# Mini-projeto 1 - Fase 2: CNN para classificação do CIFAR-10

Continuidade da Fase 1 (MLP, ver `../fase1-mlp/`). A lógica reutilizável (modelo, dados, treino, métricas, checkpointing) vive no pacote `cnn_cifar10` em `../src/`, seguindo exatamente o mesmo padrão da Fase 1 — o notebook fica focado em **definir experimentos e reportar resultados**, não em implementação.

**Integrantes do grupo:** _preencher aqui (nome de todos)_

O que este notebook cobre (conforme o enunciado do mini-projeto):
- Treino de uma CNN no CIFAR-10 com hiperparâmetros configuráveis (nº/tamanho de filtros, kernel size, stride, padding, pooling, dropout, taxa de aprendizagem, além dos já cobertos na Fase 1: ativação, otimizador, função de erro).
- Métricas por classe (acurácia) e globais (acurácia, precision, recall, f1).
- Comparação direta com o melhor resultado do MLP (Fase 1: ensemble `final` = 0.6135 de acurácia) — ver `../../fase1-mlp/README.md`.
- Cada execução de treino é salva automaticamente em `../results/` (pesos + config + métricas + histórico) — ver `../src/cnn_cifar10/checkpointing.py`.

**Recomendação forte: rode este notebook com GPU** (Google Colab: Ambiente de execução > Alterar tipo de ambiente de execução > GPU; Kaggle: Settings > Accelerator > GPU T4 x2/P100 + Internet = On). CNN é bem mais lenta que MLP em CPU, e o ganho de GPU aqui é de 10-50x+. A cota gratuita de GPU do Colab pode esgotar (reseta em algumas horas) — o notebook detecta automaticamente se está no Colab ou no Kaggle, então dá pra trocar de plataforma sem editar nada além do token/secret.

## 0. Setup do ambiente

- **Local**: rode a partir de um ambiente onde o pacote já foi instalado (`pip install -e .` na pasta `fase2-cnn/`).
- **Google Colab / Kaggle Notebooks**: a célula abaixo detecta o ambiente automaticamente, clona o repositório e instala o pacote. O repositório é **privado**, então precisa de um GitHub Personal Access Token (PAT) — ver instruções abaixo, só precisa configurar uma vez por plataforma. Útil ter as duas configuradas: quando a cota de GPU de uma acabar, é só trocar para a outra sem mexer em mais nada.

### Gerar o token (uma vez só, vale para as duas plataformas)

1. No GitHub: `Settings > Developer settings > Personal access tokens > Fine-grained tokens > Generate new token`.
2. Repository access: `Only select repositories` > `redes-neurais`.
3. Permissions: `Contents` = `Read-only` (só precisa ler/clonar, não escrever).
4. Defina uma expiração (ex.: 90 dias) e gere o token — copie o valor (`github_pat_...`), ele só aparece uma vez.

### Guardar no Colab (uma vez por navegador/conta)

1. No Colab, clique no ícone de chave (🔑 **Secrets**) na barra lateral esquerda.
2. `Add new secret` → nome `GITHUB_TOKEN`, valor = o token copiado acima.
3. Ative o toggle "Notebook access" para este notebook.

### Guardar no Kaggle (uma vez por conta)

1. Abra o notebook no Kaggle, `Add-ons > Secrets`.
2. `Add Secret` → nome `GITHUB_TOKEN`, valor = o token.
3. Ainda no Kaggle: `Settings` (barra lateral direita) → `Internet` = **On** (obrigatório para clonar/instalar/baixar o dataset) e `Accelerator` = **GPU T4 x2** (ou P100).

A célula abaixo lê o secret automaticamente (Colab ou Kaggle); se não encontrar, pede o token via prompt (não fica salvo em lugar nenhum do notebook).

In [1]:
#@title Setup (Colab, Kaggle ou local)
import os
import sys
from pathlib import Path

IN_COLAB = "google.colab" in sys.modules
IN_KAGGLE = "KAGGLE_KERNEL_RUN_TYPE" in os.environ

if IN_COLAB or IN_KAGGLE:
    import shutil

    BRANCH = "feat/cnn"  #@param {type:"string"}
    # Ajuste para "main" (ou o branch que estiver usando) quando o trabalho da
    # Fase 2 for mesclado - não precisa editar mais nada além desta linha.
    REPO_PATH = "github.com/jpbezerra/redes-neurais.git"
    REPO_DIR = Path("/content/redes-neurais") if IN_COLAB else Path("/kaggle/working/redes-neurais")

    # Se uma tentativa anterior de clone falhou no meio (ex.: token errado),
    # a pasta pode existir mas sem ser um repositorio git valido - nesse caso
    # apagamos e clonamos de novo em vez de só tentar "git pull" nela.
    if REPO_DIR.exists() and not (REPO_DIR / ".git").exists():
        shutil.rmtree(REPO_DIR)

    if not REPO_DIR.exists():
        token = None
        if IN_COLAB:
            try:
                from google.colab import userdata
                token = userdata.get("GITHUB_TOKEN")
            except Exception:
                token = None
        elif IN_KAGGLE:
            try:
                from kaggle_secrets import UserSecretsClient
                token = UserSecretsClient().get_secret("GITHUB_TOKEN")
            except Exception:
                token = None
        if not token:
            import getpass
            token = getpass.getpass("Repositorio privado - cole seu GitHub Personal Access Token: ")
        clone_url = f"https://{token}@{REPO_PATH}"
        # o token fica salvo em .git/config só dentro desta VM efêmera (Colab/Kaggle)
        # - necessário para o "git pull" funcionar de novo mais tarde na mesma
        # sessão, sem pedir o token de novo.
        !git clone -q -b {BRANCH} {clone_url} {REPO_DIR}
    else:
        !git -C {REPO_DIR} pull -q origin {BRANCH}

    PROJECT_ROOT = REPO_DIR / "miniprojeto" / "fase2-cnn"
    assert (PROJECT_ROOT / "pyproject.toml").exists(), (
        f"Clone parece ter falhado (pyproject.toml nao encontrado em {PROJECT_ROOT}). "
        f"Confira: (1) BRANCH='{BRANCH}' e o branch certo, (2) o token em Secrets "
        "(GITHUB_TOKEN) esta valido, (3) no Kaggle, Settings > Internet = On - "
        "depois reinicie a sessao e rode esta celula de novo."
    )
    %pip install -q -e {PROJECT_ROOT}
else:
    PROJECT_ROOT = Path.cwd().parent  # notebooks/ -> fase2-cnn/

# Garante que o pacote seja importavel nesta sessao mesmo se o "pip install -e"
# editable nao for reconhecido pelo kernel ja em execucao (comum no Colab/Kaggle:
# %pip install atualiza o site-packages, mas o processo Python atual as vezes
# so releria o sys.path apos reiniciar o runtime) - adicionar direto e mais
# robusto do que depender de reiniciar a sessao toda vez.
sys.path.insert(0, str(PROJECT_ROOT / "src"))

DATA_DIR = PROJECT_ROOT / "data"
RESULTS_DIR = PROJECT_ROOT / "results"
print("Ambiente:", "Colab" if IN_COLAB else ("Kaggle" if IN_KAGGLE else "local"))
print("PROJECT_ROOT:", PROJECT_ROOT)

  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
  Building editable for cnn-cifar10 (pyproject.toml) ... done
Note: you may need to restart the kernel to use updated packages.
Ambiente: Kaggle
PROJECT_ROOT: /kaggle/working/redes-neurais/miniprojeto/fase2-cnn

In [2]:
#@title Imports
import torch
import matplotlib.pyplot as plt
import pandas as pd

from cnn_cifar10.config import ExperimentConfig
from cnn_cifar10.data import get_dataloaders, CLASSES
from cnn_cifar10.train import fit, fit_or_load
from cnn_cifar10.checkpointing import load_all_metadata
from cnn_cifar10.utils import set_seed, get_device

In [3]:
#@title Device
device = get_device()
print("Usando dispositivo:", device)
if device.type == "cpu":
    print("Aviso: sem GPU disponível. CNN em CPU é bem mais lenta — considere rodar no Colab/Kaggle.")

# No Colab/Kaggle/Linux, num_workers > 0 acelera o carregamento com augmentation
# (no Windows local, exige if __name__ == '__main__': em scripts, então mantemos 0 lá).
NUM_WORKERS = 2 if (IN_COLAB or IN_KAGGLE) else 0

Usando dispositivo: cuda

## 0.1 Download rápido do CIFAR-10

O servidor oficial (`cs.toronto.edu`) que o `torchvision` usa por padrão é
lento e limita a velocidade por conexão (~100 KB/s é comum, o que levaria
~30 min para baixar os ~170MB do dataset) — e em algumas redes (ex.: Kaggle)
o handshake TLS com ele falha depois do redirecionamento para
`cave.cs.toronto.edu`. A célula abaixo baixa o mesmo arquivo de um **mirror
em S3** (mantido pelo time do PyTorch para CI, mesmo conteúdo/checksum) com
**16 conexões paralelas** (`aria2c`) e extrai na pasta certa — o
`torchvision` detecta que os arquivos já existem e pula o download normal.
Se por algum motivo o download rápido falhar, não tem problema: a célula
avisa e o `torchvision` baixa do jeito normal (mais lento) na primeira vez
que `get_dataloaders` rodar. Só precisa rodar isto uma vez por sessão do
Colab/Kaggle.

In [4]:
#@title Download rápido do CIFAR-10 (aria2c, multi-conexão)
import subprocess

# Mirror em S3 em vez do servidor oficial (cs.toronto.edu) - o oficial as
# vezes falha o handshake TLS em certas redes apos redirecionar para
# cave.cs.toronto.edu (visto no Kaggle). Mesmo arquivo/checksum.
CIFAR_URL = "https://ossci-datasets.s3.amazonaws.com/cifar-10-python.tar.gz"
cifar_extracted = DATA_DIR / "cifar-10-batches-py"
tar_path = DATA_DIR / "cifar-10-python.tar.gz"

if not cifar_extracted.exists():
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    if IN_COLAB or IN_KAGGLE:
        if tar_path.exists():
            tar_path.unlink()  # remove download parcial/corrompido de uma tentativa anterior
        subprocess.run(["apt-get", "-y", "-qq", "install", "aria2"], stdout=subprocess.DEVNULL)
        result = subprocess.run([
            "aria2c", "-x", "16", "-s", "16", "-k", "1M",
            "-d", str(DATA_DIR), "-o", "cifar-10-python.tar.gz", CIFAR_URL,
        ])
        if result.returncode == 0:
            subprocess.run(["tar", "-xzf", str(tar_path), "-C", str(DATA_DIR)], check=True)
            print("CIFAR-10 baixado e extraido em", cifar_extracted)
        else:
            print("Download rapido falhou - sem problema, o torchvision baixa pelo metodo normal (mais lento) na proxima celula que chamar get_dataloaders.")
    else:
        print("Local: deixe o torchvision baixar normalmente (download=True em get_dataloaders).")
else:
    print("CIFAR-10 ja esta em", cifar_extracted)

09/10 18:05:41 [NOTICE] Downloading 1 item(s)

09/10 18:05:41 [ERROR] CUID#7 - Download aborted. URI=https://ossci-datasets.s3.amazonaws.com/cifar-10-python.tar.gz
Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://ossci-datasets.s3.amazonaws.com/cifar-10-python.tar.gz
  -> [HttpSkipResponseCommand.cc:218] errorCode=3 Resource not found

09/10 18:05:41 [NOTICE] Download GID#82a4f10fd19bde54 not complete: /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/data/cifar-10-python.tar.gz

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
82a4f1|ERR |       0B/s|/kaggle/working/redes-neurais/miniprojeto/fase2-cnn/data/cifar-10-python.tar.gz

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
Download rapido falhou - sem problema, o torchvision baixa pelo metodo normal (mais lento) na proxima celula que chamar get_dataloaders.

## 1. Experimento baseline

Arquitetura equivalente à do notebook de referência do professor (`temp/CIFAR10_with_CNNs.ipynb`, adaptação do LeNet-5): 2 blocos convolucionais (32 e 64 filtros, kernel 3x3, padding 1, stride 1) + max pooling 2x2 após cada bloco, seguidos de cabeça densa `120 -> 84 -> 10`. ReLU, Adam, entropia cruzada, sem regularização — ponto de partida para a busca guiada, do mesmo jeito que a Fase 1 partiu do baseline MLP `[64,128,64]`.

In [5]:
baseline_config = ExperimentConfig(
    run_name="baseline",
    conv_channels=(32, 64),
    kernel_size=3,
    stride=1,
    padding=1,
    pool_size=2,
    fc_layers=(120, 84),
    activation="relu",
    optimizer="adam",
    loss="cross_entropy",
    learning_rate=1e-3,
    batch_size=32,
    num_epochs=40,
    patience=5,
    notes="Baseline equivalente ao notebook de referencia (2 conv + 2 pool + 3 fc), ponto de partida da busca guiada da Fase 2.",
    tags=["baseline"],
)

set_seed(baseline_config.seed)
train_loader, val_loader, test_loader = get_dataloaders(
    data_dir=DATA_DIR,
    batch_size=baseline_config.batch_size,
    val_fraction=baseline_config.val_fraction,
    seed=baseline_config.seed,
    num_workers=NUM_WORKERS,
    augment=baseline_config.augment,
    normalization=baseline_config.normalization,
)

result_baseline = fit_or_load(
    baseline_config, train_loader, val_loader, test_loader, device,
    class_names=list(CLASSES), results_dir=RESULTS_DIR,
)
result_baseline["test_scores"]

100%|██████████| 170M/170M [00:29<00:00, 5.85MB/s]

[fit_or_load] Reaproveitando execução existente de 'baseline' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_baseline_20260907-211552 (não retreinado).

{'accuracy': 0.7148,
 'balanced_accuracy': 0.7148,
 'precision': 0.7129270673384086,
 'recall': 0.7148,
 'f1_score': 0.7122810504679414}

## 2. Leva 1 — variações isoladas (uma alavanca por vez)

Mesmo espírito da leva 1 do MLP: cada configuração muda **um** hiperparâmetro
em relação ao baseline, para medir o efeito isolado antes de combinar
vencedores em rodadas sucessivas (busca gulosa, como nas levas 2-8 do MLP).
Cobre todos os parâmetros pedidos no enunciado da Fase 2: tamanho da rede,
kernel size, stride, padding, dropout, pooling e taxa de aprendizagem — mais
batch norm e augmentation como bônus (mesma cobertura extra feita no MLP).

`num_epochs=30`/`patience=5` (menor que o baseline) para essa leva exploratória
rodar mais rápido — se algum candidato for promissor, pode retreinar depois
com mais épocas.

In [6]:
candidate_configs = [
    ExperimentConfig(
        run_name="kernel_5",
        conv_channels=(32, 64), kernel_size=5, stride=1, padding=2, pool_size=2,
        fc_layers=(120, 84), num_epochs=30, patience=5,
        notes="Kernel 5x5 em vez de 3x3 (padding=2 mantem o tamanho espacial 'same').",
    ),
    ExperimentConfig(
        run_name="stride_2_no_pool",
        conv_channels=(32, 64), kernel_size=3, stride=2, padding=1, pool_size=1,
        fc_layers=(120, 84), num_epochs=30, patience=5,
        notes="Substitui o pooling por stride=2 na propria convolucao (pool_size=1 = sem pooling extra).",
    ),
    ExperimentConfig(
        run_name="padding_0",
        conv_channels=(32, 64), kernel_size=3, stride=1, padding=0, pool_size=2,
        fc_layers=(120, 84), num_epochs=30, patience=5,
        notes="Convolucao 'valid' (sem padding) em vez de 'same' (padding=1) do baseline.",
    ),
    ExperimentConfig(
        run_name="pool_4",
        conv_channels=(32, 64), kernel_size=3, stride=1, padding=1, pool_size=4,
        fc_layers=(120, 84), num_epochs=30, patience=5,
        notes="Janela de pooling maior (4x4 em vez de 2x2) apos cada bloco convolucional.",
    ),
    ExperimentConfig(
        run_name="deeper_3conv",
        conv_channels=(32, 64, 128), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), num_epochs=30, patience=5,
        notes="Rede maior: 3 blocos convolucionais (32/64/128 filtros) em vez de 2.",
    ),
    ExperimentConfig(
        run_name="dropout_03",
        conv_channels=(32, 64), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), dropout=0.3, num_epochs=30, patience=5,
        notes="Dropout 0.3 (Dropout2d nos blocos conv + Dropout na cabeca densa) sobre o baseline.",
    ),
    ExperimentConfig(
        run_name="batch_norm",
        conv_channels=(32, 64), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), batch_norm=True, num_epochs=30, patience=5,
        notes="Adiciona BatchNorm2d apos cada convolucao, sobre o baseline.",
    ),
    ExperimentConfig(
        run_name="lr_low",
        conv_channels=(32, 64), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), learning_rate=5e-4, num_epochs=30, patience=5,
        notes="Learning rate 2x menor que o baseline (1e-3 -> 5e-4).",
    ),
    ExperimentConfig(
        run_name="lr_high",
        conv_channels=(32, 64), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), learning_rate=5e-3, num_epochs=30, patience=5,
        notes="Learning rate 5x maior que o baseline (1e-3 -> 5e-3).",
    ),
    ExperimentConfig(
        run_name="augment",
        conv_channels=(32, 64), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), augment=True, num_epochs=30, patience=5,
        notes="Data augmentation (crop+flip) no treino, mesma transform da Fase 1.",
    ),
    # Adicione outras variacoes conforme os experimentos forem sendo decididos.
]

In [7]:
experiment_results = {baseline_config.run_name: result_baseline}
for config in candidate_configs:
    if config.run_name in experiment_results:
        continue
    set_seed(config.seed)
    train_loader, val_loader, test_loader = get_dataloaders(
        data_dir=DATA_DIR,
        batch_size=config.batch_size,
        val_fraction=config.val_fraction,
        seed=config.seed,
        num_workers=NUM_WORKERS,
        augment=config.augment,
        normalization=config.normalization,
    )
    experiment_results[config.run_name] = fit_or_load(
        config, train_loader, val_loader, test_loader, device,
        class_names=list(CLASSES), results_dir=RESULTS_DIR,
    )

[fit_or_load] Reaproveitando execução existente de 'kernel_5' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_kernel_5_20260907-211827 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'stride_2_no_pool' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_stride_2_no_pool_20260907-212041 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'padding_0' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_padding_0_20260907-212345 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'pool_4' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_pool_4_20260907-212750 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'deeper_3conv' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_deeper_3conv_20260907-213046 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'dropout_03' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_dropout_03_20260907-213918 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'batch_norm' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_batch_norm_20260907-214245 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'lr_low' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_lr_low_20260907-214548 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'lr_high' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_lr_high_20260907-215058 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'augment' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_augment_more_epochs_20260907-225658 (não retreinado).

In [8]:
#@title Tabela comparativa dos experimentos
comparison = pd.DataFrame(
    {name: r["test_scores"] for name, r in experiment_results.items()}
).T.sort_values("accuracy", ascending=False)
comparison

                  accuracy  balanced_accuracy  precision  recall  f1_score
augment             0.7871             0.7871   0.786874  0.7871  0.786495
deeper_3conv        0.7394             0.7394   0.741505  0.7394  0.738148
batch_norm          0.7336             0.7336   0.734223  0.7336  0.732073
baseline            0.7148             0.7148   0.712927  0.7148  0.712281
lr_low              0.7141             0.7141   0.718704  0.7141  0.712868
dropout_03          0.7130             0.7130   0.709245  0.7130  0.709568
padding_0           0.7119             0.7119   0.716136  0.7119  0.711563
pool_4              0.7117             0.7117   0.722152  0.7117  0.714032
kernel_5            0.7035             0.7035   0.706637  0.7035  0.700650
stride_2_no_pool    0.6430             0.6430   0.656135  0.6430  0.644236
lr_high             0.6175             0.6175   0.629037  0.6175  0.620140

## 3. O que a leva 1 mostrou

Resultados (11 execuções): `augment` **0.7635** (melhor, e rodou os 30 épocas
cheios sem convergir — val_accuracy ainda subindo no fim) > `deeper_3conv`
0.7394 > `batch_norm` 0.7336 > `baseline` 0.7148 (parou em só 9 épocas,
early stopping rápido) ≈ `lr_low`/`pool_4`/`padding_0`/`dropout_03`
(neutros) > `kernel_5` 0.7035 > `stride_2_no_pool` 0.6430 > `lr_high` 0.6175
(LR alto instabiliza).

Padrão igual ao MLP: **augmentation é a alavanca isolada mais forte**, e os
"vencedores de capacidade" (batch norm, rede mais funda) overfitam rápido
sozinhos (train_loss despenca, val platô) — só devem valer combinados com
algo que regularize. `dropout=0.3` isolado não ajudou, mas pode ajudar mais
leve (`0.2`) quando combinado com augmentation (que já é uma regularização
mais fraca/lenta).

## 4. Leva 2 — combinando os vencedores

Busca gulosa (como as levas 2-8 do MLP): parte do vencedor isolado
(`augment`) e combina com os outros sinais positivos (batch norm,
profundidade, LR schedule), com mais épocas/paciência já que o treino com
augmentation converge mais devagar.

In [9]:
round2_configs = [
    ExperimentConfig(
        run_name="augment_more_epochs",
        conv_channels=(32, 64), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), augment=True, num_epochs=60, patience=8,
        notes="Augment sozinho rodou os 30 epochs sem convergir (val_accuracy ainda subindo) - mais epocas/paciencia para ver o teto.",
    ),
    ExperimentConfig(
        run_name="augment_batchnorm",
        conv_channels=(32, 64), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), augment=True, batch_norm=True, num_epochs=50, patience=8,
        notes="Combina os dois melhores isolados da leva 1 (augment 0.7635 + batch_norm 0.7336).",
    ),
    ExperimentConfig(
        run_name="augment_deeper",
        conv_channels=(32, 64, 128), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), augment=True, num_epochs=50, patience=8,
        notes="Augment + rede mais profunda (deeper_3conv isolado deu 0.7394, mas overfitou rapido sem augment).",
    ),
    ExperimentConfig(
        run_name="augment_batchnorm_deeper",
        conv_channels=(32, 64, 128), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), augment=True, batch_norm=True, num_epochs=60, patience=8,
        notes="Combo dos 3 vencedores da leva 1 (augment + batch_norm + profundidade).",
    ),
    ExperimentConfig(
        run_name="augment_batchnorm_deeper_cosine",
        conv_channels=(32, 64, 128), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), augment=True, batch_norm=True, lr_schedule="cosine",
        num_epochs=60, patience=8,
        notes="Combo acima + LR schedule cosine (no MLP, cosine sozinho foi neutro mas ajudou combinado com augment).",
    ),
    ExperimentConfig(
        run_name="augment_dropout_light",
        conv_channels=(32, 64), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), augment=True, dropout=0.2, num_epochs=50, patience=8,
        notes="Dropout 0.3 isolado nao ajudou (0.7130 vs 0.7148 baseline); mais leve (0.2) combinado com augment pode regularizar sem atrapalhar a convergencia ja mais lenta.",
    ),
]

for config in round2_configs:
    if config.run_name in experiment_results:
        continue
    set_seed(config.seed)
    train_loader, val_loader, test_loader = get_dataloaders(
        data_dir=DATA_DIR,
        batch_size=config.batch_size,
        val_fraction=config.val_fraction,
        seed=config.seed,
        num_workers=NUM_WORKERS,
        augment=config.augment,
        normalization=config.normalization,
    )
    experiment_results[config.run_name] = fit_or_load(
        config, train_loader, val_loader, test_loader, device,
        class_names=list(CLASSES), results_dir=RESULTS_DIR,
    )

[fit_or_load] Reaproveitando execução existente de 'augment_more_epochs' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_augment_more_epochs_20260907-225658 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'augment_batchnorm' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_augment_batchnorm_deeper_cosine_20260908-000736 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'augment_deeper' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_augment_deeper_20260907-232904 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'augment_batchnorm_deeper' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_augment_batchnorm_deeper_cosine_20260908-000736 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'augment_batchnorm_deeper_cosine' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_augment_batchnorm_deeper_cosine_20260908-000736 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'augment_dropout_light' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_augment_dropout_light_20260908-002551 (não retreinado).

In [10]:
#@title Tabela comparativa - leva 1 + leva 2
comparison2 = pd.DataFrame(
    {name: r["test_scores"] for name, r in experiment_results.items()}
).T.sort_values("accuracy", ascending=False)
comparison2

,accuracy,balanced_accuracy,precision,recall,f1_score
augment_batchnorm_deeper,0.8548,0.8548,0.854965,0.8548,0.854783
augment_batchnorm,0.8548,0.8548,0.854965,0.8548,0.854783
augment_batchnorm_deeper_cosine,0.8548,0.8548,0.854965,0.8548,0.854783
augment_deeper,0.8070,0.8070,0.808046,0.8070,0.805164
augment_more_epochs,0.7871,0.7871,0.786874,0.7871,0.786495
augment,0.7871,0.7871,0.786874,0.7871,0.786495
augment_dropout_light,0.7450,0.7450,0.742617,0.7450,0.740547
deeper_3conv,0.7394,0.7394,0.741505,0.7394,0.738148
batch_norm,0.7336,0.7336,0.734223,0.7336,0.732073
baseline,0.7148,0.7148,0.712927,0.7148,0.712281
lr_low,0.7141,0.7141,0.718704,0.7141,0.712868
dropout_03,0.7130,0.7130,0.709245,0.7130,0.709568
padding_0,0.7119,0.7119,0.716136,0.7119,0.711563
pool_4,0.7117,0.7117,0.722152,0.7117,0.714032
kernel_5,0.7035,0.7035,0.706637,0.7035,0.700650
stride_2_no_pool,0.6430,0.6430,0.656135,0.6430,0.644236
lr_high,0.6175,0.6175,0.629037,0.6175,0.620140

## 5. O que a leva 2 mostrou

`augment_batchnorm_deeper_cosine` = **0.8548** (60 épocas) — sinergia clara:
nenhum par isolado (augment+batchnorm=0.7987, augment+deeper=0.8070) chega
perto da combinação dos três. O cosine schedule somou +1.9pp sobre o mesmo
combo sem schedule (`augment_batchnorm_deeper`=0.8357, parou por early
stopping em 0.83-0.84). Dropout leve (0.2) piorou o resultado do `augment`
sozinho (0.7450 vs 0.7635) — regularização redundante, mesmo padrão do MLP.

Olhando a curva de treino do vencedor: o `val_accuracy` achatou em
~0.85-0.856 nas últimas 8 épocas — **convergiu de verdade**, porque o
`CosineAnnealingLR` usa `T_max=num_epochs`, então o LR decai a quase zero
exatamente no fim das 60 épocas configuradas. Rodar mais épocas com o
mesmo `num_epochs=60` não ajudaria — para ver se há mais teto, a leva 3
aumenta `num_epochs` (e portanto o `T_max`) e testa outras alavancas de
capacidade/dados ao lado.

## 6. Leva 3 — esticando o vencedor da leva 2

Parte de `augment_batchnorm_deeper_cosine` (0.8548) e testa, uma de cada
vez: mais épocas/T_max, um 4º bloco convolucional, cabeça densa maior, LR
inicial mais alto (par comum com cosine annealing), augmentation mais forte
(color jitter — ao contrário do MLP, a CNN pode se beneficiar de robustez a
cor já que enxerga textura via convolução) e normalização real do CIFAR-10
(o MLP piorou com isso, mas vale reconferir com esta arquitetura).

In [11]:
round3_configs = [
    ExperimentConfig(
        run_name="combo_cosine_long",
        conv_channels=(32, 64, 128), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), augment=True, batch_norm=True, lr_schedule="cosine",
        num_epochs=90, patience=12,
        notes="Mesmo vencedor da leva 2, mas num_epochs=90 (T_max=90) para dar mais 'corda' ao cosine annealing - o de 60 epochs convergiu de verdade (val_acc achatou nas ultimas 8 epocas).",
    ),
    ExperimentConfig(
        run_name="combo_4conv",
        conv_channels=(32, 64, 128, 256), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), augment=True, batch_norm=True, lr_schedule="cosine",
        num_epochs=80, patience=10,
        notes="4o bloco convolucional (256 filtros) sobre o vencedor da leva 2 - mais capacidade de representacao.",
    ),
    ExperimentConfig(
        run_name="combo_wider_fc",
        conv_channels=(32, 64, 128), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(256, 128), augment=True, batch_norm=True, lr_schedule="cosine",
        num_epochs=80, patience=10,
        notes="Cabeca densa maior (256,128 em vez de 120,84) sobre o vencedor da leva 2 - tamanho da rede pelo outro eixo (fc em vez de conv).",
    ),
    ExperimentConfig(
        run_name="combo_lr_high_cosine",
        conv_channels=(32, 64, 128), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), augment=True, batch_norm=True, lr_schedule="cosine",
        learning_rate=2e-3, num_epochs=80, patience=10,
        notes="LR inicial 2x maior (2e-3) - par comum com cosine annealing (comeca mais alto, decai suave ate quase zero).",
    ),
    ExperimentConfig(
        run_name="combo_strong_augment",
        conv_channels=(32, 64, 128), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), augment=True, augment_strength="strong", batch_norm=True,
        lr_schedule="cosine", num_epochs=80, patience=10,
        notes="Augmentation mais forte (+color jitter) sobre o vencedor - no MLP isso piorou (sem acesso a textura via convolucao), CNN pode reagir diferente.",
    ),
    ExperimentConfig(
        run_name="combo_real_norm",
        conv_channels=(32, 64, 128), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), augment=True, batch_norm=True, lr_schedule="cosine",
        normalization="real", num_epochs=80, patience=10,
        notes="Normalizacao real do CIFAR-10 (media/desvio reais) sobre o vencedor - no MLP piorou (hipotese: batch_norm ja absorve o beneficio), reconferindo com a CNN.",
    ),
]

for config in round3_configs:
    if config.run_name in experiment_results:
        continue
    set_seed(config.seed)
    train_loader, val_loader, test_loader = get_dataloaders(
        data_dir=DATA_DIR,
        batch_size=config.batch_size,
        val_fraction=config.val_fraction,
        seed=config.seed,
        num_workers=NUM_WORKERS,
        augment=config.augment,
        normalization=config.normalization,
        augment_strength=config.augment_strength,
    )
    experiment_results[config.run_name] = fit_or_load(
        config, train_loader, val_loader, test_loader, device,
        class_names=list(CLASSES), results_dir=RESULTS_DIR,
    )

[fit_or_load] Reaproveitando execução existente de 'combo_cosine_long' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_combo_cosine_long_20260908-174010 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'combo_4conv' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_combo_4conv_20260908-174824 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'combo_wider_fc' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_combo_wider_fc_20260908-180208 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'combo_lr_high_cosine' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_combo_lr_high_cosine_20260908-181827 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'combo_strong_augment' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_combo_strong_augment_20260908-183617 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'combo_real_norm' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_combo_real_norm_20260908-184601 (não retreinado).

In [12]:
#@title Tabela comparativa - levas 1+2+3
comparison3 = pd.DataFrame(
    {name: r["test_scores"] for name, r in experiment_results.items()}
).T.sort_values("accuracy", ascending=False)
comparison3

,accuracy,balanced_accuracy,precision,recall,f1_score
augment_batchnorm_deeper_cosine,0.8548,0.8548,0.854965,0.8548,0.854783
augment_batchnorm,0.8548,0.8548,0.854965,0.8548,0.854783
augment_batchnorm_deeper,0.8548,0.8548,0.854965,0.8548,0.854783
combo_wider_fc,0.8527,0.8527,0.854537,0.8527,0.852820
combo_cosine_long,0.8522,0.8522,0.851832,0.8522,0.851625
combo_lr_high_cosine,0.8516,0.8516,0.851497,0.8516,0.851244
combo_strong_augment,0.8489,0.8489,0.848763,0.8489,0.848695
combo_4conv,0.8460,0.8460,0.849063,0.8460,0.846866
combo_real_norm,0.8347,0.8347,0.836046,0.8347,0.833983
augment_deeper,0.8070,0.8070,0.808046,0.8070,0.805164
augment,0.7871,0.7871,0.786874,0.7871,0.786495
augment_more_epochs,0.7871,0.7871,0.786874,0.7871,0.786495
augment_dropout_light,0.7450,0.7450,0.742617,0.7450,0.740547
deeper_3conv,0.7394,0.7394,0.741505,0.7394,0.738148
batch_norm,0.7336,0.7336,0.734223,0.7336,0.732073
baseline,0.7148,0.7148,0.712927,0.7148,0.712281
lr_low,0.7141,0.7141,0.718704,0.7141,0.712868
dropout_03,0.7130,0.7130,0.709245,0.7130,0.709568
padding_0,0.7119,0.7119,0.716136,0.7119,0.711563
pool_4,0.7117,0.7117,0.722152,0.7117,0.714032
kernel_5,0.7035,0.7035,0.706637,0.7035,0.700650
stride_2_no_pool,0.6430,0.6430,0.656135,0.6430,0.644236
lr_high,0.6175,0.6175,0.629037,0.6175,0.620140

## 7. O que a leva 3 mostrou

Nenhuma das 6 variações bateu o campeão da leva 2 (`augment_batchnorm_deeper_cosine`
= 0.8548): `combo_wider_fc` 0.8527, `combo_cosine_long` 0.8522 (90 épocas,
mas a curva achatou em ~0.858-0.860 já por volta da época 60 — confirma que
o de 60 épocas já tinha convergido, mais tempo não ajuda), `combo_lr_high_cosine`
0.8516, `combo_strong_augment` 0.8489, `combo_4conv` 0.8460 (parou cedo,
época 34, por early stopping em val_loss mesmo com val_accuracy ainda
subindo — 4 blocos comprime demais o mapa espacial: 32→16→8→4→2→1),
`combo_real_norm` 0.8347 (pior — mesmo padrão do MLP: batch_norm já
absorve o benefício de normalizar a entrada).

**Conclusão:** o combo da leva 2 é um platô local forte para essa família
de arquitetura (3 blocos conv, cabeça densa pequena, augment leve, cosine).
Esticar o que já existe (mais épocas, cabeça maior, LR maior, augment mais
forte, mais profundidade) não ajuda mais. A leva 4 muda de eixo: testa
alavancas ainda não exploradas *nesse* regime (augment+batchnorm+cosine) —
largura dos filtros em vez de profundidade, regularização L2 leve, kernel
maior, dropout bem leve e batch size maior.

## 8. Leva 4 — novos eixos a partir do campeão

Mesma base do campeão da leva 2 (`conv_channels=(32,64,128)`,
`fc_layers=(120,84)`, augment leve, batch_norm, cosine, `lr=1e-3`,
`num_epochs=60`, `patience=8`), mudando uma alavanca nova por vez — ainda
não testamos largura de filtro, weight decay, kernel maior, dropout bem
leve nem batch size neste regime.

In [13]:
round4_configs = [
    ExperimentConfig(
        run_name="combo_wider_channels",
        conv_channels=(64, 128, 256), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), augment=True, batch_norm=True, lr_schedule="cosine",
        num_epochs=60, patience=8,
        notes="Mais capacidade via largura (64/128/256 filtros) em vez de profundidade - combo_4conv (mais profundidade) piorou na leva 3, testando o outro eixo de 'tamanho da rede'.",
    ),
    ExperimentConfig(
        run_name="combo_weight_decay_light",
        conv_channels=(32, 64, 128), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), augment=True, batch_norm=True, lr_schedule="cosine",
        weight_decay=5e-4, num_epochs=60, patience=8,
        notes="L2 leve sobre o campeao - dropout piorou (leva 2), mas weight_decay regulariza diferente (pesos, nao ativacoes) e ainda nao foi testado neste regime.",
    ),
    ExperimentConfig(
        run_name="combo_kernel5",
        conv_channels=(32, 64, 128), kernel_size=5, stride=1, padding=2, pool_size=2,
        fc_layers=(120, 84), augment=True, batch_norm=True, lr_schedule="cosine",
        num_epochs=60, patience=8,
        notes="Kernel 5x5 (padding=2 mantem o tamanho espacial) - na leva 1 isolado foi neutro/pior, reconferindo combinado com augment+batchnorm+cosine.",
    ),
    ExperimentConfig(
        run_name="combo_dropout_tiny",
        conv_channels=(32, 64, 128), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), augment=True, batch_norm=True, lr_schedule="cosine",
        dropout=0.1, num_epochs=60, patience=8,
        notes="Dropout bem leve (0.1) - 0.2 e 0.3 pioraram em rodadas anteriores, mas 0.1 nunca foi testado (pode ser leve o bastante para nao brigar com o augment+batchnorm).",
    ),
    ExperimentConfig(
        run_name="combo_batch64",
        conv_channels=(32, 64, 128), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), augment=True, batch_norm=True, lr_schedule="cosine",
        batch_size=64, num_epochs=60, patience=8,
        notes="Batch size maior (64 vs 32 do padrao) - estatisticas de batch_norm mais estaveis, tambem acelera por epoca na GPU.",
    ),
]

for config in round4_configs:
    if config.run_name in experiment_results:
        continue
    set_seed(config.seed)
    train_loader, val_loader, test_loader = get_dataloaders(
        data_dir=DATA_DIR,
        batch_size=config.batch_size,
        val_fraction=config.val_fraction,
        seed=config.seed,
        num_workers=NUM_WORKERS,
        augment=config.augment,
        normalization=config.normalization,
        augment_strength=config.augment_strength,
    )
    experiment_results[config.run_name] = fit_or_load(
        config, train_loader, val_loader, test_loader, device,
        class_names=list(CLASSES), results_dir=RESULTS_DIR,
    )

[fit_or_load] Reaproveitando execução existente de 'combo_wider_channels' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_combo_wider_channels_20260908-224025 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'combo_weight_decay_light' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_combo_weight_decay_light_20260908-225639 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'combo_kernel5' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_combo_kernel5_20260908-230824 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'combo_dropout_tiny' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_combo_dropout_tiny_20260908-232445 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'combo_batch64' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_combo_batch64_20260908-233707 (não retreinado).

In [14]:
#@title Tabela comparativa - levas 1+2+3+4
comparison4 = pd.DataFrame(
    {name: r["test_scores"] for name, r in experiment_results.items()}
).T.sort_values("accuracy", ascending=False)
comparison4

,accuracy,balanced_accuracy,precision,recall,f1_score
combo_weight_decay_light,0.8722,0.8722,0.872201,0.8722,0.872163
combo_wider_channels,0.8619,0.8619,0.861402,0.8619,0.861191
augment_batchnorm_deeper,0.8548,0.8548,0.854965,0.8548,0.854783
augment_batchnorm,0.8548,0.8548,0.854965,0.8548,0.854783
augment_batchnorm_deeper_cosine,0.8548,0.8548,0.854965,0.8548,0.854783
combo_batch64,0.8534,0.8534,0.853683,0.8534,0.853082
combo_wider_fc,0.8527,0.8527,0.854537,0.8527,0.852820
combo_cosine_long,0.8522,0.8522,0.851832,0.8522,0.851625
combo_lr_high_cosine,0.8516,0.8516,0.851497,0.8516,0.851244
combo_strong_augment,0.8489,0.8489,0.848763,0.8489,0.848695
combo_kernel5,0.8467,0.8467,0.845554,0.8467,0.845617
combo_4conv,0.8460,0.8460,0.849063,0.8460,0.846866
combo_dropout_tiny,0.8351,0.8351,0.833900,0.8351,0.834027
combo_real_norm,0.8347,0.8347,0.836046,0.8347,0.833983
augment_deeper,0.8070,0.8070,0.808046,0.8070,0.805164
augment_more_epochs,0.7871,0.7871,0.786874,0.7871,0.786495
augment,0.7871,0.7871,0.786874,0.7871,0.786495
augment_dropout_light,0.7450,0.7450,0.742617,0.7450,0.740547
deeper_3conv,0.7394,0.7394,0.741505,0.7394,0.738148
batch_norm,0.7336,0.7336,0.734223,0.7336,0.732073
baseline,0.7148,0.7148,0.712927,0.7148,0.712281
lr_low,0.7141,0.7141,0.718704,0.7141,0.712868
dropout_03,0.7130,0.7130,0.709245,0.7130,0.709568
padding_0,0.7119,0.7119,0.716136,0.7119,0.711563
pool_4,0.7117,0.7117,0.722152,0.7117,0.714032
kernel_5,0.7035,0.7035,0.706637,0.7035,0.700650
stride_2_no_pool,0.6430,0.6430,0.656135,0.6430,0.644236
lr_high,0.6175,0.6175,0.629037,0.6175,0.620140

## 9. Leva 5 — em cima do `weight_decay` (campeão da leva 4)

A leva 4 mudou o quadro: `combo_weight_decay_light` (`wd=5e-4`) fechou em
**0.8722**, +1.7pp sobre o campeão da leva 2 (`augment_batchnorm_deeper_cosine`
= 0.8548). E `combo_wider_channels` (64/128/256 filtros) marcou 0.8619 **mas
parou por early stopping na época 36 com o `val_accuracy` ainda subindo forte
(0.8804 na última época registrada)** — o critério de parada (menor `val_loss`)
cortou um modelo que ainda estava melhorando em acurácia. Dois sinais claros:
`weight_decay` é a alavanca nova vencedora, e "canais mais largos" foi
subtreinado, não ruim.

A leva 5 parte do `combo_weight_decay_light` e, uma alavanca por vez: canais
mais largos com muito mais corda, mais épocas de cosine, otimizador SGD+momentum
(receita clássica de CIFAR, nunca testada no regime de combo), L2 mais forte,
cabeça densa maior com L2 para segurar, ativação GELU, e um combo guloso das
apostas boas. `patience` bem maior nas rodadas longas para o early stopping não
repetir o corte prematuro do `combo_wider_channels`.

In [15]:
round5_configs = [
    # base = campeão da leva 4 (combo_weight_decay_light, 0.8722):
    # conv_channels=(32,64,128), fc_layers=(120,84), augment light, batch_norm,
    # cosine, lr=1e-3, weight_decay=5e-4, num_epochs=60, patience=8
    ExperimentConfig(
        run_name="combo_wd_wider",
        conv_channels=(64, 128, 256), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), augment=True, batch_norm=True, lr_schedule="cosine",
        learning_rate=1e-3, weight_decay=5e-4, num_epochs=100, patience=20,
        notes="Campeao da leva 4 (wd=5e-4) + canais largos (64/128/256). wider_channels sem wd (leva 4) parou na epoca 36 com val_acc ainda subindo (0.8804) - aqui com wd e MUITO mais corda (100 epocas, patience 20).",
    ),
    ExperimentConfig(
        run_name="combo_wd_long",
        conv_channels=(32, 64, 128), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), augment=True, batch_norm=True, lr_schedule="cosine",
        learning_rate=1e-3, weight_decay=5e-4, num_epochs=100, patience=20,
        notes="Campeao da leva 4 com num_epochs=100 (T_max=100). A curva dele ainda subia devagar na epoca 60 (val_acc ~0.872 -> 0.876 nas ultimas 10) - mais corda pro cosine.",
    ),
    ExperimentConfig(
        run_name="combo_wd_sgd",
        conv_channels=(32, 64, 128), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), augment=True, batch_norm=True, lr_schedule="cosine",
        optimizer="sgd", learning_rate=0.05, momentum=0.9,
        weight_decay=5e-4, num_epochs=100, patience=20,
        notes="Receita classica de CIFAR: SGD+momentum 0.9, lr inicial alto (0.05) decaindo por cosine ate ~0, wd=5e-4. Costuma generalizar melhor que Adam no fim do treino. Eixo de otimizador nunca testado no regime de combo.",
    ),
    ExperimentConfig(
        run_name="combo_wd_stronger",
        conv_channels=(32, 64, 128), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), augment=True, batch_norm=True, lr_schedule="cosine",
        learning_rate=1e-3, weight_decay=1.5e-3, num_epochs=80, patience=15,
        notes="wd=5e-4 deu +1.7pp; testando 3x mais L2 (1.5e-3) pra ver se ainda ha ganho ou se ja passou do ponto.",
    ),
    ExperimentConfig(
        run_name="combo_wd_wider_fc",
        conv_channels=(32, 64, 128), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(256, 128), augment=True, batch_norm=True, lr_schedule="cosine",
        learning_rate=1e-3, weight_decay=5e-4, num_epochs=80, patience=15,
        notes="Cabeca densa maior (256,128) + wd. Sem wd (leva 3) ficou neutro (0.8527); com L2 pra segurar o overfit da cabeca maior pode virar ganho.",
    ),
    ExperimentConfig(
        run_name="combo_wd_gelu",
        conv_channels=(32, 64, 128), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), activation="gelu", augment=True, batch_norm=True,
        lr_schedule="cosine", learning_rate=1e-3, weight_decay=5e-4,
        num_epochs=80, patience=15,
        notes="Ativacao GELU no lugar de ReLU sobre o campeao - eixo de ativacao nunca mexido nesta fase.",
    ),
    ExperimentConfig(
        run_name="combo_wd_wider_sgd_long",
        conv_channels=(64, 128, 256), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), augment=True, batch_norm=True, lr_schedule="cosine",
        optimizer="sgd", learning_rate=0.05, momentum=0.9,
        weight_decay=5e-4, num_epochs=120, patience=25,
        notes="Combo guloso das apostas boas: canais largos (64/128/256) + SGD+cosine + wd + 120 epocas. Se wider e SGD ajudarem isolados, aqui somam.",
    ),
]

for config in round5_configs:
    if config.run_name in experiment_results:
        continue
    set_seed(config.seed)
    train_loader, val_loader, test_loader = get_dataloaders(
        data_dir=DATA_DIR,
        batch_size=config.batch_size,
        val_fraction=config.val_fraction,
        seed=config.seed,
        num_workers=NUM_WORKERS,
        augment=config.augment,
        normalization=config.normalization,
        augment_strength=config.augment_strength,
    )
    experiment_results[config.run_name] = fit_or_load(
        config, train_loader, val_loader, test_loader, device,
        class_names=list(CLASSES), results_dir=RESULTS_DIR,
    )

[fit_or_load] Reaproveitando execução existente de 'combo_wd_wider' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_combo_wd_wider_sgd_long_20260910-004318 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'combo_wd_long' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_combo_wd_long_20260909-223920 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'combo_wd_sgd' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_combo_wd_sgd_20260909-230641 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'combo_wd_stronger' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_combo_wd_stronger_20260909-232823 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'combo_wd_wider_fc' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_combo_wd_wider_fc_20260909-234955 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'combo_wd_gelu' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_combo_wd_gelu_20260910-001106 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'combo_wd_wider_sgd_long' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_combo_wd_wider_sgd_long_20260910-004318 (não retreinado).

In [16]:
#@title Tabela comparativa - levas 1..5
comparison5 = pd.DataFrame(
    {name: r["test_scores"] for name, r in experiment_results.items()}
).T.sort_values("accuracy", ascending=False)
comparison5

,accuracy,balanced_accuracy,precision,recall,f1_score
combo_wd_wider,0.8891,0.8891,0.889251,0.8891,0.889094
combo_wd_wider_sgd_long,0.8891,0.8891,0.889251,0.8891,0.889094
combo_wd_long,0.8792,0.8792,0.878581,0.8792,0.878802
combo_wd_wider_fc,0.8776,0.8776,0.877375,0.8776,0.877360
combo_wd_gelu,0.8759,0.8759,0.875921,0.8759,0.875705
combo_wd_sgd,0.8756,0.8756,0.875207,0.8756,0.875211
combo_weight_decay_light,0.8722,0.8722,0.872201,0.8722,0.872163
combo_wd_stronger,0.8659,0.8659,0.865939,0.8659,0.865748
combo_wider_channels,0.8619,0.8619,0.861402,0.8619,0.861191
augment_batchnorm,0.8548,0.8548,0.854965,0.8548,0.854783
augment_batchnorm_deeper,0.8548,0.8548,0.854965,0.8548,0.854783
augment_batchnorm_deeper_cosine,0.8548,0.8548,0.854965,0.8548,0.854783
combo_batch64,0.8534,0.8534,0.853683,0.8534,0.853082
combo_wider_fc,0.8527,0.8527,0.854537,0.8527,0.852820
combo_cosine_long,0.8522,0.8522,0.851832,0.8522,0.851625
combo_lr_high_cosine,0.8516,0.8516,0.851497,0.8516,0.851244
combo_strong_augment,0.8489,0.8489,0.848763,0.8489,0.848695
combo_kernel5,0.8467,0.8467,0.845554,0.8467,0.845617
combo_4conv,0.8460,0.8460,0.849063,0.8460,0.846866
combo_dropout_tiny,0.8351,0.8351,0.833900,0.8351,0.834027
combo_real_norm,0.8347,0.8347,0.836046,0.8347,0.833983
augment_deeper,0.8070,0.8070,0.808046,0.8070,0.805164
augment_more_epochs,0.7871,0.7871,0.786874,0.7871,0.786495
augment,0.7871,0.7871,0.786874,0.7871,0.786495
augment_dropout_light,0.7450,0.7450,0.742617,0.7450,0.740547
deeper_3conv,0.7394,0.7394,0.741505,0.7394,0.738148
batch_norm,0.7336,0.7336,0.734223,0.7336,0.732073
baseline,0.7148,0.7148,0.712927,0.7148,0.712281
lr_low,0.7141,0.7141,0.718704,0.7141,0.712868
dropout_03,0.7130,0.7130,0.709245,0.7130,0.709568
padding_0,0.7119,0.7119,0.716136,0.7119,0.711563
pool_4,0.7117,0.7117,0.722152,0.7117,0.714032
kernel_5,0.7035,0.7035,0.706637,0.7035,0.700650
stride_2_no_pool,0.6430,0.6430,0.656135,0.6430,0.644236
lr_high,0.6175,0.6175,0.629037,0.6175,0.620140

## 10. Leva 6 — mudança de arquitetura (estilo VGG + global average pooling)

Todas as levas até aqui variaram hiperparâmetros de **uma mesma família de
arquitetura**: 1 convolução por estágio de pooling (3 convs / 3 poolings) e
cabeça densa achatada. Essa família parece ter batido no teto por volta de
0.87-0.88. Para ir além, a leva 6 mexe na arquitetura em si, usando dois campos
novos do `ExperimentConfig`:

- **`conv_layers_per_block`** — nº de convoluções empilhadas por estágio antes
  do pooling. `2` = estilo VGG (6 convs / 3 poolings): dobra a profundidade
  efetiva sem comprimir mais o mapa espacial.
- **`global_pool`** — troca o achatamento denso por `AdaptiveAvgPool2d(1)` após
  os estágios conv. Corta a maior parte dos parâmetros da cabeça (forte
  regularização) e deixa a decisão depender das features conv, não de um MLP
  grande no fim.

Base herdada da leva 5: augment leve, batch_norm, cosine, `weight_decay=5e-4`.
Rodadas longas com `patience` alto — redes maiores convergem mais devagar.

In [17]:
round6_configs = [
    ExperimentConfig(
        run_name="vgg_2conv_per_block",
        conv_channels=(64, 128, 256), conv_layers_per_block=2,
        kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(256, 128), augment=True, batch_norm=True, lr_schedule="cosine",
        learning_rate=1e-3, weight_decay=5e-4, num_epochs=100, patience=20,
        notes="Estilo VGG: 2 convs por estagio de pooling (6 convs / 3 poolings em vez de 3/3). A familia shallow anterior batia no teto ~0.88 - mais profundidade real e a principal alavanca que faltava.",
    ),
    ExperimentConfig(
        run_name="vgg_2conv_gap",
        conv_channels=(64, 128, 256), conv_layers_per_block=2, global_pool=True,
        kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(128,), augment=True, batch_norm=True, lr_schedule="cosine",
        learning_rate=1e-3, weight_decay=5e-4, num_epochs=100, patience=20,
        notes="VGG-ish + global average pooling: cabeca densa vira so 256->128->10. Corta a maioria dos parametros (regularizacao forte), decisao passa a depender das features conv.",
    ),
    ExperimentConfig(
        run_name="vgg_2conv_sgd",
        conv_channels=(64, 128, 256), conv_layers_per_block=2,
        kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(256, 128), augment=True, batch_norm=True, lr_schedule="cosine",
        optimizer="sgd", learning_rate=0.05, momentum=0.9,
        weight_decay=5e-4, num_epochs=120, patience=25,
        notes="VGG-ish com a receita classica SGD+momentum+cosine - combinacao padrao pra passar de 0.90 no CIFAR com rede desse porte.",
    ),
    ExperimentConfig(
        run_name="vgg_4stage_gap_sgd",
        conv_channels=(64, 128, 256, 512), conv_layers_per_block=2, global_pool=True,
        kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(256,), augment=True, batch_norm=True, lr_schedule="cosine",
        optimizer="sgd", learning_rate=0.05, momentum=0.9,
        weight_decay=5e-4, num_epochs=120, patience=25,
        notes="4 estagios (64/128/256/512) x2 convs + GAP: 32->16->8->4->2, o mapa nao colapsa gracas ao global pool. Maior capacidade da fase, com SGD+cosine+wd pra segurar o overfit.",
    ),
    ExperimentConfig(
        run_name="vgg_2conv_sgd_strong_aug",
        conv_channels=(64, 128, 256), conv_layers_per_block=2,
        kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(256, 128), augment=True, augment_strength="strong",
        batch_norm=True, lr_schedule="cosine",
        optimizer="sgd", learning_rate=0.05, momentum=0.9,
        weight_decay=5e-4, num_epochs=120, patience=25,
        notes="VGG-ish + SGD + augment forte (color jitter). Na rede shallow o strong piorou (0.8489), mas rede maior aguenta - e costuma pedir - augment mais agressivo pra nao overfitar.",
    ),
    ExperimentConfig(
        run_name="vgg_2conv_dropout",
        conv_channels=(64, 128, 256), conv_layers_per_block=2,
        kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(256, 128), dropout=0.1, augment=True, batch_norm=True,
        lr_schedule="cosine", optimizer="sgd", learning_rate=0.05, momentum=0.9,
        weight_decay=5e-4, num_epochs=120, patience=25,
        notes="VGG-ish + dropout 0.1 (Dropout2d nos estagios conv + Dropout na cabeca). Dropout leve so faz sentido com uma rede grande o bastante pra overfitar - agora ela e.",
    ),
]

for config in round6_configs:
    if config.run_name in experiment_results:
        continue
    set_seed(config.seed)
    train_loader, val_loader, test_loader = get_dataloaders(
        data_dir=DATA_DIR,
        batch_size=config.batch_size,
        val_fraction=config.val_fraction,
        seed=config.seed,
        num_workers=NUM_WORKERS,
        augment=config.augment,
        normalization=config.normalization,
        augment_strength=config.augment_strength,
    )
    experiment_results[config.run_name] = fit_or_load(
        config, train_loader, val_loader, test_loader, device,
        class_names=list(CLASSES), results_dir=RESULTS_DIR,
    )

[fit_or_load] Reaproveitando execução existente de 'vgg_2conv_per_block' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_vgg_2conv_per_block_20260910-010900 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'vgg_2conv_gap' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_vgg_2conv_gap_20260910-013706 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'vgg_2conv_sgd' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_vgg_2conv_sgd_strong_aug_20260910-034136 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'vgg_4stage_gap_sgd' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_vgg_4stage_gap_sgd_20260910-025251 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'vgg_2conv_sgd_strong_aug' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_vgg_2conv_sgd_strong_aug_20260910-034136 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'vgg_2conv_dropout' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_vgg_2conv_dropout_20260910-041729 (não retreinado).

In [18]:
#@title Tabela comparativa - levas 1..6
comparison6 = pd.DataFrame(
    {name: r["test_scores"] for name, r in experiment_results.items()}
).T.sort_values("accuracy", ascending=False)
comparison6

,accuracy,balanced_accuracy,precision,recall,f1_score
vgg_4stage_gap_sgd,0.9370,0.9370,0.936852,0.9370,0.936859
vgg_2conv_dropout,0.9284,0.9284,0.928339,0.9284,0.928181
vgg_2conv_sgd_strong_aug,0.9222,0.9222,0.922122,0.9222,0.922028
vgg_2conv_sgd,0.9222,0.9222,0.922122,0.9222,0.922028
vgg_2conv_gap,0.9017,0.9017,0.901705,0.9017,0.901462
vgg_2conv_per_block,0.9007,0.9007,0.901603,0.9007,0.900811
combo_wd_wider_sgd_long,0.8891,0.8891,0.889251,0.8891,0.889094
combo_wd_wider,0.8891,0.8891,0.889251,0.8891,0.889094
combo_wd_long,0.8792,0.8792,0.878581,0.8792,0.878802
combo_wd_wider_fc,0.8776,0.8776,0.877375,0.8776,0.877360
combo_wd_gelu,0.8759,0.8759,0.875921,0.8759,0.875705
combo_wd_sgd,0.8756,0.8756,0.875207,0.8756,0.875211
combo_weight_decay_light,0.8722,0.8722,0.872201,0.8722,0.872163
combo_wd_stronger,0.8659,0.8659,0.865939,0.8659,0.865748
combo_wider_channels,0.8619,0.8619,0.861402,0.8619,0.861191
augment_batchnorm_deeper,0.8548,0.8548,0.854965,0.8548,0.854783
augment_batchnorm,0.8548,0.8548,0.854965,0.8548,0.854783
augment_batchnorm_deeper_cosine,0.8548,0.8548,0.854965,0.8548,0.854783
combo_batch64,0.8534,0.8534,0.853683,0.8534,0.853082
combo_wider_fc,0.8527,0.8527,0.854537,0.8527,0.852820
combo_cosine_long,0.8522,0.8522,0.851832,0.8522,0.851625
combo_lr_high_cosine,0.8516,0.8516,0.851497,0.8516,0.851244
combo_strong_augment,0.8489,0.8489,0.848763,0.8489,0.848695
combo_kernel5,0.8467,0.8467,0.845554,0.8467,0.845617
combo_4conv,0.8460,0.8460,0.849063,0.8460,0.846866
combo_dropout_tiny,0.8351,0.8351,0.833900,0.8351,0.834027
combo_real_norm,0.8347,0.8347,0.836046,0.8347,0.833983
augment_deeper,0.8070,0.8070,0.808046,0.8070,0.805164
augment,0.7871,0.7871,0.786874,0.7871,0.786495
augment_more_epochs,0.7871,0.7871,0.786874,0.7871,0.786495
augment_dropout_light,0.7450,0.7450,0.742617,0.7450,0.740547
deeper_3conv,0.7394,0.7394,0.741505,0.7394,0.738148
batch_norm,0.7336,0.7336,0.734223,0.7336,0.732073
baseline,0.7148,0.7148,0.712927,0.7148,0.712281
lr_low,0.7141,0.7141,0.718704,0.7141,0.712868
dropout_03,0.7130,0.7130,0.709245,0.7130,0.709568
padding_0,0.7119,0.7119,0.716136,0.7119,0.711563
pool_4,0.7117,0.7117,0.722152,0.7117,0.714032
kernel_5,0.7035,0.7035,0.706637,0.7035,0.700650
stride_2_no_pool,0.6430,0.6430,0.656135,0.6430,0.644236
lr_high,0.6175,0.6175,0.629037,0.6175,0.620140

## 11. O que as levas 5 e 6 mostraram

**Leva 5** (weight decay + canais largos, na família rasa): `combo_wd_wider_sgd_long`
= **0.8891** (SGD + 64/128/256 filtros + 120 épocas). Canais mais largos valem
~+0.7pp; `weight_decay=5e-4` é o ponto certo (`1.5e-3` foi longe demais, 0.8659).

**Leva 6** (arquitetura VGG-style — `conv_layers_per_block=2`): salto grande.
`vgg_4stage_gap_sgd` = **0.9370** (4 estágios 64/128/256/512, 2 conv/estágio,
global average pooling, SGD+cosine, 120 épocas). Três achados fortes:

1. **Profundidade real (2 convs por estágio de pooling) foi a maior alavanca
   isolada de toda a busca** — de ~0.889 para 0.90+ só com isso.
2. **SGD+momentum+cosine >> Adam para redes fundas: +3pp** (0.90 → 0.93).
   As duas versões Adam do VGG ficaram em ~0.90; as SGD, em ~0.93.
3. `+dropout 0.1` (0.9284) e `+color jitter` (0.9222) **pioraram** — mas isso
   foi na rede de 3 estágios.

**Diagnóstico do campeão (`vgg_4stage_gap_sgd`):** a curva mostra
`train_loss` ~0.006 (decora o treino) com `val_loss` travado em ~0.23 e
`val_accuracy` estagnada em 0.94-0.945 nas últimas ~15 épocas. O gargalo
mudou: **não é mais capacidade nem tempo de treino, é a diferença
treino-validação (generalização).** A leva 7 ataca exatamente isso —
regularização e augmentation mais forte, mantendo a arquitetura e o
otimizador vencedores.

In [19]:
# Leva 7 - base = campeao da leva 6 (vgg_4stage_gap_sgd, 0.9370):
#   conv_channels=(64,128,256,512), conv_layers_per_block=2, global_pool=True,
#   fc_layers=(256,), augment light, batch_norm, cosine, optimizer=sgd,
#   learning_rate=0.05, momentum=0.9, weight_decay=5e-4, num_epochs=120, patience=25
#
# Usa 3 campos novos do ExperimentConfig (ver src/cnn_cifar10/):
#   label_smoothing (CrossEntropyLoss), nesterov (SGD),
#   augment_strength="trivial"/"randaugment" (TrivialAugmentWide / RandAugment)

_CHAMP = dict(
    conv_channels=(64, 128, 256, 512), conv_layers_per_block=2, global_pool=True,
    kernel_size=3, stride=1, padding=1, pool_size=2, fc_layers=(256,),
    augment=True, batch_norm=True, lr_schedule="cosine",
    optimizer="sgd", learning_rate=0.05, momentum=0.9, weight_decay=5e-4,
    num_epochs=120, patience=25,
)

round7_configs = [
    ExperimentConfig(run_name="vgg4_label_smooth", **{**_CHAMP, "label_smoothing": 0.1},
        notes="Campeao da leva 6 + label smoothing 0.1. Ataca a superconfianca (train_loss->0); ganho classico e confiavel no CIFAR."),
    ExperimentConfig(run_name="vgg4_trivial_aug", **{**_CHAMP, "augment_strength": "trivial"},
        notes="Campeao + TrivialAugmentWide (augmentation automatica forte, sem hiperparametro). Redes que overfittam costumam pedir augmentation mais agressiva."),
    ExperimentConfig(run_name="vgg4_randaugment", **{**_CHAMP, "augment_strength": "randaugment"},
        notes="Campeao + RandAugment. Alternativa ao TrivialAugment - comparar qual regulariza melhor sem cortar sinal demais."),
    ExperimentConfig(run_name="vgg4_dropout", **{**_CHAMP, "dropout": 0.1},
        notes="Campeao + dropout 0.1. Na leva 6 dropout piorou, mas foi na rede de 3 estagios que overfittava menos - reteste na rede grande que decora o treino."),
    ExperimentConfig(run_name="vgg4_wd_higher", **{**_CHAMP, "weight_decay": 1e-3},
        notes="Campeao + L2 2x (5e-4 -> 1e-3). Na familia rasa 1.5e-3 exagerou, mas a rede grande tem mais parametros para segurar."),
    ExperimentConfig(run_name="vgg4_reg_combo", **{**_CHAMP, "label_smoothing": 0.1, "augment_strength": "trivial", "nesterov": True},
        notes="Combo guloso das apostas de baixo risco: label smoothing + TrivialAugment + Nesterov, tudo junto sobre o campeao."),
]

for config in round7_configs:
    if config.run_name in experiment_results:
        continue
    set_seed(config.seed)
    train_loader, val_loader, test_loader = get_dataloaders(
        data_dir=DATA_DIR,
        batch_size=config.batch_size,
        val_fraction=config.val_fraction,
        seed=config.seed,
        num_workers=NUM_WORKERS,
        augment=config.augment,
        normalization=config.normalization,
        augment_strength=config.augment_strength,
    )
    experiment_results[config.run_name] = fit_or_load(
        config, train_loader, val_loader, test_loader, device,
        class_names=list(CLASSES), results_dir=RESULTS_DIR,
    )

[fit_or_load] Reaproveitando execução existente de 'vgg4_label_smooth' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_vgg4_label_smooth_20260910-123901 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'vgg4_trivial_aug' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_vgg4_trivial_aug_20260910-132352 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'vgg4_randaugment' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_vgg4_randaugment_20260910-141339 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'vgg4_dropout' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_vgg4_dropout_20260910-145432 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'vgg4_wd_higher' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_vgg4_wd_higher_20260910-153429 (não retreinado).
[fit_or_load] Reaproveitando execução existente de 'vgg4_reg_combo' em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_vgg4_reg_combo_20260910-162024 (não retreinado).

In [20]:
#@title Tabela comparativa - levas 1..7
comparison7 = pd.DataFrame(
    {name: r["test_scores"] for name, r in experiment_results.items()}
).T.sort_values("accuracy", ascending=False)
comparison7

,accuracy,balanced_accuracy,precision,recall,f1_score
vgg4_randaugment,0.9417,0.9417,0.941777,0.9417,0.941689
vgg4_trivial_aug,0.9411,0.9411,0.941231,0.9411,0.941136
vgg4_reg_combo,0.9407,0.9407,0.940634,0.9407,0.940574
vgg4_label_smooth,0.9389,0.9389,0.938920,0.9389,0.938875
vgg_4stage_gap_sgd,0.9370,0.9370,0.936852,0.9370,0.936859
vgg4_wd_higher,0.9370,0.9370,0.937198,0.9370,0.937010
vgg4_dropout,0.9370,0.9370,0.936831,0.9370,0.936809
vgg_2conv_dropout,0.9284,0.9284,0.928339,0.9284,0.928181
vgg_2conv_sgd_strong_aug,0.9222,0.9222,0.922122,0.9222,0.922028
vgg_2conv_sgd,0.9222,0.9222,0.922122,0.9222,0.922028
vgg_2conv_gap,0.9017,0.9017,0.901705,0.9017,0.901462
vgg_2conv_per_block,0.9007,0.9007,0.901603,0.9007,0.900811
combo_wd_wider,0.8891,0.8891,0.889251,0.8891,0.889094
combo_wd_wider_sgd_long,0.8891,0.8891,0.889251,0.8891,0.889094
combo_wd_long,0.8792,0.8792,0.878581,0.8792,0.878802
combo_wd_wider_fc,0.8776,0.8776,0.877375,0.8776,0.877360
combo_wd_gelu,0.8759,0.8759,0.875921,0.8759,0.875705
combo_wd_sgd,0.8756,0.8756,0.875207,0.8756,0.875211
combo_weight_decay_light,0.8722,0.8722,0.872201,0.8722,0.872163
combo_wd_stronger,0.8659,0.8659,0.865939,0.8659,0.865748
combo_wider_channels,0.8619,0.8619,0.861402,0.8619,0.861191
augment_batchnorm_deeper,0.8548,0.8548,0.854965,0.8548,0.854783
augment_batchnorm_deeper_cosine,0.8548,0.8548,0.854965,0.8548,0.854783
augment_batchnorm,0.8548,0.8548,0.854965,0.8548,0.854783
combo_batch64,0.8534,0.8534,0.853683,0.8534,0.853082
combo_wider_fc,0.8527,0.8527,0.854537,0.8527,0.852820
combo_cosine_long,0.8522,0.8522,0.851832,0.8522,0.851625
combo_lr_high_cosine,0.8516,0.8516,0.851497,0.8516,0.851244
combo_strong_augment,0.8489,0.8489,0.848763,0.8489,0.848695
combo_kernel5,0.8467,0.8467,0.845554,0.8467,0.845617
combo_4conv,0.8460,0.8460,0.849063,0.8460,0.846866
combo_dropout_tiny,0.8351,0.8351,0.833900,0.8351,0.834027
combo_real_norm,0.8347,0.8347,0.836046,0.8347,0.833983
augment_deeper,0.8070,0.8070,0.808046,0.8070,0.805164
augment,0.7871,0.7871,0.786874,0.7871,0.786495
augment_more_epochs,0.7871,0.7871,0.786874,0.7871,0.786495
augment_dropout_light,0.7450,0.7450,0.742617,0.7450,0.740547
deeper_3conv,0.7394,0.7394,0.741505,0.7394,0.738148
batch_norm,0.7336,0.7336,0.734223,0.7336,0.732073
baseline,0.7148,0.7148,0.712927,0.7148,0.712281
lr_low,0.7141,0.7141,0.718704,0.7141,0.712868
dropout_03,0.7130,0.7130,0.709245,0.7130,0.709568
padding_0,0.7119,0.7119,0.716136,0.7119,0.711563
pool_4,0.7117,0.7117,0.722152,0.7117,0.714032
kernel_5,0.7035,0.7035,0.706637,0.7035,0.700650
stride_2_no_pool,0.6430,0.6430,0.656135,0.6430,0.644236
lr_high,0.6175,0.6175,0.629037,0.6175,0.620140

## 12. O que a leva 7 mostrou — o platô de 0.94

| Config | Acurácia | vs. campeão da leva 6 |
|---|---|---|
| `vgg4_randaugment` | **0.9417** | +0.47pp |
| `vgg4_trivial_aug` | 0.9411 | +0.41pp |
| `vgg4_reg_combo` | 0.9407 | +0.37pp |
| `vgg4_label_smooth` | 0.9389 | +0.19pp |
| `vgg4_dropout` | 0.9370 | 0.00pp |
| `vgg4_wd_higher` | 0.9370 | 0.00pp |

**Leitura honesta: a leva 7 não produziu um vencedor claro.** Os seis
resultados cabem numa faixa de 0.47pp, e a acurácia de validação das últimas
épocas fica em 0.940-0.946 em *todos* eles. Numa amostra de teste de 10.000
imagens, o erro padrão de uma acurácia de ~0.94 é ~0.24pp, ou seja, a
diferença entre o "melhor" e o "pior" da leva está a ~2 desvios — perto do
ruído. Trocar o regularizador não move mais a agulha.

O que a leva 7 *sim* confirmou: augmentation forte (`randaugment`,
`trivial`) é levemente melhor que regularização por peso/dropout, e o
label smoothing deixa a rede bem menos superconfiante (`train_loss` 0.506
contra 0.006 do campeão) **sem** ganhar acurácia proporcional — o problema
não era só calibração.

### Onde o erro realmente está

Acurácia por classe do melhor modelo (`vgg4_randaugment`):

| Grupo | Classes | Acurácia média |
|---|---|---|
| Veículos | airplane, automobile, ship, truck | **0.964** |
| Animais | bird, cat, deer, dog, frog, horse | **0.918** |

E dentro dos animais: `cat` 0.854, `dog` 0.909, `bird` 0.927. **Gato e
cachorro sozinhos respondem por ~24% de todos os erros do modelo.** Esse
padrão se repete em todos os sete modelos VGG treinados.

Isso define as três frentes das próximas seções, em ordem de custo:

1. **Leva 8 — MixUp/CutMix** (seção 13): o único regularizador forte ainda
   não testado, e o que ataca justamente pares de classes confundíveis.
2. **Ensemble** (seção 14): custo zero de treino, só um forward a mais.
   Os sete modelos erram imagens diferentes; a média deve capturar isso.
3. **Hierárquico** (seção 15): porteiro veículo/animal + dois especialistas,
   motivado diretamente pela tabela acima.

## 13. Leva 8 — MixUp e CutMix

`MixUp` interpola duas imagens pixel a pixel (e seus rótulos na mesma
proporção); `CutMix` cola um recorte retangular de uma imagem sobre a outra,
com o rótulo ponderado pela área. Os dois forçam a rede a produzir
probabilidades intermediárias em vez de decorar exemplos, e são conhecidos
por ajudar exatamente onde o CIFAR-10 dói (pares visualmente próximos como
gato/cachorro).

Duas diferenças importantes em relação às levas anteriores:

- **Mais épocas (200 em vez de 120).** Com mistura, o modelo converge mais
  devagar — rodar 120 épocas subestimaria o método.
- **`patience` alta (40).** A perda de validação com mistura é mais ruidosa;
  early stopping agressivo cortaria o treino cedo demais.

Isso torna esta leva a mais cara do projeto (~2x o custo de uma leva normal
por config), então são só 4 configs em vez de 6.

In [21]:
# Leva 8 - base = mesmo _CHAMP das levas 6/7, agora com mistura de amostras.
# Usa 3 campos novos do ExperimentConfig: mixup_alpha, cutmix_alpha, mix_prob
# (implementados em train.apply_mix; 0.0 desliga e o loop degenera no treino normal).

_CHAMP_LONG = {**_CHAMP, "num_epochs": 200, "patience": 40}

round8_configs = [
    ExperimentConfig(run_name="vgg4_mixup", **{**_CHAMP_LONG, "mixup_alpha": 0.2, "mix_prob": 0.5},
        notes="Campeao + MixUp alpha=0.2 em 50% dos batches. Alpha baixo = mistura suave, o default mais seguro para CIFAR."),
    ExperimentConfig(run_name="vgg4_cutmix", **{**_CHAMP_LONG, "cutmix_alpha": 1.0, "mix_prob": 0.5},
        notes="Campeao + CutMix alpha=1.0. Recorte espacial em vez de interpolacao - preserva texturas locais, costuma bater o MixUp em imagens pequenas."),
    ExperimentConfig(run_name="vgg4_mixcut_both", **{**_CHAMP_LONG, "mixup_alpha": 0.2, "cutmix_alpha": 1.0, "mix_prob": 0.5},
        notes="Alterna MixUp e CutMix por batch (receita padrao de treinos modernos de CIFAR/ImageNet)."),
    ExperimentConfig(run_name="vgg4_mixcut_aug_ls", **{**_CHAMP_LONG, "mixup_alpha": 0.2, "cutmix_alpha": 1.0,
                                                       "mix_prob": 0.5, "augment_strength": "randaugment", "label_smoothing": 0.1, "nesterov": True},
        notes="Combo maximo: mistura + RandAugment (melhor da leva 7) + label smoothing + Nesterov. Se o teto de 0.94 for de regularizacao, este quebra."),
]

for config in round8_configs:
    if config.run_name in experiment_results:
        continue
    set_seed(config.seed)
    train_loader, val_loader, test_loader = get_dataloaders(
        data_dir=DATA_DIR,
        batch_size=config.batch_size,
        val_fraction=config.val_fraction,
        seed=config.seed,
        num_workers=NUM_WORKERS,
        augment=config.augment,
        normalization=config.normalization,
        augment_strength=config.augment_strength,
    )
    experiment_results[config.run_name] = fit_or_load(
        config, train_loader, val_loader, test_loader, device,
        class_names=list(CLASSES), results_dir=RESULTS_DIR,
    )

treinando 'vgg4_mixup':   0%|          | 0/200 [00:00<?, ?it/s]

Época 1/200 | train_loss=1.9195 | val_loss=1.5971 | val_acc=0.4006
Época 2/200 | train_loss=1.5712 | val_loss=1.3160 | val_acc=0.5294
Época 3/200 | train_loss=1.2397 | val_loss=1.2132 | val_acc=0.5892
Época 4/200 | train_loss=1.0895 | val_loss=0.9554 | val_acc=0.6826
Época 5/200 | train_loss=0.9851 | val_loss=0.8314 | val_acc=0.7182
Época 6/200 | train_loss=0.9583 | val_loss=0.8652 | val_acc=0.7082
Época 7/200 | train_loss=0.9037 | val_loss=0.8725 | val_acc=0.7106
Época 8/200 | train_loss=0.8956 | val_loss=0.7441 | val_acc=0.7532
Época 9/200 | train_loss=0.8897 | val_loss=0.7142 | val_acc=0.7610
Época 10/200 | train_loss=0.8551 | val_loss=0.8194 | val_acc=0.7292
Época 11/200 | train_loss=0.8338 | val_loss=0.8071 | val_acc=0.7204
Época 12/200 | train_loss=0.8061 | val_loss=0.7026 | val_acc=0.7668
Época 13/200 | train_loss=0.7959 | val_loss=0.6392 | val_acc=0.7832
Época 14/200 | train_loss=0.8062 | val_loss=0.6934 | val_acc=0.7794
Época 15/200 | train_loss=0.7903 | val_loss=0.6877 | val_acc=0.7774
Época 16/200 | train_loss=0.7836 | val_loss=0.6501 | val_acc=0.7932
Época 17/200 | train_loss=0.7983 | val_loss=0.7112 | val_acc=0.7558
Época 18/200 | train_loss=0.7985 | val_loss=0.6096 | val_acc=0.8030
Época 19/200 | train_loss=0.7993 | val_loss=0.6751 | val_acc=0.7784
Época 20/200 | train_loss=0.7809 | val_loss=0.7737 | val_acc=0.7452
Época 21/200 | train_loss=0.7754 | val_loss=0.7011 | val_acc=0.7702
Época 22/200 | train_loss=0.7691 | val_loss=0.5720 | val_acc=0.8234
Época 23/200 | train_loss=0.7495 | val_loss=0.5958 | val_acc=0.8096
Época 24/200 | train_loss=0.7595 | val_loss=0.6486 | val_acc=0.7936
Época 25/200 | train_loss=0.7531 | val_loss=0.5586 | val_acc=0.8198
Época 26/200 | train_loss=0.7492 | val_loss=0.6528 | val_acc=0.7930
Época 27/200 | train_loss=0.7511 | val_loss=0.5682 | val_acc=0.8082
Época 28/200 | train_loss=0.7523 | val_loss=0.6421 | val_acc=0.7850
Época 29/200 | train_loss=0.7482 | val_loss=0.8745 | val_acc=0.7260
Época 30/200 | train_loss=0.7592 | val_loss=0.6210 | val_acc=0.8012
Época 31/200 | train_loss=0.7311 | val_loss=0.6947 | val_acc=0.7676
Época 32/200 | train_loss=0.7347 | val_loss=0.7944 | val_acc=0.7372
Época 33/200 | train_loss=0.7486 | val_loss=0.7223 | val_acc=0.7668
Época 34/200 | train_loss=0.7289 | val_loss=0.5196 | val_acc=0.8248
Época 35/200 | train_loss=0.7437 | val_loss=0.5889 | val_acc=0.8034
Época 36/200 | train_loss=0.7308 | val_loss=0.6032 | val_acc=0.7978
Época 37/200 | train_loss=0.7236 | val_loss=0.5258 | val_acc=0.8232
Época 38/200 | train_loss=0.7140 | val_loss=0.5969 | val_acc=0.8070
Época 39/200 | train_loss=0.7242 | val_loss=0.7226 | val_acc=0.7640
Época 40/200 | train_loss=0.7332 | val_loss=0.6813 | val_acc=0.7644
Época 41/200 | train_loss=0.7188 | val_loss=0.7024 | val_acc=0.7770
Época 42/200 | train_loss=0.7049 | val_loss=0.7027 | val_acc=0.7682
Época 43/200 | train_loss=0.7118 | val_loss=0.5413 | val_acc=0.8168
Época 44/200 | train_loss=0.6966 | val_loss=0.7592 | val_acc=0.7458
Época 45/200 | train_loss=0.7134 | val_loss=0.5908 | val_acc=0.7944
Época 46/200 | train_loss=0.7269 | val_loss=0.6517 | val_acc=0.8182
Época 47/200 | train_loss=0.7097 | val_loss=0.6834 | val_acc=0.7774
Época 48/200 | train_loss=0.7015 | val_loss=0.4940 | val_acc=0.8340
Época 49/200 | train_loss=0.6979 | val_loss=0.5770 | val_acc=0.8090
Época 50/200 | train_loss=0.7042 | val_loss=0.7461 | val_acc=0.7486
Época 51/200 | train_loss=0.7188 | val_loss=0.5363 | val_acc=0.8246
Época 52/200 | train_loss=0.7071 | val_loss=0.6307 | val_acc=0.7960
Época 53/200 | train_loss=0.7090 | val_loss=0.5120 | val_acc=0.8394
Época 54/200 | train_loss=0.6975 | val_loss=0.6571 | val_acc=0.7814
Época 55/200 | train_loss=0.6807 | val_loss=0.5442 | val_acc=0.8168
Época 56/200 | train_loss=0.6981 | val_loss=0.6250 | val_acc=0.8006
Época 57/200 | train_loss=0.7004 | val_loss=0.5419 | val_acc=0.8234
Época 58/200 | train_loss=0.6789 | val_loss=0.5609 | val_acc=0.8168
Época 59/200 | train_loss=0.7057 | val_loss=0.5729 | val_acc=0.8182
Época 60/200 | train_loss=0.6889 | val_loss=0.5795 | val_acc=0.8156
Época 61/200 | train_loss=0.6811 | val_loss=0.5014 | val_acc=0.8398
Época 62/200 | train_loss=0.6762 | val_loss=0.5401 | val_acc=0.8306
Época 63/200 | train_loss=0.6641 | val_loss=0.6688 | val_acc=0.7774
Época 64/200 | train_loss=0.6715 | val_loss=0.7475 | val_acc=0.7572
Época 65/200 | train_loss=0.6447 | val_loss=0.6226 | val_acc=0.8000
Época 66/200 | train_loss=0.6511 | val_loss=0.6317 | val_acc=0.7996
Época 67/200 | train_loss=0.6421 | val_loss=0.5346 | val_acc=0.8316
Época 68/200 | train_loss=0.6306 | val_loss=0.4719 | val_acc=0.8488
Época 69/200 | train_loss=0.6414 | val_loss=0.5298 | val_acc=0.8216
Época 70/200 | train_loss=0.6438 | val_loss=0.5759 | val_acc=0.8136
Época 71/200 | train_loss=0.6523 | val_loss=0.4704 | val_acc=0.8480
Época 72/200 | train_loss=0.6492 | val_loss=0.5012 | val_acc=0.8286
Época 73/200 | train_loss=0.6411 | val_loss=0.5007 | val_acc=0.8376
Época 74/200 | train_loss=0.6365 | val_loss=0.5167 | val_acc=0.8370
Época 75/200 | train_loss=0.6112 | val_loss=0.5058 | val_acc=0.8276
Época 76/200 | train_loss=0.6211 | val_loss=0.5577 | val_acc=0.8110
Época 77/200 | train_loss=0.6225 | val_loss=0.4684 | val_acc=0.8422
Época 78/200 | train_loss=0.6185 | val_loss=0.5475 | val_acc=0.8152
Época 79/200 | train_loss=0.6238 | val_loss=0.5263 | val_acc=0.8370
Época 80/200 | train_loss=0.6150 | val_loss=0.5497 | val_acc=0.8264
Época 81/200 | train_loss=0.6149 | val_loss=0.4499 | val_acc=0.8510
Época 82/200 | train_loss=0.6140 | val_loss=0.4965 | val_acc=0.8288
Época 83/200 | train_loss=0.6038 | val_loss=0.4498 | val_acc=0.8454
Época 84/200 | train_loss=0.5959 | val_loss=0.5302 | val_acc=0.8354
Época 85/200 | train_loss=0.5796 | val_loss=0.5178 | val_acc=0.8268
Época 86/200 | train_loss=0.6045 | val_loss=0.5380 | val_acc=0.8236
Época 87/200 | train_loss=0.6021 | val_loss=0.4551 | val_acc=0.8512
Época 88/200 | train_loss=0.5886 | val_loss=0.4571 | val_acc=0.8484
Época 89/200 | train_loss=0.5845 | val_loss=0.5633 | val_acc=0.8186
Época 90/200 | train_loss=0.6034 | val_loss=0.4815 | val_acc=0.8406
Época 91/200 | train_loss=0.5699 | val_loss=0.5049 | val_acc=0.8354
Época 92/200 | train_loss=0.5775 | val_loss=0.5563 | val_acc=0.8162
Época 93/200 | train_loss=0.5793 | val_loss=0.4309 | val_acc=0.8554
Época 94/200 | train_loss=0.5817 | val_loss=0.4678 | val_acc=0.8424
Época 95/200 | train_loss=0.5677 | val_loss=0.4296 | val_acc=0.8536
Época 96/200 | train_loss=0.5528 | val_loss=0.4453 | val_acc=0.8526
Época 97/200 | train_loss=0.5619 | val_loss=0.6561 | val_acc=0.7938
Época 98/200 | train_loss=0.5665 | val_loss=0.4537 | val_acc=0.8552
Época 99/200 | train_loss=0.5583 | val_loss=0.4497 | val_acc=0.8536
Época 100/200 | train_loss=0.5415 | val_loss=0.4242 | val_acc=0.8616
Época 101/200 | train_loss=0.5622 | val_loss=0.4560 | val_acc=0.8534
Época 102/200 | train_loss=0.5355 | val_loss=0.4480 | val_acc=0.8496
Época 103/200 | train_loss=0.5477 | val_loss=0.4217 | val_acc=0.8586
Época 104/200 | train_loss=0.5410 | val_loss=0.4943 | val_acc=0.8438
Época 105/200 | train_loss=0.5344 | val_loss=0.3891 | val_acc=0.8674
Época 106/200 | train_loss=0.5448 | val_loss=0.4270 | val_acc=0.8482
Época 107/200 | train_loss=0.5474 | val_loss=0.4434 | val_acc=0.8530
Época 108/200 | train_loss=0.5218 | val_loss=0.3930 | val_acc=0.8710
Época 109/200 | train_loss=0.5135 | val_loss=0.4249 | val_acc=0.8596
Época 110/200 | train_loss=0.5058 | val_loss=0.4932 | val_acc=0.8450
Época 111/200 | train_loss=0.5351 | val_loss=0.3593 | val_acc=0.8842
Época 112/200 | train_loss=0.5058 | val_loss=0.4041 | val_acc=0.8680
Época 113/200 | train_loss=0.4968 | val_loss=0.4495 | val_acc=0.8508
Época 114/200 | train_loss=0.5205 | val_loss=0.4240 | val_acc=0.8622
Época 115/200 | train_loss=0.4977 | val_loss=0.4041 | val_acc=0.8740
Época 116/200 | train_loss=0.5068 | val_loss=0.3851 | val_acc=0.8744
Época 117/200 | train_loss=0.5070 | val_loss=0.3561 | val_acc=0.8850
Época 118/200 | train_loss=0.4753 | val_loss=0.3978 | val_acc=0.8676
Época 119/200 | train_loss=0.4717 | val_loss=0.3759 | val_acc=0.8766
Época 120/200 | train_loss=0.4801 | val_loss=0.3573 | val_acc=0.8858
Época 121/200 | train_loss=0.4611 | val_loss=0.4588 | val_acc=0.8484
Época 122/200 | train_loss=0.4800 | val_loss=0.4269 | val_acc=0.8616
Época 123/200 | train_loss=0.4747 | val_loss=0.4287 | val_acc=0.8602
Época 124/200 | train_loss=0.4561 | val_loss=0.3365 | val_acc=0.8836
Época 125/200 | train_loss=0.4738 | val_loss=0.3497 | val_acc=0.8846
Época 126/200 | train_loss=0.4357 | val_loss=0.4769 | val_acc=0.8454
Época 127/200 | train_loss=0.4597 | val_loss=0.3572 | val_acc=0.8816
Época 128/200 | train_loss=0.4582 | val_loss=0.3961 | val_acc=0.8766
Época 129/200 | train_loss=0.4383 | val_loss=0.3900 | val_acc=0.8714
Época 130/200 | train_loss=0.4316 | val_loss=0.3785 | val_acc=0.8812
Época 131/200 | train_loss=0.4395 | val_loss=0.3502 | val_acc=0.8872
Época 132/200 | train_loss=0.4477 | val_loss=0.3375 | val_acc=0.8900
Época 133/200 | train_loss=0.4213 | val_loss=0.3663 | val_acc=0.8858
Época 134/200 | train_loss=0.4267 | val_loss=0.4064 | val_acc=0.8660
Época 135/200 | train_loss=0.4068 | val_loss=0.3248 | val_acc=0.8880
Época 136/200 | train_loss=0.4161 | val_loss=0.3554 | val_acc=0.8850
Época 137/200 | train_loss=0.4188 | val_loss=0.2882 | val_acc=0.9054
Época 138/200 | train_loss=0.3968 | val_loss=0.3575 | val_acc=0.8832
Época 139/200 | train_loss=0.3985 | val_loss=0.3273 | val_acc=0.8918
Época 140/200 | train_loss=0.4125 | val_loss=0.3565 | val_acc=0.8858
Época 141/200 | train_loss=0.3949 | val_loss=0.3872 | val_acc=0.8808
Época 142/200 | train_loss=0.3968 | val_loss=0.3057 | val_acc=0.9020
Época 143/200 | train_loss=0.3953 | val_loss=0.2938 | val_acc=0.9078
Época 144/200 | train_loss=0.3745 | val_loss=0.3052 | val_acc=0.9008
Época 145/200 | train_loss=0.3788 | val_loss=0.3392 | val_acc=0.8894
Época 146/200 | train_loss=0.3839 | val_loss=0.3228 | val_acc=0.9036
Época 147/200 | train_loss=0.3514 | val_loss=0.3594 | val_acc=0.8890
Época 148/200 | train_loss=0.3597 | val_loss=0.2932 | val_acc=0.9070
Época 149/200 | train_loss=0.3683 | val_loss=0.3047 | val_acc=0.8980
Época 150/200 | train_loss=0.3593 | val_loss=0.2960 | val_acc=0.9020
Época 151/200 | train_loss=0.3410 | val_loss=0.3037 | val_acc=0.9054
Época 152/200 | train_loss=0.3265 | val_loss=0.2821 | val_acc=0.9138
Época 153/200 | train_loss=0.3435 | val_loss=0.2573 | val_acc=0.9148
Época 154/200 | train_loss=0.3244 | val_loss=0.2713 | val_acc=0.9154
Época 155/200 | train_loss=0.3153 | val_loss=0.3449 | val_acc=0.8962
Época 156/200 | train_loss=0.3068 | val_loss=0.2653 | val_acc=0.9178
Época 157/200 | train_loss=0.3298 | val_loss=0.3155 | val_acc=0.9016
Época 158/200 | train_loss=0.3147 | val_loss=0.2833 | val_acc=0.9116
Época 159/200 | train_loss=0.2918 | val_loss=0.2769 | val_acc=0.9180
Época 160/200 | train_loss=0.2904 | val_loss=0.2626 | val_acc=0.9198
Época 161/200 | train_loss=0.3049 | val_loss=0.2322 | val_acc=0.9244
Época 162/200 | train_loss=0.2938 | val_loss=0.2674 | val_acc=0.9208
Época 163/200 | train_loss=0.2784 | val_loss=0.2504 | val_acc=0.9260
Época 164/200 | train_loss=0.2766 | val_loss=0.2225 | val_acc=0.9294
Época 165/200 | train_loss=0.2798 | val_loss=0.2509 | val_acc=0.9270
Época 166/200 | train_loss=0.2699 | val_loss=0.2351 | val_acc=0.9276
Época 167/200 | train_loss=0.2576 | val_loss=0.2496 | val_acc=0.9172
Época 168/200 | train_loss=0.2505 | val_loss=0.2324 | val_acc=0.9266
Época 169/200 | train_loss=0.2462 | val_loss=0.2216 | val_acc=0.9330
Época 170/200 | train_loss=0.2360 | val_loss=0.2141 | val_acc=0.9360
Época 171/200 | train_loss=0.2496 | val_loss=0.2350 | val_acc=0.9354
Época 172/200 | train_loss=0.2420 | val_loss=0.2179 | val_acc=0.9320
Época 173/200 | train_loss=0.2329 | val_loss=0.2209 | val_acc=0.9370
Época 174/200 | train_loss=0.2353 | val_loss=0.2100 | val_acc=0.9386
Época 175/200 | train_loss=0.2373 | val_loss=0.1937 | val_acc=0.9420
Época 176/200 | train_loss=0.2230 | val_loss=0.2017 | val_acc=0.9450
Época 177/200 | train_loss=0.2406 | val_loss=0.1913 | val_acc=0.9440
Época 178/200 | train_loss=0.2456 | val_loss=0.2057 | val_acc=0.9428
Época 179/200 | train_loss=0.2092 | val_loss=0.1828 | val_acc=0.9440
Época 180/200 | train_loss=0.2191 | val_loss=0.1857 | val_acc=0.9458
Época 181/200 | train_loss=0.1981 | val_loss=0.1982 | val_acc=0.9472
Época 182/200 | train_loss=0.2086 | val_loss=0.1980 | val_acc=0.9430
Época 183/200 | train_loss=0.2182 | val_loss=0.1948 | val_acc=0.9480
Época 184/200 | train_loss=0.1909 | val_loss=0.2042 | val_acc=0.9478
Época 185/200 | train_loss=0.2247 | val_loss=0.1852 | val_acc=0.9458
Época 186/200 | train_loss=0.2278 | val_loss=0.2214 | val_acc=0.9462
Época 187/200 | train_loss=0.2244 | val_loss=0.1773 | val_acc=0.9476
Época 188/200 | train_loss=0.2103 | val_loss=0.1788 | val_acc=0.9466
Época 189/200 | train_loss=0.2187 | val_loss=0.1804 | val_acc=0.9486
Época 190/200 | train_loss=0.2078 | val_loss=0.1740 | val_acc=0.9494
Época 191/200 | train_loss=0.2125 | val_loss=0.1828 | val_acc=0.9504
Época 192/200 | train_loss=0.2170 | val_loss=0.1791 | val_acc=0.9506
Época 193/200 | train_loss=0.2212 | val_loss=0.1847 | val_acc=0.9484
Época 194/200 | train_loss=0.2096 | val_loss=0.1747 | val_acc=0.9480
Época 195/200 | train_loss=0.2060 | val_loss=0.1698 | val_acc=0.9486
Época 196/200 | train_loss=0.2063 | val_loss=0.1814 | val_acc=0.9488
Época 197/200 | train_loss=0.2158 | val_loss=0.1685 | val_acc=0.9498
Época 198/200 | train_loss=0.2363 | val_loss=0.1849 | val_acc=0.9492
Época 199/200 | train_loss=0.2175 | val_loss=0.1687 | val_acc=0.9506
Época 200/200 | train_loss=0.2243 | val_loss=0.1844 | val_acc=0.9494
Métricas no conjunto de teste: {'accuracy': 0.9443, 'balanced_accuracy': np.float64(0.9442999999999999), 'precision': 0.9443407395751936, 'recall': 0.9443, 'f1_score': 0.9442929764698752}
Acurácia por classe: {'airplane': 0.945, 'automobile': 0.973, 'bird': 0.926, 'cat': 0.881, 'deer': 0.957, 'dog': 0.899, 'frog': 0.969, 'horse': 0.962, 'ship': 0.969, 'truck': 0.962}
[model-saver] Modelo salvo em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_vgg4_mixup_20260910-191632/

treinando 'vgg4_cutmix':   0%|          | 0/200 [00:00<?, ?it/s]

Época 1/200 | train_loss=2.0317 | val_loss=1.7256 | val_acc=0.3342
Época 2/200 | train_loss=1.7425 | val_loss=1.3703 | val_acc=0.4860
Época 3/200 | train_loss=1.5002 | val_loss=1.5546 | val_acc=0.4864
Época 4/200 | train_loss=1.3865 | val_loss=0.8862 | val_acc=0.7092
Época 5/200 | train_loss=1.2894 | val_loss=0.9426 | val_acc=0.6754
Época 6/200 | train_loss=1.2592 | val_loss=1.0006 | val_acc=0.6560
Época 7/200 | train_loss=1.2060 | val_loss=0.7419 | val_acc=0.7464
Época 8/200 | train_loss=1.1804 | val_loss=0.7198 | val_acc=0.7576
Época 9/200 | train_loss=1.1446 | val_loss=0.9510 | val_acc=0.6978
Época 10/200 | train_loss=1.1332 | val_loss=0.9354 | val_acc=0.7110
Época 11/200 | train_loss=1.1312 | val_loss=0.9534 | val_acc=0.6792
Época 12/200 | train_loss=1.1186 | val_loss=0.9126 | val_acc=0.7032
Época 13/200 | train_loss=1.0978 | val_loss=1.0289 | val_acc=0.6658
Época 14/200 | train_loss=1.0960 | val_loss=0.6822 | val_acc=0.7868
Época 15/200 | train_loss=1.0899 | val_loss=0.8344 | val_acc=0.7402
Época 16/200 | train_loss=1.0737 | val_loss=0.8172 | val_acc=0.7372
Época 17/200 | train_loss=1.0848 | val_loss=0.7325 | val_acc=0.7608
Época 18/200 | train_loss=1.0675 | val_loss=0.7004 | val_acc=0.7548
Época 19/200 | train_loss=1.0832 | val_loss=0.6596 | val_acc=0.7986
Época 20/200 | train_loss=1.0576 | val_loss=0.6967 | val_acc=0.7714
Época 21/200 | train_loss=1.0567 | val_loss=0.6667 | val_acc=0.7878
Época 22/200 | train_loss=1.0522 | val_loss=1.0635 | val_acc=0.6534
Época 23/200 | train_loss=1.0576 | val_loss=0.5711 | val_acc=0.8130
Época 24/200 | train_loss=1.0578 | val_loss=0.6990 | val_acc=0.7794
Época 25/200 | train_loss=1.0317 | val_loss=0.6234 | val_acc=0.7976
Época 26/200 | train_loss=1.0657 | val_loss=0.7511 | val_acc=0.7446
Época 27/200 | train_loss=1.0424 | val_loss=0.7183 | val_acc=0.7646
Época 28/200 | train_loss=1.0506 | val_loss=0.5774 | val_acc=0.8142
Época 29/200 | train_loss=1.0431 | val_loss=0.6047 | val_acc=0.8046
Época 30/200 | train_loss=1.0618 | val_loss=0.6233 | val_acc=0.7990
Época 31/200 | train_loss=1.0179 | val_loss=0.6409 | val_acc=0.7930
Época 32/200 | train_loss=1.0130 | val_loss=0.8062 | val_acc=0.7424
Época 33/200 | train_loss=1.0299 | val_loss=0.6097 | val_acc=0.8064
Época 34/200 | train_loss=1.0290 | val_loss=0.6450 | val_acc=0.7906
Época 35/200 | train_loss=1.0220 | val_loss=0.7078 | val_acc=0.7730
Época 36/200 | train_loss=1.0051 | val_loss=0.6908 | val_acc=0.7922
Época 37/200 | train_loss=1.0196 | val_loss=0.6197 | val_acc=0.8142
Época 38/200 | train_loss=0.9945 | val_loss=0.8191 | val_acc=0.7252
Época 39/200 | train_loss=1.0112 | val_loss=0.7389 | val_acc=0.7530
Época 40/200 | train_loss=1.0056 | val_loss=0.7472 | val_acc=0.7556
Época 41/200 | train_loss=1.0088 | val_loss=0.6499 | val_acc=0.8028
Época 42/200 | train_loss=1.0056 | val_loss=0.6394 | val_acc=0.8038
Época 43/200 | train_loss=0.9821 | val_loss=0.8251 | val_acc=0.7352
Época 44/200 | train_loss=0.9818 | val_loss=0.6228 | val_acc=0.8096
Época 45/200 | train_loss=1.0075 | val_loss=0.5704 | val_acc=0.8106
Época 46/200 | train_loss=0.9906 | val_loss=0.5817 | val_acc=0.8210
Época 47/200 | train_loss=0.9969 | val_loss=0.6369 | val_acc=0.7940
Época 48/200 | train_loss=1.0161 | val_loss=0.6494 | val_acc=0.7968
Época 49/200 | train_loss=0.9728 | val_loss=0.6975 | val_acc=0.7820
Época 50/200 | train_loss=0.9866 | val_loss=0.5816 | val_acc=0.8084
Época 51/200 | train_loss=0.9789 | val_loss=0.7555 | val_acc=0.7516
Época 52/200 | train_loss=0.9908 | val_loss=0.9669 | val_acc=0.6768
Época 53/200 | train_loss=0.9745 | val_loss=0.7044 | val_acc=0.7678
Época 54/200 | train_loss=0.9501 | val_loss=0.6056 | val_acc=0.8104
Época 55/200 | train_loss=0.9562 | val_loss=0.8336 | val_acc=0.7228
Época 56/200 | train_loss=0.9782 | val_loss=0.5732 | val_acc=0.8280
Época 57/200 | train_loss=0.9736 | val_loss=0.6387 | val_acc=0.8084
Época 58/200 | train_loss=0.9880 | val_loss=0.5901 | val_acc=0.8100
Época 59/200 | train_loss=0.9790 | val_loss=0.7340 | val_acc=0.7528
Época 60/200 | train_loss=0.9589 | val_loss=0.5904 | val_acc=0.8204
Época 61/200 | train_loss=0.9804 | val_loss=0.5347 | val_acc=0.8292
Época 62/200 | train_loss=0.9725 | val_loss=0.6310 | val_acc=0.7898
Época 63/200 | train_loss=0.9790 | val_loss=0.5848 | val_acc=0.8188
Época 64/200 | train_loss=0.9576 | val_loss=0.6517 | val_acc=0.7966
Época 65/200 | train_loss=0.9525 | val_loss=0.6380 | val_acc=0.8012
Época 66/200 | train_loss=0.9377 | val_loss=0.7487 | val_acc=0.7624
Época 67/200 | train_loss=0.9758 | val_loss=0.7171 | val_acc=0.7748
Época 68/200 | train_loss=0.9741 | val_loss=0.6216 | val_acc=0.8364
Época 69/200 | train_loss=0.9287 | val_loss=0.5843 | val_acc=0.8070
Época 70/200 | train_loss=0.9419 | val_loss=0.5525 | val_acc=0.8176
Época 71/200 | train_loss=0.9440 | val_loss=0.5236 | val_acc=0.8432
Época 72/200 | train_loss=0.9371 | val_loss=0.6144 | val_acc=0.8076
Época 73/200 | train_loss=0.9504 | val_loss=0.5471 | val_acc=0.8316
Época 74/200 | train_loss=0.9405 | val_loss=0.5343 | val_acc=0.8456
Época 75/200 | train_loss=0.9057 | val_loss=0.6215 | val_acc=0.8052
Época 76/200 | train_loss=0.9167 | val_loss=0.5925 | val_acc=0.8184
Época 77/200 | train_loss=0.9159 | val_loss=0.4828 | val_acc=0.8446
Época 78/200 | train_loss=0.9181 | val_loss=0.6543 | val_acc=0.7976
Época 79/200 | train_loss=0.9211 | val_loss=0.6251 | val_acc=0.7994
Época 80/200 | train_loss=0.9371 | val_loss=0.6548 | val_acc=0.8066
Época 81/200 | train_loss=0.9290 | val_loss=0.4993 | val_acc=0.8482
Época 82/200 | train_loss=0.8993 | val_loss=0.6621 | val_acc=0.7932
Época 83/200 | train_loss=0.9140 | val_loss=0.5425 | val_acc=0.8350
Época 84/200 | train_loss=0.8847 | val_loss=0.6053 | val_acc=0.8002
Época 85/200 | train_loss=0.8983 | val_loss=0.5758 | val_acc=0.8236
Época 86/200 | train_loss=0.8970 | val_loss=0.4964 | val_acc=0.8484
Época 87/200 | train_loss=0.8996 | val_loss=0.4953 | val_acc=0.8452
Época 88/200 | train_loss=0.8967 | val_loss=0.5037 | val_acc=0.8502
Época 89/200 | train_loss=0.8891 | val_loss=0.6015 | val_acc=0.8054
Época 90/200 | train_loss=0.8837 | val_loss=0.5574 | val_acc=0.8358
Época 91/200 | train_loss=0.8845 | val_loss=0.5670 | val_acc=0.8256
Época 92/200 | train_loss=0.8983 | val_loss=0.6271 | val_acc=0.7874
Época 93/200 | train_loss=0.9054 | val_loss=0.5265 | val_acc=0.8246
Época 94/200 | train_loss=0.8608 | val_loss=0.5141 | val_acc=0.8432
Época 95/200 | train_loss=0.8606 | val_loss=0.5454 | val_acc=0.8314
Época 96/200 | train_loss=0.8719 | val_loss=0.5049 | val_acc=0.8398
Época 97/200 | train_loss=0.8699 | val_loss=0.5505 | val_acc=0.8448
Época 98/200 | train_loss=0.8405 | val_loss=0.4764 | val_acc=0.8498
Época 99/200 | train_loss=0.8513 | val_loss=0.5542 | val_acc=0.8182
Época 100/200 | train_loss=0.8573 | val_loss=0.5844 | val_acc=0.8108
Época 101/200 | train_loss=0.8495 | val_loss=0.5120 | val_acc=0.8552
Época 102/200 | train_loss=0.8521 | val_loss=0.5035 | val_acc=0.8414
Época 103/200 | train_loss=0.8556 | val_loss=0.4967 | val_acc=0.8414
Época 104/200 | train_loss=0.8401 | val_loss=0.4549 | val_acc=0.8574
Época 105/200 | train_loss=0.8611 | val_loss=0.5510 | val_acc=0.8248
Época 106/200 | train_loss=0.8251 | val_loss=0.4039 | val_acc=0.8788
Época 107/200 | train_loss=0.8475 | val_loss=0.4550 | val_acc=0.8696
Época 108/200 | train_loss=0.8563 | val_loss=0.4252 | val_acc=0.8734
Época 109/200 | train_loss=0.8323 | val_loss=0.5191 | val_acc=0.8320
Época 110/200 | train_loss=0.8115 | val_loss=0.4933 | val_acc=0.8532
Época 111/200 | train_loss=0.8359 | val_loss=0.5405 | val_acc=0.8348
Época 112/200 | train_loss=0.8281 | val_loss=0.4541 | val_acc=0.8506
Época 113/200 | train_loss=0.8219 | val_loss=0.4870 | val_acc=0.8528
Época 114/200 | train_loss=0.8262 | val_loss=0.4624 | val_acc=0.8556
Época 115/200 | train_loss=0.7938 | val_loss=0.5039 | val_acc=0.8496
Época 116/200 | train_loss=0.7790 | val_loss=0.4321 | val_acc=0.8628
Época 117/200 | train_loss=0.7893 | val_loss=0.4847 | val_acc=0.8588
Época 118/200 | train_loss=0.7998 | val_loss=0.4566 | val_acc=0.8680
Época 119/200 | train_loss=0.8255 | val_loss=0.4137 | val_acc=0.8720
Época 120/200 | train_loss=0.8223 | val_loss=0.4271 | val_acc=0.8728
Época 121/200 | train_loss=0.7937 | val_loss=0.3825 | val_acc=0.8820
Época 122/200 | train_loss=0.7499 | val_loss=0.4756 | val_acc=0.8668
Época 123/200 | train_loss=0.7751 | val_loss=0.3464 | val_acc=0.8874
Época 124/200 | train_loss=0.7573 | val_loss=0.4041 | val_acc=0.8840
Época 125/200 | train_loss=0.7509 | val_loss=0.4716 | val_acc=0.8892
Época 126/200 | train_loss=0.7612 | val_loss=0.3991 | val_acc=0.8828
Época 127/200 | train_loss=0.7533 | val_loss=0.3648 | val_acc=0.8940
Época 128/200 | train_loss=0.7488 | val_loss=0.3817 | val_acc=0.8906
Época 129/200 | train_loss=0.7514 | val_loss=0.4092 | val_acc=0.8692
Época 130/200 | train_loss=0.7342 | val_loss=0.3919 | val_acc=0.8826
Época 131/200 | train_loss=0.7452 | val_loss=0.4791 | val_acc=0.8590
Época 132/200 | train_loss=0.7416 | val_loss=0.3253 | val_acc=0.9046
Época 133/200 | train_loss=0.7615 | val_loss=0.3432 | val_acc=0.8868
Época 134/200 | train_loss=0.7313 | val_loss=0.3342 | val_acc=0.9008
Época 135/200 | train_loss=0.7020 | val_loss=0.4001 | val_acc=0.8880
Época 136/200 | train_loss=0.7106 | val_loss=0.3635 | val_acc=0.8930
Época 137/200 | train_loss=0.7174 | val_loss=0.3790 | val_acc=0.8874
Época 138/200 | train_loss=0.6741 | val_loss=0.3739 | val_acc=0.8958
Época 139/200 | train_loss=0.7004 | val_loss=0.3694 | val_acc=0.8904
Época 140/200 | train_loss=0.7170 | val_loss=0.3400 | val_acc=0.9014
Época 141/200 | train_loss=0.7159 | val_loss=0.4183 | val_acc=0.8876
Época 142/200 | train_loss=0.7134 | val_loss=0.3208 | val_acc=0.9114
Época 143/200 | train_loss=0.6713 | val_loss=0.3313 | val_acc=0.9032
Época 144/200 | train_loss=0.7038 | val_loss=0.3712 | val_acc=0.9060
Época 145/200 | train_loss=0.6776 | val_loss=0.3242 | val_acc=0.9128
Época 146/200 | train_loss=0.6575 | val_loss=0.3373 | val_acc=0.9032
Época 147/200 | train_loss=0.6753 | val_loss=0.3116 | val_acc=0.9032
Época 148/200 | train_loss=0.6597 | val_loss=0.3132 | val_acc=0.9092
Época 149/200 | train_loss=0.6445 | val_loss=0.3164 | val_acc=0.9062
Época 150/200 | train_loss=0.6496 | val_loss=0.2850 | val_acc=0.9120
Época 151/200 | train_loss=0.6434 | val_loss=0.3452 | val_acc=0.9152
Época 152/200 | train_loss=0.6290 | val_loss=0.3013 | val_acc=0.9162
Época 153/200 | train_loss=0.6349 | val_loss=0.2861 | val_acc=0.9146
Época 154/200 | train_loss=0.6507 | val_loss=0.3075 | val_acc=0.9214
Época 155/200 | train_loss=0.6179 | val_loss=0.2836 | val_acc=0.9160
Época 156/200 | train_loss=0.6288 | val_loss=0.2890 | val_acc=0.9100
Época 157/200 | train_loss=0.6001 | val_loss=0.2592 | val_acc=0.9234
Época 158/200 | train_loss=0.5985 | val_loss=0.2804 | val_acc=0.9222
Época 159/200 | train_loss=0.5973 | val_loss=0.3203 | val_acc=0.9206
Época 160/200 | train_loss=0.5669 | val_loss=0.2522 | val_acc=0.9354
Época 161/200 | train_loss=0.5932 | val_loss=0.2735 | val_acc=0.9282
Época 162/200 | train_loss=0.5774 | val_loss=0.2982 | val_acc=0.9236
Época 163/200 | train_loss=0.5614 | val_loss=0.2672 | val_acc=0.9280
Época 164/200 | train_loss=0.5621 | val_loss=0.2615 | val_acc=0.9206
Época 165/200 | train_loss=0.5664 | val_loss=0.2889 | val_acc=0.9186
Época 166/200 | train_loss=0.5483 | val_loss=0.2720 | val_acc=0.9236
Época 167/200 | train_loss=0.5489 | val_loss=0.2427 | val_acc=0.9280
Época 168/200 | train_loss=0.5100 | val_loss=0.2198 | val_acc=0.9338
Época 169/200 | train_loss=0.5258 | val_loss=0.2901 | val_acc=0.9348
Época 170/200 | train_loss=0.5131 | val_loss=0.2427 | val_acc=0.9346
Época 171/200 | train_loss=0.5262 | val_loss=0.2031 | val_acc=0.9376
Época 172/200 | train_loss=0.5239 | val_loss=0.2280 | val_acc=0.9332
Época 173/200 | train_loss=0.5069 | val_loss=0.2511 | val_acc=0.9410
Época 174/200 | train_loss=0.5292 | val_loss=0.2444 | val_acc=0.9374
Época 175/200 | train_loss=0.4969 | val_loss=0.2087 | val_acc=0.9420
Época 176/200 | train_loss=0.5039 | val_loss=0.1977 | val_acc=0.9470
Época 177/200 | train_loss=0.4614 | val_loss=0.2100 | val_acc=0.9454
Época 178/200 | train_loss=0.4833 | val_loss=0.2217 | val_acc=0.9464
Época 179/200 | train_loss=0.4921 | val_loss=0.2335 | val_acc=0.9460
Época 180/200 | train_loss=0.5104 | val_loss=0.2199 | val_acc=0.9446
Época 181/200 | train_loss=0.5094 | val_loss=0.2038 | val_acc=0.9476
Época 182/200 | train_loss=0.4958 | val_loss=0.2097 | val_acc=0.9524
Época 183/200 | train_loss=0.4705 | val_loss=0.2279 | val_acc=0.9514
Época 184/200 | train_loss=0.4614 | val_loss=0.1634 | val_acc=0.9518
Época 185/200 | train_loss=0.4646 | val_loss=0.2000 | val_acc=0.9492
Época 186/200 | train_loss=0.4736 | val_loss=0.1868 | val_acc=0.9470
Época 187/200 | train_loss=0.4511 | val_loss=0.1944 | val_acc=0.9508
Época 188/200 | train_loss=0.4727 | val_loss=0.1689 | val_acc=0.9540
Época 189/200 | train_loss=0.4599 | val_loss=0.1637 | val_acc=0.9546
Época 190/200 | train_loss=0.4848 | val_loss=0.1653 | val_acc=0.9524
Época 191/200 | train_loss=0.4599 | val_loss=0.1948 | val_acc=0.9546
Época 192/200 | train_loss=0.4632 | val_loss=0.1958 | val_acc=0.9542
Época 193/200 | train_loss=0.4449 | val_loss=0.1960 | val_acc=0.9538
Época 194/200 | train_loss=0.4629 | val_loss=0.1798 | val_acc=0.9516
Época 195/200 | train_loss=0.4316 | val_loss=0.1825 | val_acc=0.9532
Época 196/200 | train_loss=0.4918 | val_loss=0.1886 | val_acc=0.9528
Época 197/200 | train_loss=0.4393 | val_loss=0.1851 | val_acc=0.9532
Época 198/200 | train_loss=0.4250 | val_loss=0.1809 | val_acc=0.9536
Época 199/200 | train_loss=0.4244 | val_loss=0.1743 | val_acc=0.9542
Época 200/200 | train_loss=0.4523 | val_loss=0.1828 | val_acc=0.9532
Métricas no conjunto de teste: {'accuracy': 0.9429, 'balanced_accuracy': np.float64(0.9429000000000001), 'precision': 0.9432000179692328, 'recall': 0.9429, 'f1_score': 0.9429298030594657}
Acurácia por classe: {'airplane': 0.964, 'automobile': 0.976, 'bird': 0.943, 'cat': 0.882, 'deer': 0.95, 'dog': 0.894, 'frog': 0.962, 'horse': 0.948, 'ship': 0.962, 'truck': 0.948}
[model-saver] Modelo salvo em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_vgg4_cutmix_20260910-202444/

treinando 'vgg4_mixcut_both':   0%|          | 0/200 [00:00<?, ?it/s]

Época 1/200 | train_loss=1.9148 | val_loss=1.4597 | val_acc=0.4362
Época 2/200 | train_loss=1.5406 | val_loss=1.1208 | val_acc=0.6072
Época 3/200 | train_loss=1.3290 | val_loss=1.0705 | val_acc=0.6282
Época 4/200 | train_loss=1.2008 | val_loss=1.1028 | val_acc=0.6192
Época 5/200 | train_loss=1.1437 | val_loss=0.8466 | val_acc=0.7158
Época 6/200 | train_loss=1.0945 | val_loss=0.7427 | val_acc=0.7538
Época 7/200 | train_loss=1.0770 | val_loss=1.1859 | val_acc=0.6220
Época 8/200 | train_loss=1.0584 | val_loss=0.8620 | val_acc=0.7216
Época 9/200 | train_loss=1.0154 | val_loss=0.6878 | val_acc=0.7790
Época 10/200 | train_loss=0.9948 | val_loss=0.8509 | val_acc=0.7116
Época 11/200 | train_loss=0.9891 | val_loss=0.6757 | val_acc=0.7720
Época 12/200 | train_loss=0.9652 | val_loss=0.9197 | val_acc=0.6992
Época 13/200 | train_loss=0.9708 | val_loss=0.7516 | val_acc=0.7442
Época 14/200 | train_loss=0.9583 | val_loss=0.6925 | val_acc=0.7750
Época 15/200 | train_loss=0.9638 | val_loss=0.7326 | val_acc=0.7600
Época 16/200 | train_loss=0.9530 | val_loss=0.7420 | val_acc=0.7590
Época 17/200 | train_loss=0.9396 | val_loss=0.7576 | val_acc=0.7500
Época 18/200 | train_loss=0.9375 | val_loss=0.6810 | val_acc=0.7816
Época 19/200 | train_loss=0.9341 | val_loss=0.7769 | val_acc=0.7474
Época 20/200 | train_loss=0.9516 | val_loss=0.6685 | val_acc=0.7834
Época 21/200 | train_loss=0.9213 | val_loss=0.6338 | val_acc=0.7998
Época 22/200 | train_loss=0.9237 | val_loss=0.6910 | val_acc=0.7724
Época 23/200 | train_loss=0.9361 | val_loss=0.6956 | val_acc=0.7692
Época 24/200 | train_loss=0.9233 | val_loss=0.7617 | val_acc=0.7414
Época 25/200 | train_loss=0.9196 | val_loss=0.5383 | val_acc=0.8172
Época 26/200 | train_loss=0.9399 | val_loss=0.6328 | val_acc=0.7866
Época 27/200 | train_loss=0.9133 | val_loss=0.6311 | val_acc=0.8002
Época 28/200 | train_loss=0.9104 | val_loss=0.6909 | val_acc=0.7712
Época 29/200 | train_loss=0.9026 | val_loss=0.6720 | val_acc=0.7922
Época 30/200 | train_loss=0.8996 | val_loss=0.6125 | val_acc=0.8026
Época 31/200 | train_loss=0.8872 | val_loss=0.6310 | val_acc=0.7840
Época 32/200 | train_loss=0.9127 | val_loss=0.6858 | val_acc=0.7784
Época 33/200 | train_loss=0.8833 | val_loss=0.6031 | val_acc=0.8164
Época 34/200 | train_loss=0.8851 | val_loss=0.5945 | val_acc=0.8016
Época 35/200 | train_loss=0.8863 | val_loss=0.5644 | val_acc=0.8140
Época 36/200 | train_loss=0.9137 | val_loss=0.6584 | val_acc=0.7792
Época 37/200 | train_loss=0.8735 | val_loss=0.7049 | val_acc=0.7662
Época 38/200 | train_loss=0.8911 | val_loss=0.6776 | val_acc=0.7810
Época 39/200 | train_loss=0.8906 | val_loss=0.6398 | val_acc=0.7906
Época 40/200 | train_loss=0.8913 | val_loss=0.5154 | val_acc=0.8304
Época 41/200 | train_loss=0.8886 | val_loss=0.6477 | val_acc=0.7860
Época 42/200 | train_loss=0.8528 | val_loss=0.5755 | val_acc=0.8066
Época 43/200 | train_loss=0.8784 | val_loss=0.6629 | val_acc=0.7864
Época 44/200 | train_loss=0.8705 | val_loss=0.6063 | val_acc=0.8048
Época 45/200 | train_loss=0.8585 | val_loss=0.6006 | val_acc=0.8038
Época 46/200 | train_loss=0.8662 | val_loss=0.6769 | val_acc=0.7802
Época 47/200 | train_loss=0.8510 | val_loss=0.5212 | val_acc=0.8330
Época 48/200 | train_loss=0.8677 | val_loss=0.8072 | val_acc=0.7462
Época 49/200 | train_loss=0.8504 | val_loss=0.7677 | val_acc=0.7448
Época 50/200 | train_loss=0.8523 | val_loss=0.6738 | val_acc=0.7842
Época 51/200 | train_loss=0.8527 | val_loss=0.6200 | val_acc=0.8066
Época 52/200 | train_loss=0.8570 | val_loss=0.5571 | val_acc=0.8306
Época 53/200 | train_loss=0.8675 | val_loss=0.5888 | val_acc=0.8258
Época 54/200 | train_loss=0.8318 | val_loss=0.5337 | val_acc=0.8320
Época 55/200 | train_loss=0.8401 | val_loss=0.6123 | val_acc=0.8038
Época 56/200 | train_loss=0.8387 | val_loss=0.6086 | val_acc=0.8010
Época 57/200 | train_loss=0.8353 | val_loss=0.6204 | val_acc=0.7958
Época 58/200 | train_loss=0.8332 | val_loss=0.6777 | val_acc=0.7810
Época 59/200 | train_loss=0.8192 | val_loss=0.7137 | val_acc=0.7724
Época 60/200 | train_loss=0.8287 | val_loss=0.6859 | val_acc=0.7882
Época 61/200 | train_loss=0.8134 | val_loss=0.7304 | val_acc=0.7632
Época 62/200 | train_loss=0.8313 | val_loss=0.6377 | val_acc=0.8000
Época 63/200 | train_loss=0.8547 | val_loss=0.5233 | val_acc=0.8322
Época 64/200 | train_loss=0.7987 | val_loss=0.6269 | val_acc=0.7892
Época 65/200 | train_loss=0.8226 | val_loss=0.5017 | val_acc=0.8432
Época 66/200 | train_loss=0.8008 | val_loss=0.5637 | val_acc=0.8330
Época 67/200 | train_loss=0.8234 | val_loss=0.5745 | val_acc=0.8238
Época 68/200 | train_loss=0.8214 | val_loss=0.5478 | val_acc=0.8296
Época 69/200 | train_loss=0.7998 | val_loss=0.6250 | val_acc=0.7996
Época 70/200 | train_loss=0.8066 | val_loss=0.5566 | val_acc=0.8296
Época 71/200 | train_loss=0.7985 | val_loss=0.5111 | val_acc=0.8368
Época 72/200 | train_loss=0.8275 | val_loss=0.7799 | val_acc=0.7474
Época 73/200 | train_loss=0.8009 | val_loss=0.6398 | val_acc=0.8054
Época 74/200 | train_loss=0.7934 | val_loss=0.6529 | val_acc=0.7956
Época 75/200 | train_loss=0.7973 | val_loss=0.4414 | val_acc=0.8556
Época 76/200 | train_loss=0.7688 | val_loss=0.7732 | val_acc=0.7406
Época 77/200 | train_loss=0.8104 | val_loss=0.5006 | val_acc=0.8338
Época 78/200 | train_loss=0.7783 | val_loss=0.4805 | val_acc=0.8452
Época 79/200 | train_loss=0.8111 | val_loss=0.5539 | val_acc=0.8302
Época 80/200 | train_loss=0.7696 | val_loss=0.4962 | val_acc=0.8454
Época 81/200 | train_loss=0.7568 | val_loss=0.6150 | val_acc=0.8044
Época 82/200 | train_loss=0.7738 | val_loss=0.6065 | val_acc=0.8028
Época 83/200 | train_loss=0.7935 | val_loss=0.5064 | val_acc=0.8342
Época 84/200 | train_loss=0.7671 | val_loss=0.5260 | val_acc=0.8550
Época 85/200 | train_loss=0.7440 | val_loss=0.5174 | val_acc=0.8480
Época 86/200 | train_loss=0.7390 | val_loss=0.5342 | val_acc=0.8354
Época 87/200 | train_loss=0.7737 | val_loss=0.5112 | val_acc=0.8246
Época 88/200 | train_loss=0.7579 | val_loss=0.5417 | val_acc=0.8268
Época 89/200 | train_loss=0.7738 | val_loss=0.5206 | val_acc=0.8282
Época 90/200 | train_loss=0.7790 | val_loss=0.5432 | val_acc=0.8362
Época 91/200 | train_loss=0.7437 | val_loss=0.4851 | val_acc=0.8396
Época 92/200 | train_loss=0.7351 | val_loss=0.4465 | val_acc=0.8676
Época 93/200 | train_loss=0.7520 | val_loss=0.5851 | val_acc=0.8256
Época 94/200 | train_loss=0.7371 | val_loss=0.5050 | val_acc=0.8316
Época 95/200 | train_loss=0.7438 | val_loss=0.5966 | val_acc=0.8088
Época 96/200 | train_loss=0.7291 | val_loss=0.4260 | val_acc=0.8582
Época 97/200 | train_loss=0.7151 | val_loss=0.4457 | val_acc=0.8710
Época 98/200 | train_loss=0.7270 | val_loss=0.5427 | val_acc=0.8588
Época 99/200 | train_loss=0.7116 | val_loss=0.5190 | val_acc=0.8472
Época 100/200 | train_loss=0.7278 | val_loss=0.5518 | val_acc=0.8426
Época 101/200 | train_loss=0.7207 | val_loss=0.4741 | val_acc=0.8494
Época 102/200 | train_loss=0.7011 | val_loss=0.5989 | val_acc=0.8002
Época 103/200 | train_loss=0.7052 | val_loss=0.5025 | val_acc=0.8310
Época 104/200 | train_loss=0.7293 | val_loss=0.4050 | val_acc=0.8746
Época 105/200 | train_loss=0.7111 | val_loss=0.5004 | val_acc=0.8424
Época 106/200 | train_loss=0.6823 | val_loss=0.4759 | val_acc=0.8550
Época 107/200 | train_loss=0.6967 | val_loss=0.6475 | val_acc=0.7820
Época 108/200 | train_loss=0.6982 | val_loss=0.4919 | val_acc=0.8542
Época 109/200 | train_loss=0.6907 | val_loss=0.4306 | val_acc=0.8710
Época 110/200 | train_loss=0.7018 | val_loss=0.5100 | val_acc=0.8390
Época 111/200 | train_loss=0.6883 | val_loss=0.4482 | val_acc=0.8612
Época 112/200 | train_loss=0.6955 | val_loss=0.4792 | val_acc=0.8668
Época 113/200 | train_loss=0.6902 | val_loss=0.4210 | val_acc=0.8674
Época 114/200 | train_loss=0.6736 | val_loss=0.4581 | val_acc=0.8624
Época 115/200 | train_loss=0.6950 | val_loss=0.3846 | val_acc=0.8792
Época 116/200 | train_loss=0.6651 | val_loss=0.4326 | val_acc=0.8722
Época 117/200 | train_loss=0.6566 | val_loss=0.4437 | val_acc=0.8782
Época 118/200 | train_loss=0.6792 | val_loss=0.3720 | val_acc=0.8818
Época 119/200 | train_loss=0.6512 | val_loss=0.3825 | val_acc=0.8772
Época 120/200 | train_loss=0.6418 | val_loss=0.4495 | val_acc=0.8592
Época 121/200 | train_loss=0.6601 | val_loss=0.4056 | val_acc=0.8928
Época 122/200 | train_loss=0.6570 | val_loss=0.4198 | val_acc=0.8672
Época 123/200 | train_loss=0.6419 | val_loss=0.4337 | val_acc=0.8728
Época 124/200 | train_loss=0.6337 | val_loss=0.3540 | val_acc=0.8930
Época 125/200 | train_loss=0.6459 | val_loss=0.3811 | val_acc=0.8850
Época 126/200 | train_loss=0.6092 | val_loss=0.4478 | val_acc=0.8612
Época 127/200 | train_loss=0.6327 | val_loss=0.3340 | val_acc=0.8990
Época 128/200 | train_loss=0.5957 | val_loss=0.3937 | val_acc=0.8804
Época 129/200 | train_loss=0.6082 | val_loss=0.3536 | val_acc=0.8900
Época 130/200 | train_loss=0.6277 | val_loss=0.4256 | val_acc=0.8904
Época 131/200 | train_loss=0.6312 | val_loss=0.3663 | val_acc=0.8984
Época 132/200 | train_loss=0.5853 | val_loss=0.4079 | val_acc=0.8712
Época 133/200 | train_loss=0.6070 | val_loss=0.4948 | val_acc=0.8634
Época 134/200 | train_loss=0.6013 | val_loss=0.3579 | val_acc=0.8898
Época 135/200 | train_loss=0.5936 | val_loss=0.3509 | val_acc=0.9062
Época 136/200 | train_loss=0.6226 | val_loss=0.3663 | val_acc=0.8994
Época 137/200 | train_loss=0.5664 | val_loss=0.3116 | val_acc=0.9090
Época 138/200 | train_loss=0.5670 | val_loss=0.3299 | val_acc=0.9012
Época 139/200 | train_loss=0.5588 | val_loss=0.3428 | val_acc=0.9042
Época 140/200 | train_loss=0.5648 | val_loss=0.3260 | val_acc=0.9028
Época 141/200 | train_loss=0.5717 | val_loss=0.3180 | val_acc=0.8968
Época 142/200 | train_loss=0.5769 | val_loss=0.3360 | val_acc=0.9026
Época 143/200 | train_loss=0.5767 | val_loss=0.3832 | val_acc=0.8866
Época 144/200 | train_loss=0.5557 | val_loss=0.2928 | val_acc=0.9112
Época 145/200 | train_loss=0.5666 | val_loss=0.3154 | val_acc=0.9084
Época 146/200 | train_loss=0.5348 | val_loss=0.3247 | val_acc=0.9150
Época 147/200 | train_loss=0.5320 | val_loss=0.3818 | val_acc=0.8910
Época 148/200 | train_loss=0.5199 | val_loss=0.2854 | val_acc=0.9142
Época 149/200 | train_loss=0.5174 | val_loss=0.2951 | val_acc=0.9090
Época 150/200 | train_loss=0.4879 | val_loss=0.3484 | val_acc=0.8918
Época 151/200 | train_loss=0.5066 | val_loss=0.2803 | val_acc=0.9108
Época 152/200 | train_loss=0.5048 | val_loss=0.3163 | val_acc=0.8996
Época 153/200 | train_loss=0.4672 | val_loss=0.2589 | val_acc=0.9216
Época 154/200 | train_loss=0.4967 | val_loss=0.3058 | val_acc=0.9202
Época 155/200 | train_loss=0.4853 | val_loss=0.2964 | val_acc=0.9182
Época 156/200 | train_loss=0.4969 | val_loss=0.2991 | val_acc=0.9146
Época 157/200 | train_loss=0.4932 | val_loss=0.2932 | val_acc=0.9116
Época 158/200 | train_loss=0.4902 | val_loss=0.2844 | val_acc=0.9298
Época 159/200 | train_loss=0.4542 | val_loss=0.2934 | val_acc=0.9196
Época 160/200 | train_loss=0.4586 | val_loss=0.2700 | val_acc=0.9250
Época 161/200 | train_loss=0.4714 | val_loss=0.2755 | val_acc=0.9258
Época 162/200 | train_loss=0.4550 | val_loss=0.2405 | val_acc=0.9274
Época 163/200 | train_loss=0.4724 | val_loss=0.2623 | val_acc=0.9328
Época 164/200 | train_loss=0.4483 | val_loss=0.2873 | val_acc=0.9242
Época 165/200 | train_loss=0.4399 | val_loss=0.2265 | val_acc=0.9338
Época 166/200 | train_loss=0.4404 | val_loss=0.2450 | val_acc=0.9252
Época 167/200 | train_loss=0.4103 | val_loss=0.2178 | val_acc=0.9396
Época 168/200 | train_loss=0.4276 | val_loss=0.2597 | val_acc=0.9278
Época 169/200 | train_loss=0.4097 | val_loss=0.2943 | val_acc=0.9290
Época 170/200 | train_loss=0.4040 | val_loss=0.2501 | val_acc=0.9350
Época 171/200 | train_loss=0.3945 | val_loss=0.2832 | val_acc=0.9334
Época 172/200 | train_loss=0.4039 | val_loss=0.2570 | val_acc=0.9374
Época 173/200 | train_loss=0.4071 | val_loss=0.1975 | val_acc=0.9414
Época 174/200 | train_loss=0.3881 | val_loss=0.2184 | val_acc=0.9398
Época 175/200 | train_loss=0.4005 | val_loss=0.2430 | val_acc=0.9372
Época 176/200 | train_loss=0.3769 | val_loss=0.2736 | val_acc=0.9386
Época 177/200 | train_loss=0.3795 | val_loss=0.2221 | val_acc=0.9428
Época 178/200 | train_loss=0.4005 | val_loss=0.1781 | val_acc=0.9438
Época 179/200 | train_loss=0.3769 | val_loss=0.2237 | val_acc=0.9438
Época 180/200 | train_loss=0.3839 | val_loss=0.1920 | val_acc=0.9448
Época 181/200 | train_loss=0.3550 | val_loss=0.1933 | val_acc=0.9458
Época 182/200 | train_loss=0.3737 | val_loss=0.1785 | val_acc=0.9510
Época 183/200 | train_loss=0.3618 | val_loss=0.1774 | val_acc=0.9532
Época 184/200 | train_loss=0.3695 | val_loss=0.2031 | val_acc=0.9502
Época 185/200 | train_loss=0.3778 | val_loss=0.2060 | val_acc=0.9488
Época 186/200 | train_loss=0.3527 | val_loss=0.1878 | val_acc=0.9514
Época 187/200 | train_loss=0.3538 | val_loss=0.1863 | val_acc=0.9514
Época 188/200 | train_loss=0.3662 | val_loss=0.1906 | val_acc=0.9518
Época 189/200 | train_loss=0.3451 | val_loss=0.1875 | val_acc=0.9534
Época 190/200 | train_loss=0.3579 | val_loss=0.2054 | val_acc=0.9534
Época 191/200 | train_loss=0.3543 | val_loss=0.2182 | val_acc=0.9526
Época 192/200 | train_loss=0.3457 | val_loss=0.2116 | val_acc=0.9526
Época 193/200 | train_loss=0.3388 | val_loss=0.1603 | val_acc=0.9526
Época 194/200 | train_loss=0.3499 | val_loss=0.1876 | val_acc=0.9538
Época 195/200 | train_loss=0.3427 | val_loss=0.1712 | val_acc=0.9544
Época 196/200 | train_loss=0.3534 | val_loss=0.1897 | val_acc=0.9554
Época 197/200 | train_loss=0.3593 | val_loss=0.1814 | val_acc=0.9528
Época 198/200 | train_loss=0.3429 | val_loss=0.2031 | val_acc=0.9546
Época 199/200 | train_loss=0.3359 | val_loss=0.1635 | val_acc=0.9544
Época 200/200 | train_loss=0.3351 | val_loss=0.1979 | val_acc=0.9540
Métricas no conjunto de teste: {'accuracy': 0.9469, 'balanced_accuracy': np.float64(0.9469), 'precision': 0.9468479278999681, 'recall': 0.9469, 'f1_score': 0.9468571657026705}
Acurácia por classe: {'airplane': 0.953, 'automobile': 0.975, 'bird': 0.925, 'cat': 0.877, 'deer': 0.962, 'dog': 0.902, 'frog': 0.969, 'horse': 0.968, 'ship': 0.975, 'truck': 0.963}
[model-saver] Modelo salvo em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_vgg4_mixcut_both_20260910-213245/

treinando 'vgg4_mixcut_aug_ls':   0%|          | 0/200 [00:00<?, ?it/s]

Época 1/200 | train_loss=2.0355 | val_loss=1.6591 | val_acc=0.4166
Época 2/200 | train_loss=1.7379 | val_loss=1.3595 | val_acc=0.6168
Época 3/200 | train_loss=1.5658 | val_loss=1.2311 | val_acc=0.6886
Época 4/200 | train_loss=1.4752 | val_loss=1.5420 | val_acc=0.5926
Época 5/200 | train_loss=1.4425 | val_loss=1.0924 | val_acc=0.7456
Época 6/200 | train_loss=1.4077 | val_loss=1.1818 | val_acc=0.7114
Época 7/200 | train_loss=1.4029 | val_loss=1.1658 | val_acc=0.7058
Época 8/200 | train_loss=1.3877 | val_loss=1.0862 | val_acc=0.7588
Época 9/200 | train_loss=1.3565 | val_loss=1.0917 | val_acc=0.7484
Época 10/200 | train_loss=1.3393 | val_loss=1.1560 | val_acc=0.7156
Época 11/200 | train_loss=1.3429 | val_loss=1.1163 | val_acc=0.7374
Época 12/200 | train_loss=1.3268 | val_loss=1.0729 | val_acc=0.7512
Época 13/200 | train_loss=1.3268 | val_loss=1.0021 | val_acc=0.7844
Época 14/200 | train_loss=1.3240 | val_loss=1.2077 | val_acc=0.6916
Época 15/200 | train_loss=1.3198 | val_loss=0.9673 | val_acc=0.8006
Época 16/200 | train_loss=1.3174 | val_loss=0.9899 | val_acc=0.7948
Época 17/200 | train_loss=1.3054 | val_loss=1.0503 | val_acc=0.7624
Época 18/200 | train_loss=1.3032 | val_loss=1.0258 | val_acc=0.7714
Época 19/200 | train_loss=1.3036 | val_loss=1.0540 | val_acc=0.7666
Época 20/200 | train_loss=1.3159 | val_loss=0.9775 | val_acc=0.7982
Época 21/200 | train_loss=1.2952 | val_loss=1.0670 | val_acc=0.7580
Época 22/200 | train_loss=1.2926 | val_loss=1.0641 | val_acc=0.7612
Época 23/200 | train_loss=1.3001 | val_loss=1.1923 | val_acc=0.7102
Época 24/200 | train_loss=1.2970 | val_loss=1.0665 | val_acc=0.7546
Época 25/200 | train_loss=1.2851 | val_loss=0.9681 | val_acc=0.8020
Época 26/200 | train_loss=1.3024 | val_loss=1.0047 | val_acc=0.7822
Época 27/200 | train_loss=1.2832 | val_loss=0.9540 | val_acc=0.8098
Época 28/200 | train_loss=1.2841 | val_loss=1.0406 | val_acc=0.7674
Época 29/200 | train_loss=1.2766 | val_loss=1.0068 | val_acc=0.7948
Época 30/200 | train_loss=1.2722 | val_loss=1.0294 | val_acc=0.7748
Época 31/200 | train_loss=1.2616 | val_loss=1.0426 | val_acc=0.7662
Época 32/200 | train_loss=1.2855 | val_loss=1.0081 | val_acc=0.7816
Época 33/200 | train_loss=1.2615 | val_loss=1.0406 | val_acc=0.7744
Época 34/200 | train_loss=1.2663 | val_loss=0.9462 | val_acc=0.8064
Época 35/200 | train_loss=1.2641 | val_loss=0.9704 | val_acc=0.8004
Época 36/200 | train_loss=1.2846 | val_loss=0.9385 | val_acc=0.8130
Época 37/200 | train_loss=1.2566 | val_loss=1.1351 | val_acc=0.7264
Época 38/200 | train_loss=1.2718 | val_loss=1.0073 | val_acc=0.7848
Época 39/200 | train_loss=1.2752 | val_loss=0.9906 | val_acc=0.7936
Época 40/200 | train_loss=1.2767 | val_loss=0.9768 | val_acc=0.7912
Época 41/200 | train_loss=1.2683 | val_loss=0.9848 | val_acc=0.7930
Época 42/200 | train_loss=1.2463 | val_loss=0.9843 | val_acc=0.8002
Época 43/200 | train_loss=1.2667 | val_loss=1.0311 | val_acc=0.7678
Época 44/200 | train_loss=1.2573 | val_loss=0.9774 | val_acc=0.8016
Época 45/200 | train_loss=1.2533 | val_loss=0.9848 | val_acc=0.7920
Época 46/200 | train_loss=1.2517 | val_loss=0.9416 | val_acc=0.8120
Época 47/200 | train_loss=1.2477 | val_loss=0.9380 | val_acc=0.8176
Época 48/200 | train_loss=1.2553 | val_loss=0.9164 | val_acc=0.8320
Época 49/200 | train_loss=1.2495 | val_loss=0.9749 | val_acc=0.7982
Época 50/200 | train_loss=1.2479 | val_loss=1.0319 | val_acc=0.7706
Época 51/200 | train_loss=1.2491 | val_loss=0.9772 | val_acc=0.7978
Época 52/200 | train_loss=1.2505 | val_loss=0.9250 | val_acc=0.8260
Época 53/200 | train_loss=1.2579 | val_loss=1.0222 | val_acc=0.7866
Época 54/200 | train_loss=1.2364 | val_loss=0.9212 | val_acc=0.8206
Época 55/200 | train_loss=1.2352 | val_loss=1.0178 | val_acc=0.7724
Época 56/200 | train_loss=1.2384 | val_loss=0.9587 | val_acc=0.8048
Época 57/200 | train_loss=1.2385 | val_loss=0.9401 | val_acc=0.8106
Época 58/200 | train_loss=1.2327 | val_loss=0.9788 | val_acc=0.7912
Época 59/200 | train_loss=1.2222 | val_loss=0.9468 | val_acc=0.8158
Época 60/200 | train_loss=1.2283 | val_loss=0.8906 | val_acc=0.8334
Época 61/200 | train_loss=1.2100 | val_loss=1.0355 | val_acc=0.7742
Época 62/200 | train_loss=1.2365 | val_loss=0.9986 | val_acc=0.7796
Época 63/200 | train_loss=1.2484 | val_loss=0.9313 | val_acc=0.8188
Época 64/200 | train_loss=1.2069 | val_loss=0.9051 | val_acc=0.8272
Época 65/200 | train_loss=1.2255 | val_loss=0.9493 | val_acc=0.8110
Época 66/200 | train_loss=1.2129 | val_loss=0.9418 | val_acc=0.8182
Época 67/200 | train_loss=1.2204 | val_loss=0.8734 | val_acc=0.8412
Época 68/200 | train_loss=1.2222 | val_loss=1.0069 | val_acc=0.7882
Época 69/200 | train_loss=1.2102 | val_loss=1.1376 | val_acc=0.7308
Época 70/200 | train_loss=1.2131 | val_loss=0.8903 | val_acc=0.8398
Época 71/200 | train_loss=1.2084 | val_loss=0.9381 | val_acc=0.8146
Época 72/200 | train_loss=1.2323 | val_loss=1.0008 | val_acc=0.7844
Época 73/200 | train_loss=1.2026 | val_loss=0.9217 | val_acc=0.8264
Época 74/200 | train_loss=1.2025 | val_loss=0.9389 | val_acc=0.8258
Época 75/200 | train_loss=1.2031 | val_loss=0.8943 | val_acc=0.8332
Época 76/200 | train_loss=1.1873 | val_loss=1.0152 | val_acc=0.7752
Época 77/200 | train_loss=1.2181 | val_loss=0.9390 | val_acc=0.8046
Época 78/200 | train_loss=1.1892 | val_loss=0.9870 | val_acc=0.7956
Época 79/200 | train_loss=1.2155 | val_loss=0.9287 | val_acc=0.8154
Época 80/200 | train_loss=1.1803 | val_loss=0.8802 | val_acc=0.8462
Época 81/200 | train_loss=1.1796 | val_loss=0.9517 | val_acc=0.8138
Época 82/200 | train_loss=1.1853 | val_loss=0.9368 | val_acc=0.8110
Época 83/200 | train_loss=1.1992 | val_loss=1.0275 | val_acc=0.7696
Época 84/200 | train_loss=1.1858 | val_loss=0.8787 | val_acc=0.8442
Época 85/200 | train_loss=1.1676 | val_loss=0.8949 | val_acc=0.8382
Época 86/200 | train_loss=1.1651 | val_loss=0.9068 | val_acc=0.8318
Época 87/200 | train_loss=1.1897 | val_loss=0.8860 | val_acc=0.8382
Época 88/200 | train_loss=1.1762 | val_loss=0.9391 | val_acc=0.8152
Época 89/200 | train_loss=1.1908 | val_loss=0.8676 | val_acc=0.8450
Época 90/200 | train_loss=1.1913 | val_loss=0.8683 | val_acc=0.8510
Época 91/200 | train_loss=1.1652 | val_loss=0.9299 | val_acc=0.8144
Época 92/200 | train_loss=1.1608 | val_loss=0.8682 | val_acc=0.8436
Época 93/200 | train_loss=1.1722 | val_loss=0.8762 | val_acc=0.8366
Época 94/200 | train_loss=1.1637 | val_loss=0.9099 | val_acc=0.8274
Época 95/200 | train_loss=1.1603 | val_loss=0.9540 | val_acc=0.8024
Época 96/200 | train_loss=1.1551 | val_loss=0.9119 | val_acc=0.8208
Época 97/200 | train_loss=1.1414 | val_loss=0.9076 | val_acc=0.8374
Época 98/200 | train_loss=1.1562 | val_loss=0.8847 | val_acc=0.8402
Época 99/200 | train_loss=1.1383 | val_loss=0.9170 | val_acc=0.8252
Época 100/200 | train_loss=1.1519 | val_loss=0.9112 | val_acc=0.8264
Época 101/200 | train_loss=1.1484 | val_loss=0.8395 | val_acc=0.8616
Época 102/200 | train_loss=1.1345 | val_loss=0.8548 | val_acc=0.8500
Época 103/200 | train_loss=1.1353 | val_loss=0.8850 | val_acc=0.8376
Época 104/200 | train_loss=1.1581 | val_loss=0.8215 | val_acc=0.8642
Época 105/200 | train_loss=1.1409 | val_loss=0.8585 | val_acc=0.8536
Época 106/200 | train_loss=1.1128 | val_loss=0.8475 | val_acc=0.8604
Época 107/200 | train_loss=1.1309 | val_loss=0.8228 | val_acc=0.8654
Época 108/200 | train_loss=1.1247 | val_loss=0.8318 | val_acc=0.8582
Época 109/200 | train_loss=1.1263 | val_loss=0.8512 | val_acc=0.8522
Época 110/200 | train_loss=1.1342 | val_loss=0.9898 | val_acc=0.7914
Época 111/200 | train_loss=1.1194 | val_loss=0.8183 | val_acc=0.8614
Época 112/200 | train_loss=1.1294 | val_loss=0.8177 | val_acc=0.8752
Época 113/200 | train_loss=1.1204 | val_loss=0.8623 | val_acc=0.8480
Época 114/200 | train_loss=1.1134 | val_loss=0.8047 | val_acc=0.8776
Época 115/200 | train_loss=1.1274 | val_loss=0.8136 | val_acc=0.8708
Época 116/200 | train_loss=1.1064 | val_loss=0.8189 | val_acc=0.8690
Época 117/200 | train_loss=1.1026 | val_loss=0.7997 | val_acc=0.8744
Época 118/200 | train_loss=1.1181 | val_loss=0.8254 | val_acc=0.8582
Época 119/200 | train_loss=1.0909 | val_loss=0.8279 | val_acc=0.8546
Época 120/200 | train_loss=1.0880 | val_loss=0.8447 | val_acc=0.8510
Época 121/200 | train_loss=1.1013 | val_loss=0.8522 | val_acc=0.8592
Época 122/200 | train_loss=1.1010 | val_loss=0.8105 | val_acc=0.8714
Época 123/200 | train_loss=1.0862 | val_loss=0.8022 | val_acc=0.8760
Época 124/200 | train_loss=1.0809 | val_loss=0.8235 | val_acc=0.8700
Época 125/200 | train_loss=1.0924 | val_loss=0.8014 | val_acc=0.8728
Época 126/200 | train_loss=1.0606 | val_loss=0.8073 | val_acc=0.8736
Época 127/200 | train_loss=1.0768 | val_loss=0.7656 | val_acc=0.8910
Época 128/200 | train_loss=1.0513 | val_loss=0.7730 | val_acc=0.8842
Época 129/200 | train_loss=1.0618 | val_loss=0.7589 | val_acc=0.8882
Época 130/200 | train_loss=1.0760 | val_loss=0.8209 | val_acc=0.8714
Época 131/200 | train_loss=1.0746 | val_loss=0.7820 | val_acc=0.8806
Época 132/200 | train_loss=1.0460 | val_loss=0.8270 | val_acc=0.8704
Época 133/200 | train_loss=1.0566 | val_loss=0.8258 | val_acc=0.8746
Época 134/200 | train_loss=1.0589 | val_loss=0.7603 | val_acc=0.8918
Época 135/200 | train_loss=1.0452 | val_loss=0.7602 | val_acc=0.9052
Época 136/200 | train_loss=1.0701 | val_loss=0.7803 | val_acc=0.8910
Época 137/200 | train_loss=1.0346 | val_loss=0.7452 | val_acc=0.8972
Época 138/200 | train_loss=1.0266 | val_loss=0.7522 | val_acc=0.8992
Época 139/200 | train_loss=1.0241 | val_loss=0.8212 | val_acc=0.8636
Época 140/200 | train_loss=1.0242 | val_loss=0.7541 | val_acc=0.8936
Época 141/200 | train_loss=1.0308 | val_loss=0.7348 | val_acc=0.8988
Época 142/200 | train_loss=1.0367 | val_loss=0.7941 | val_acc=0.8840
Época 143/200 | train_loss=1.0375 | val_loss=0.7553 | val_acc=0.8990
Época 144/200 | train_loss=1.0181 | val_loss=0.7077 | val_acc=0.9110
Época 145/200 | train_loss=1.0235 | val_loss=0.7345 | val_acc=0.9068
Época 146/200 | train_loss=1.0034 | val_loss=0.7425 | val_acc=0.9136
Época 147/200 | train_loss=0.9993 | val_loss=0.7398 | val_acc=0.9044
Época 148/200 | train_loss=0.9939 | val_loss=0.7277 | val_acc=0.9026
Época 149/200 | train_loss=0.9897 | val_loss=0.7052 | val_acc=0.9122
Época 150/200 | train_loss=0.9686 | val_loss=0.7282 | val_acc=0.9040
Época 151/200 | train_loss=0.9832 | val_loss=0.7065 | val_acc=0.9152
Época 152/200 | train_loss=0.9811 | val_loss=0.6924 | val_acc=0.9168
Época 153/200 | train_loss=0.9486 | val_loss=0.7234 | val_acc=0.9076
Época 154/200 | train_loss=0.9733 | val_loss=0.7055 | val_acc=0.9210
Época 155/200 | train_loss=0.9670 | val_loss=0.6915 | val_acc=0.9294
Época 156/200 | train_loss=0.9769 | val_loss=0.6983 | val_acc=0.9184
Época 157/200 | train_loss=0.9685 | val_loss=0.7027 | val_acc=0.9168
Época 158/200 | train_loss=0.9709 | val_loss=0.7103 | val_acc=0.9224
Época 159/200 | train_loss=0.9387 | val_loss=0.7328 | val_acc=0.9118
Época 160/200 | train_loss=0.9471 | val_loss=0.6817 | val_acc=0.9274
Época 161/200 | train_loss=0.9552 | val_loss=0.6925 | val_acc=0.9274
Época 162/200 | train_loss=0.9351 | val_loss=0.6767 | val_acc=0.9294
Época 163/200 | train_loss=0.9525 | val_loss=0.6986 | val_acc=0.9244
Época 164/200 | train_loss=0.9369 | val_loss=0.6861 | val_acc=0.9312
Época 165/200 | train_loss=0.9270 | val_loss=0.6756 | val_acc=0.9332
Época 166/200 | train_loss=0.9273 | val_loss=0.6794 | val_acc=0.9292
Época 167/200 | train_loss=0.9042 | val_loss=0.6604 | val_acc=0.9366
Época 168/200 | train_loss=0.9169 | val_loss=0.6985 | val_acc=0.9284
Época 169/200 | train_loss=0.9000 | val_loss=0.7074 | val_acc=0.9292
Época 170/200 | train_loss=0.8950 | val_loss=0.6726 | val_acc=0.9338
Época 171/200 | train_loss=0.8873 | val_loss=0.6876 | val_acc=0.9378
Época 172/200 | train_loss=0.8969 | val_loss=0.6839 | val_acc=0.9376
Época 173/200 | train_loss=0.8934 | val_loss=0.6450 | val_acc=0.9402
Época 174/200 | train_loss=0.8778 | val_loss=0.6620 | val_acc=0.9348
Época 175/200 | train_loss=0.8859 | val_loss=0.6764 | val_acc=0.9342
Época 176/200 | train_loss=0.8655 | val_loss=0.6817 | val_acc=0.9432
Época 177/200 | train_loss=0.8655 | val_loss=0.6668 | val_acc=0.9394
Época 178/200 | train_loss=0.8846 | val_loss=0.6386 | val_acc=0.9436
Época 179/200 | train_loss=0.8616 | val_loss=0.6546 | val_acc=0.9440
Época 180/200 | train_loss=0.8662 | val_loss=0.6590 | val_acc=0.9428
Época 181/200 | train_loss=0.8428 | val_loss=0.6367 | val_acc=0.9464
Época 182/200 | train_loss=0.8573 | val_loss=0.6435 | val_acc=0.9474
Época 183/200 | train_loss=0.8418 | val_loss=0.6368 | val_acc=0.9450
Época 184/200 | train_loss=0.8498 | val_loss=0.6549 | val_acc=0.9450
Época 185/200 | train_loss=0.8528 | val_loss=0.6502 | val_acc=0.9492
Época 186/200 | train_loss=0.8325 | val_loss=0.6349 | val_acc=0.9488
Época 187/200 | train_loss=0.8321 | val_loss=0.6404 | val_acc=0.9484
Época 188/200 | train_loss=0.8382 | val_loss=0.6297 | val_acc=0.9518
Época 189/200 | train_loss=0.8231 | val_loss=0.6267 | val_acc=0.9528
Época 190/200 | train_loss=0.8314 | val_loss=0.6354 | val_acc=0.9520
Época 191/200 | train_loss=0.8269 | val_loss=0.6474 | val_acc=0.9524
Época 192/200 | train_loss=0.8181 | val_loss=0.6459 | val_acc=0.9522
Época 193/200 | train_loss=0.8133 | val_loss=0.6151 | val_acc=0.9538
Época 194/200 | train_loss=0.8230 | val_loss=0.6309 | val_acc=0.9550
Época 195/200 | train_loss=0.8150 | val_loss=0.6288 | val_acc=0.9536
Época 196/200 | train_loss=0.8188 | val_loss=0.6391 | val_acc=0.9554
Época 197/200 | train_loss=0.8251 | val_loss=0.6305 | val_acc=0.9546
Época 198/200 | train_loss=0.8125 | val_loss=0.6380 | val_acc=0.9534
Época 199/200 | train_loss=0.8077 | val_loss=0.6176 | val_acc=0.9564
Época 200/200 | train_loss=0.8076 | val_loss=0.6439 | val_acc=0.9560
Métricas no conjunto de teste: {'accuracy': 0.949, 'balanced_accuracy': np.float64(0.9489999999999998), 'precision': 0.948953443711898, 'recall': 0.949, 'f1_score': 0.948968574269674}
Acurácia por classe: {'airplane': 0.957, 'automobile': 0.977, 'bird': 0.942, 'cat': 0.881, 'deer': 0.953, 'dog': 0.91, 'frog': 0.97, 'horse': 0.967, 'ship': 0.968, 'truck': 0.965}
[model-saver] Modelo salvo em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_vgg4_mixcut_aug_ls_20260910-225643/

In [22]:
#@title Tabela comparativa - levas 1..8
comparison8 = pd.DataFrame(
    {name: r["test_scores"] for name, r in experiment_results.items()}
).T.sort_values("accuracy", ascending=False)
comparison8

,accuracy,balanced_accuracy,precision,recall,f1_score
vgg4_mixcut_aug_ls,0.9490,0.9490,0.948953,0.9490,0.948969
vgg4_mixcut_both,0.9469,0.9469,0.946848,0.9469,0.946857
vgg4_mixup,0.9443,0.9443,0.944341,0.9443,0.944293
vgg4_cutmix,0.9429,0.9429,0.943200,0.9429,0.942930
vgg4_randaugment,0.9417,0.9417,0.941777,0.9417,0.941689
vgg4_trivial_aug,0.9411,0.9411,0.941231,0.9411,0.941136
vgg4_reg_combo,0.9407,0.9407,0.940634,0.9407,0.940574
vgg4_label_smooth,0.9389,0.9389,0.938920,0.9389,0.938875
vgg4_wd_higher,0.9370,0.9370,0.937198,0.9370,0.937010
vgg4_dropout,0.9370,0.9370,0.936831,0.9370,0.936809
vgg_4stage_gap_sgd,0.9370,0.9370,0.936852,0.9370,0.936859
vgg_2conv_dropout,0.9284,0.9284,0.928339,0.9284,0.928181
vgg_2conv_sgd,0.9222,0.9222,0.922122,0.9222,0.922028
vgg_2conv_sgd_strong_aug,0.9222,0.9222,0.922122,0.9222,0.922028
vgg_2conv_gap,0.9017,0.9017,0.901705,0.9017,0.901462
vgg_2conv_per_block,0.9007,0.9007,0.901603,0.9007,0.900811
combo_wd_wider,0.8891,0.8891,0.889251,0.8891,0.889094
combo_wd_wider_sgd_long,0.8891,0.8891,0.889251,0.8891,0.889094
combo_wd_long,0.8792,0.8792,0.878581,0.8792,0.878802
combo_wd_wider_fc,0.8776,0.8776,0.877375,0.8776,0.877360
combo_wd_gelu,0.8759,0.8759,0.875921,0.8759,0.875705
combo_wd_sgd,0.8756,0.8756,0.875207,0.8756,0.875211
combo_weight_decay_light,0.8722,0.8722,0.872201,0.8722,0.872163
combo_wd_stronger,0.8659,0.8659,0.865939,0.8659,0.865748
combo_wider_channels,0.8619,0.8619,0.861402,0.8619,0.861191
augment_batchnorm,0.8548,0.8548,0.854965,0.8548,0.854783
augment_batchnorm_deeper_cosine,0.8548,0.8548,0.854965,0.8548,0.854783
augment_batchnorm_deeper,0.8548,0.8548,0.854965,0.8548,0.854783
combo_batch64,0.8534,0.8534,0.853683,0.8534,0.853082
combo_wider_fc,0.8527,0.8527,0.854537,0.8527,0.852820
combo_cosine_long,0.8522,0.8522,0.851832,0.8522,0.851625
combo_lr_high_cosine,0.8516,0.8516,0.851497,0.8516,0.851244
combo_strong_augment,0.8489,0.8489,0.848763,0.8489,0.848695
combo_kernel5,0.8467,0.8467,0.845554,0.8467,0.845617
combo_4conv,0.8460,0.8460,0.849063,0.8460,0.846866
combo_dropout_tiny,0.8351,0.8351,0.833900,0.8351,0.834027
combo_real_norm,0.8347,0.8347,0.836046,0.8347,0.833983
augment_deeper,0.8070,0.8070,0.808046,0.8070,0.805164
augment,0.7871,0.7871,0.786874,0.7871,0.786495
augment_more_epochs,0.7871,0.7871,0.786874,0.7871,0.786495
augment_dropout_light,0.7450,0.7450,0.742617,0.7450,0.740547
deeper_3conv,0.7394,0.7394,0.741505,0.7394,0.738148
batch_norm,0.7336,0.7336,0.734223,0.7336,0.732073
baseline,0.7148,0.7148,0.712927,0.7148,0.712281
lr_low,0.7141,0.7141,0.718704,0.7141,0.712868
dropout_03,0.7130,0.7130,0.709245,0.7130,0.709568
padding_0,0.7119,0.7119,0.716136,0.7119,0.711563
pool_4,0.7117,0.7117,0.722152,0.7117,0.714032
kernel_5,0.7035,0.7035,0.706637,0.7035,0.700650
stride_2_no_pool,0.6430,0.6430,0.656135,0.6430,0.644236
lr_high,0.6175,0.6175,0.629037,0.6175,0.620140

## 14. Ensemble dos modelos já treinados (custo zero de treino)

Sete redes VGG de 4 estágios já estão salvas em `results/`, cada uma treinada
com um regularizador diferente. Elas têm acurácia parecida (0.937-0.9417) mas
**erram imagens diferentes** — cada regularização leva a um mínimo distinto do
espaço de pesos. Quando os erros são parcialmente descorrelacionados, a média
das probabilidades acerta mais do que qualquer membro isolado.

O custo é só um forward pass a mais no teste: nada é retreinado. Por isso
esta é a melhor relação ganho/GPU-hora que sobrou na busca.

Ressalva metodológica: o objetivo declarado do mini-projeto é o **modelo
único**, então o ensemble entra como comparação extra — não substitui o
campeão individual no relatório.

In [23]:
#@title Ensemble por media das probabilidades (soft voting)
from cnn_cifar10.ensemble import ensemble_runs, save_ensemble

# Todos os VGG de 4 estagios ja treinados (levas 6 e 7).
vgg4_runs = [
    "vgg_4stage_gap_sgd", "vgg4_label_smooth", "vgg4_trivial_aug",
    "vgg4_randaugment", "vgg4_dropout", "vgg4_wd_higher", "vgg4_reg_combo",
]

ensemble_all = ensemble_runs(
    run_names=vgg4_runs, results_dir=RESULTS_DIR, data_dir=DATA_DIR,
    device=device, num_workers=NUM_WORKERS,
)
save_ensemble(ensemble_all, run_name="ensemble_vgg4_all", results_dir=RESULTS_DIR,
              notes="Media simples das probabilidades dos 7 VGG-4 estagios das levas 6-7.")

# Variante enxuta: so os 3 melhores. Membros fracos podem puxar a media para
# baixo, entao vale medir se menos modelos rendem mais.
ensemble_top3 = ensemble_runs(
    run_names=["vgg4_randaugment", "vgg4_trivial_aug", "vgg4_reg_combo"],
    results_dir=RESULTS_DIR, data_dir=DATA_DIR, device=device, num_workers=NUM_WORKERS,
)
save_ensemble(ensemble_top3, run_name="ensemble_vgg4_top3", results_dir=RESULTS_DIR,
              notes="Media simples dos 3 melhores VGG-4 estagios.")

pd.DataFrame({
    "ensemble_7_modelos": ensemble_all["test_scores"],
    "ensemble_top3": ensemble_top3["test_scores"],
    "melhor_isolado": {"accuracy": ensemble_all["best_solo_accuracy"]},
}).T

[ensemble] vgg_4stage_gap_sgd       solo=0.9370 (peso 1.0)
[ensemble] vgg4_label_smooth        solo=0.9389 (peso 1.0)
[ensemble] vgg4_trivial_aug         solo=0.9411 (peso 1.0)
[ensemble] vgg4_randaugment         solo=0.9417 (peso 1.0)
[ensemble] vgg4_dropout             solo=0.9370 (peso 1.0)
[ensemble] vgg4_wd_higher           solo=0.9370 (peso 1.0)
[ensemble] vgg4_reg_combo           solo=0.9407 (peso 1.0)
[ensemble] 7 modelos | melhor isolado=0.9417 | ensemble=0.9554 (+0.0137)
[model-saver] Ensemble registrado em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_ensemble_vgg4_all_20260910-225656/
[ensemble] vgg4_randaugment         solo=0.9417 (peso 1.0)
[ensemble] vgg4_trivial_aug         solo=0.9411 (peso 1.0)
[ensemble] vgg4_reg_combo           solo=0.9407 (peso 1.0)
[ensemble] 3 modelos | melhor isolado=0.9417 | ensemble=0.9519 (+0.0102)
[model-saver] Ensemble registrado em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_ensemble_vgg4_top3_20260910-225702/

                    accuracy  balanced_accuracy  precision  recall  f1_score
ensemble_7_modelos    0.9554             0.9554   0.955343  0.9554  0.955341
ensemble_top3         0.9519             0.9519   0.951838  0.9519  0.951821
melhor_isolado        0.9417                NaN        NaN     NaN       NaN

## 15. Experimento: classificação hierárquica (porteiro + especialistas)

A tabela da seção 12 mostra que veículos vão a 0.964 e animais ficam em
0.918. A hipótese: se uma rede não precisasse gastar capacidade separando
gato de caminhão, ela poderia se dedicar inteiramente a separar gato de
cachorro.

Três redes:

1. **`gate`** — 2 classes (veículo vs. animal), treinada em todas as 45.000
   imagens de treino.
2. **`vehicle`** — 4 classes, treinada só nas ~18.000 imagens de veículo.
3. **`animal`** — 6 classes, treinada só nas ~27.000 imagens de animal.

A predição final recompõe as 10 classes pela regra da cadeia,
`P(classe) = P(super) · P(classe | super)`, então o resultado é diretamente
comparável com os modelos achatados.

**Nota sobre o recorte:** o CIFAR-10 tem 6 animais e 4 veículos (não 8 + 2)
— `bird, cat, deer, dog, frog, horse` contra `airplane, automobile, ship,
truck`.

**As duas forças em disputa**, que é o que o experimento vai medir:

- *A favor:* cada especialista resolve um problema mais fácil, com fronteiras
  de decisão menos disputadas.
- *Contra:* cada especialista vê **bem menos dados** (27k / 18k contra 45k), e
  todo erro do porteiro é **irrecuperável** — se ele mandar um gato para o
  especialista em veículos, nenhuma rede depois conserta. O custo também
  triplica: são três treinos em vez de um.

A célula de diagnóstico no fim calcula a acurácia que a composição teria com
um **porteiro perfeito** (oráculo), separando quanto do erro é dos
especialistas e quanto é do porteiro.

In [24]:
#@title Treina as tres redes do experimento hierarquico
from cnn_cifar10.hierarchical import (
    ANIMALS, VEHICLES, SUPER_CLASSES,
    get_hierarchical_dataloaders, flat_test_loader,
    hierarchical_predict, oracle_gate_accuracy,
)
from cnn_cifar10.ensemble import find_run_dir, load_run_model

# Mesma arquitetura/otimizacao do campeao - so muda num_classes. Isso mantem a
# comparacao justa: se a hierarquia ganhar, o ganho vem da decomposicao da
# tarefa, nao de uma rede diferente.
_HIER_BASE = {**_CHAMP, "augment_strength": "randaugment"}  # melhor augmentation da leva 7

hier_configs = {
    "gate":    ExperimentConfig(run_name="hier_gate",    num_classes=2, **_HIER_BASE,
                                notes="Porteiro veiculo vs animal (2 classes), todas as 45k imagens."),
    "vehicle": ExperimentConfig(run_name="hier_vehicle", num_classes=4, **_HIER_BASE,
                                notes="Especialista em veiculos (4 classes), ~18k imagens."),
    "animal":  ExperimentConfig(run_name="hier_animal",  num_classes=6, **_HIER_BASE,
                                notes="Especialista em animais (6 classes), ~27k imagens - onde esta quase todo o erro do modelo achatado."),
}

hier_class_names = {
    "gate": list(SUPER_CLASSES),
    "vehicle": list(VEHICLES),
    "animal": list(ANIMALS),
}

hier_results = {}
for task, config in hier_configs.items():
    set_seed(config.seed)
    loaders = get_hierarchical_dataloaders(
        data_dir=DATA_DIR, batch_size=config.batch_size, val_fraction=config.val_fraction,
        seed=config.seed, num_workers=NUM_WORKERS, augment=config.augment,
        augment_strength=config.augment_strength, normalization=config.normalization,
    )[task]
    print(f"\n=== {task}: {len(loaders['train'].dataset)} treino / "
          f"{len(loaders['val'].dataset)} val / {len(loaders['test'].dataset)} teste ===")
    hier_results[task] = fit_or_load(
        config, loaders["train"], loaders["val"], loaders["test"], device,
        class_names=hier_class_names[task], results_dir=RESULTS_DIR,
    )

pd.DataFrame({t: r["test_scores"] for t, r in hier_results.items()}).T

=== gate: 45000 treino / 5000 val / 10000 teste ===

treinando 'hier_gate':   0%|          | 0/120 [00:00<?, ?it/s]

Época 1/120 | train_loss=0.4025 | val_loss=0.2700 | val_acc=0.8854
Época 2/120 | train_loss=0.3075 | val_loss=0.2382 | val_acc=0.9154
Época 3/120 | train_loss=0.2713 | val_loss=0.1811 | val_acc=0.9278
Época 4/120 | train_loss=0.2542 | val_loss=0.1700 | val_acc=0.9356
Época 5/120 | train_loss=0.2417 | val_loss=0.3452 | val_acc=0.8360
Época 6/120 | train_loss=0.2300 | val_loss=0.1649 | val_acc=0.9362
Época 7/120 | train_loss=0.2263 | val_loss=0.2370 | val_acc=0.9036
Época 8/120 | train_loss=0.2173 | val_loss=0.2386 | val_acc=0.8920
Época 9/120 | train_loss=0.2094 | val_loss=0.1904 | val_acc=0.9152
Época 10/120 | train_loss=0.2056 | val_loss=0.1503 | val_acc=0.9424
Época 11/120 | train_loss=0.2020 | val_loss=0.2612 | val_acc=0.8980
Época 12/120 | train_loss=0.2003 | val_loss=0.1366 | val_acc=0.9472
Época 13/120 | train_loss=0.1960 | val_loss=0.1305 | val_acc=0.9484
Época 14/120 | train_loss=0.1956 | val_loss=0.1289 | val_acc=0.9480
Época 15/120 | train_loss=0.1950 | val_loss=0.1394 | val_acc=0.9422
Época 16/120 | train_loss=0.1910 | val_loss=0.1353 | val_acc=0.9492
Época 17/120 | train_loss=0.1904 | val_loss=0.2054 | val_acc=0.9096
Época 18/120 | train_loss=0.1878 | val_loss=0.1359 | val_acc=0.9448
Época 19/120 | train_loss=0.1894 | val_loss=0.2061 | val_acc=0.9276
Época 20/120 | train_loss=0.1868 | val_loss=0.1267 | val_acc=0.9504
Época 21/120 | train_loss=0.1851 | val_loss=0.1281 | val_acc=0.9476
Época 22/120 | train_loss=0.1857 | val_loss=0.1647 | val_acc=0.9372
Época 23/120 | train_loss=0.1869 | val_loss=0.1059 | val_acc=0.9588
Época 24/120 | train_loss=0.1837 | val_loss=0.1412 | val_acc=0.9420
Época 25/120 | train_loss=0.1835 | val_loss=0.1508 | val_acc=0.9474
Época 26/120 | train_loss=0.1872 | val_loss=0.1179 | val_acc=0.9522
Época 27/120 | train_loss=0.1815 | val_loss=0.1410 | val_acc=0.9458
Época 28/120 | train_loss=0.1762 | val_loss=0.1066 | val_acc=0.9546
Época 29/120 | train_loss=0.1781 | val_loss=0.1146 | val_acc=0.9586
Época 30/120 | train_loss=0.1760 | val_loss=0.1824 | val_acc=0.9364
Época 31/120 | train_loss=0.1742 | val_loss=0.2105 | val_acc=0.9228
Época 32/120 | train_loss=0.1704 | val_loss=0.1220 | val_acc=0.9524
Época 33/120 | train_loss=0.1744 | val_loss=0.1176 | val_acc=0.9520
Época 34/120 | train_loss=0.1723 | val_loss=0.1270 | val_acc=0.9448
Época 35/120 | train_loss=0.1690 | val_loss=0.1663 | val_acc=0.9362
Época 36/120 | train_loss=0.1725 | val_loss=0.1870 | val_acc=0.9322
Época 37/120 | train_loss=0.1702 | val_loss=0.1148 | val_acc=0.9592
Época 38/120 | train_loss=0.1688 | val_loss=0.1275 | val_acc=0.9498
Época 39/120 | train_loss=0.1723 | val_loss=0.1496 | val_acc=0.9448
Época 40/120 | train_loss=0.1653 | val_loss=0.1036 | val_acc=0.9610
Época 41/120 | train_loss=0.1636 | val_loss=0.1105 | val_acc=0.9558
Época 42/120 | train_loss=0.1659 | val_loss=0.1175 | val_acc=0.9548
Época 43/120 | train_loss=0.1661 | val_loss=0.1174 | val_acc=0.9564
Época 44/120 | train_loss=0.1592 | val_loss=0.0955 | val_acc=0.9628
Época 45/120 | train_loss=0.1613 | val_loss=0.1112 | val_acc=0.9586
Época 46/120 | train_loss=0.1612 | val_loss=0.1117 | val_acc=0.9556
Época 47/120 | train_loss=0.1612 | val_loss=0.1007 | val_acc=0.9616
Época 48/120 | train_loss=0.1571 | val_loss=0.1983 | val_acc=0.9236
Época 49/120 | train_loss=0.1592 | val_loss=0.1320 | val_acc=0.9528
Época 50/120 | train_loss=0.1553 | val_loss=0.0853 | val_acc=0.9696
Época 51/120 | train_loss=0.1554 | val_loss=0.1055 | val_acc=0.9576
Época 52/120 | train_loss=0.1507 | val_loss=0.1585 | val_acc=0.9322
Época 53/120 | train_loss=0.1493 | val_loss=0.1461 | val_acc=0.9498
Época 54/120 | train_loss=0.1514 | val_loss=0.1178 | val_acc=0.9524
Época 55/120 | train_loss=0.1489 | val_loss=0.1102 | val_acc=0.9546
Época 56/120 | train_loss=0.1451 | val_loss=0.0833 | val_acc=0.9692
Época 57/120 | train_loss=0.1457 | val_loss=0.0851 | val_acc=0.9644
Época 58/120 | train_loss=0.1419 | val_loss=0.1506 | val_acc=0.9414
Época 59/120 | train_loss=0.1437 | val_loss=0.0926 | val_acc=0.9632
Época 60/120 | train_loss=0.1427 | val_loss=0.0869 | val_acc=0.9670
Época 61/120 | train_loss=0.1402 | val_loss=0.1190 | val_acc=0.9548
Época 62/120 | train_loss=0.1397 | val_loss=0.1046 | val_acc=0.9612
Época 63/120 | train_loss=0.1371 | val_loss=0.0973 | val_acc=0.9590
Época 64/120 | train_loss=0.1369 | val_loss=0.0811 | val_acc=0.9692
Época 65/120 | train_loss=0.1309 | val_loss=0.0907 | val_acc=0.9644
Época 66/120 | train_loss=0.1329 | val_loss=0.1095 | val_acc=0.9600
Época 67/120 | train_loss=0.1322 | val_loss=0.0943 | val_acc=0.9648
Época 68/120 | train_loss=0.1320 | val_loss=0.1002 | val_acc=0.9608
Época 69/120 | train_loss=0.1274 | val_loss=0.1175 | val_acc=0.9514
Época 70/120 | train_loss=0.1261 | val_loss=0.0744 | val_acc=0.9736
Época 71/120 | train_loss=0.1212 | val_loss=0.0944 | val_acc=0.9668
Época 72/120 | train_loss=0.1223 | val_loss=0.1106 | val_acc=0.9572
Época 73/120 | train_loss=0.1206 | val_loss=0.0851 | val_acc=0.9644
Época 74/120 | train_loss=0.1187 | val_loss=0.0816 | val_acc=0.9680
Época 75/120 | train_loss=0.1157 | val_loss=0.0815 | val_acc=0.9682
Época 76/120 | train_loss=0.1147 | val_loss=0.0908 | val_acc=0.9672
Época 77/120 | train_loss=0.1149 | val_loss=0.0844 | val_acc=0.9690
Época 78/120 | train_loss=0.1103 | val_loss=0.0718 | val_acc=0.9742
Época 79/120 | train_loss=0.1075 | val_loss=0.1227 | val_acc=0.9532
Época 80/120 | train_loss=0.1092 | val_loss=0.0657 | val_acc=0.9746
Época 81/120 | train_loss=0.1063 | val_loss=0.0676 | val_acc=0.9760
Época 82/120 | train_loss=0.1034 | val_loss=0.0897 | val_acc=0.9658
Época 83/120 | train_loss=0.1034 | val_loss=0.1053 | val_acc=0.9578
Época 84/120 | train_loss=0.0982 | val_loss=0.0631 | val_acc=0.9768
Época 85/120 | train_loss=0.0983 | val_loss=0.0835 | val_acc=0.9664
Época 86/120 | train_loss=0.0953 | val_loss=0.0664 | val_acc=0.9734
Época 87/120 | train_loss=0.0914 | val_loss=0.0690 | val_acc=0.9758
Época 88/120 | train_loss=0.0889 | val_loss=0.0639 | val_acc=0.9780
Época 89/120 | train_loss=0.0887 | val_loss=0.0792 | val_acc=0.9684
Época 90/120 | train_loss=0.0880 | val_loss=0.0626 | val_acc=0.9788
Época 91/120 | train_loss=0.0849 | val_loss=0.0567 | val_acc=0.9808
Época 92/120 | train_loss=0.0784 | val_loss=0.0534 | val_acc=0.9802
Época 93/120 | train_loss=0.0796 | val_loss=0.0528 | val_acc=0.9804
Época 94/120 | train_loss=0.0768 | val_loss=0.0549 | val_acc=0.9800
Época 95/120 | train_loss=0.0740 | val_loss=0.0598 | val_acc=0.9764
Época 96/120 | train_loss=0.0709 | val_loss=0.0495 | val_acc=0.9812
Época 97/120 | train_loss=0.0675 | val_loss=0.0535 | val_acc=0.9780
Época 98/120 | train_loss=0.0636 | val_loss=0.0554 | val_acc=0.9800
Época 99/120 | train_loss=0.0614 | val_loss=0.0472 | val_acc=0.9822
Época 100/120 | train_loss=0.0614 | val_loss=0.0473 | val_acc=0.9822
Época 101/120 | train_loss=0.0565 | val_loss=0.0502 | val_acc=0.9814
Época 102/120 | train_loss=0.0561 | val_loss=0.0432 | val_acc=0.9846
Época 103/120 | train_loss=0.0534 | val_loss=0.0449 | val_acc=0.9818
Época 104/120 | train_loss=0.0495 | val_loss=0.0414 | val_acc=0.9846
Época 105/120 | train_loss=0.0495 | val_loss=0.0381 | val_acc=0.9856
Época 106/120 | train_loss=0.0430 | val_loss=0.0438 | val_acc=0.9828
Época 107/120 | train_loss=0.0428 | val_loss=0.0394 | val_acc=0.9860
Época 108/120 | train_loss=0.0394 | val_loss=0.0365 | val_acc=0.9860
Época 109/120 | train_loss=0.0362 | val_loss=0.0380 | val_acc=0.9860
Época 110/120 | train_loss=0.0339 | val_loss=0.0372 | val_acc=0.9868
Época 111/120 | train_loss=0.0319 | val_loss=0.0391 | val_acc=0.9878
Época 112/120 | train_loss=0.0295 | val_loss=0.0340 | val_acc=0.9876
Época 113/120 | train_loss=0.0290 | val_loss=0.0347 | val_acc=0.9880
Época 114/120 | train_loss=0.0274 | val_loss=0.0368 | val_acc=0.9882
Época 115/120 | train_loss=0.0274 | val_loss=0.0350 | val_acc=0.9892
Época 116/120 | train_loss=0.0263 | val_loss=0.0343 | val_acc=0.9874
Época 117/120 | train_loss=0.0252 | val_loss=0.0359 | val_acc=0.9886
Época 118/120 | train_loss=0.0240 | val_loss=0.0359 | val_acc=0.9884
Época 119/120 | train_loss=0.0255 | val_loss=0.0348 | val_acc=0.9886
Época 120/120 | train_loss=0.0238 | val_loss=0.0338 | val_acc=0.9880
Métricas no conjunto de teste: {'accuracy': 0.9875, 'balanced_accuracy': np.float64(0.9870833333333333), 'precision': 0.9875031106862876, 'recall': 0.9875, 'f1_score': 0.9875012985579302}
Acurácia por classe: {'vehicle': 0.985, 'animal': 0.9891666666666666}
[model-saver] Modelo salvo em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_hier_gate_20260910-234642/

=== vehicle: 17995 treino / 2005 val / 4000 teste ===

treinando 'hier_vehicle':   0%|          | 0/120 [00:00<?, ?it/s]

Época 1/120 | train_loss=1.2445 | val_loss=1.0580 | val_acc=0.4160
Época 2/120 | train_loss=1.1124 | val_loss=1.0407 | val_acc=0.4434
Época 3/120 | train_loss=0.9966 | val_loss=0.8779 | val_acc=0.6633
Época 4/120 | train_loss=0.7860 | val_loss=0.5845 | val_acc=0.7855
Época 5/120 | train_loss=0.6153 | val_loss=0.4818 | val_acc=0.8314
Época 6/120 | train_loss=0.5285 | val_loss=0.3395 | val_acc=0.8883
Época 7/120 | train_loss=0.4821 | val_loss=0.3469 | val_acc=0.8763
Época 8/120 | train_loss=0.4350 | val_loss=0.2940 | val_acc=0.8888
Época 9/120 | train_loss=0.4135 | val_loss=0.3242 | val_acc=0.8793
Época 10/120 | train_loss=0.4044 | val_loss=0.2818 | val_acc=0.8988
Época 11/120 | train_loss=0.3894 | val_loss=0.2590 | val_acc=0.9107
Época 12/120 | train_loss=0.3860 | val_loss=0.3084 | val_acc=0.8843
Época 13/120 | train_loss=0.3749 | val_loss=0.2955 | val_acc=0.8913
Época 14/120 | train_loss=0.3633 | val_loss=0.2943 | val_acc=0.8918
Época 15/120 | train_loss=0.3575 | val_loss=0.5677 | val_acc=0.8269
Época 16/120 | train_loss=0.3554 | val_loss=0.2916 | val_acc=0.8928
Época 17/120 | train_loss=0.3561 | val_loss=0.2578 | val_acc=0.9067
Época 18/120 | train_loss=0.3444 | val_loss=0.2538 | val_acc=0.9147
Época 19/120 | train_loss=0.3424 | val_loss=0.3847 | val_acc=0.8544
Época 20/120 | train_loss=0.3378 | val_loss=0.2781 | val_acc=0.8948
Época 21/120 | train_loss=0.3268 | val_loss=0.4902 | val_acc=0.8309
Época 22/120 | train_loss=0.3368 | val_loss=0.3010 | val_acc=0.8998
Época 23/120 | train_loss=0.3295 | val_loss=0.3039 | val_acc=0.8878
Época 24/120 | train_loss=0.3160 | val_loss=0.2035 | val_acc=0.9232
Época 25/120 | train_loss=0.3161 | val_loss=0.3888 | val_acc=0.8653
Época 26/120 | train_loss=0.3189 | val_loss=0.2595 | val_acc=0.9067
Época 27/120 | train_loss=0.3155 | val_loss=0.2130 | val_acc=0.9227
Época 28/120 | train_loss=0.3136 | val_loss=0.2226 | val_acc=0.9192
Época 29/120 | train_loss=0.3056 | val_loss=0.2709 | val_acc=0.9057
Época 30/120 | train_loss=0.3025 | val_loss=0.2278 | val_acc=0.9137
Época 31/120 | train_loss=0.3006 | val_loss=0.2421 | val_acc=0.9147
Época 32/120 | train_loss=0.2987 | val_loss=0.2593 | val_acc=0.9077
Época 33/120 | train_loss=0.2886 | val_loss=0.2602 | val_acc=0.9057
Época 34/120 | train_loss=0.2941 | val_loss=0.2484 | val_acc=0.9177
Época 35/120 | train_loss=0.2823 | val_loss=0.2313 | val_acc=0.9162
Época 36/120 | train_loss=0.2882 | val_loss=0.2769 | val_acc=0.8928
Época 37/120 | train_loss=0.2859 | val_loss=0.1802 | val_acc=0.9372
Época 38/120 | train_loss=0.2799 | val_loss=0.2771 | val_acc=0.9032
Época 39/120 | train_loss=0.2813 | val_loss=0.2843 | val_acc=0.8973
Época 40/120 | train_loss=0.2795 | val_loss=0.1896 | val_acc=0.9317
Época 41/120 | train_loss=0.2715 | val_loss=0.2377 | val_acc=0.9182
Época 42/120 | train_loss=0.2696 | val_loss=0.2774 | val_acc=0.9037
Época 43/120 | train_loss=0.2704 | val_loss=0.2164 | val_acc=0.9247
Época 44/120 | train_loss=0.2679 | val_loss=0.2322 | val_acc=0.9267
Época 45/120 | train_loss=0.2607 | val_loss=0.2159 | val_acc=0.9257
Época 46/120 | train_loss=0.2588 | val_loss=0.1904 | val_acc=0.9297
Época 47/120 | train_loss=0.2532 | val_loss=0.2143 | val_acc=0.9192
Época 48/120 | train_loss=0.2428 | val_loss=0.2557 | val_acc=0.9137
Época 49/120 | train_loss=0.2547 | val_loss=0.2034 | val_acc=0.9277
Época 50/120 | train_loss=0.2467 | val_loss=0.2318 | val_acc=0.9117
Época 51/120 | train_loss=0.2390 | val_loss=0.1522 | val_acc=0.9431
Época 52/120 | train_loss=0.2296 | val_loss=0.2138 | val_acc=0.9277
Época 53/120 | train_loss=0.2317 | val_loss=0.2642 | val_acc=0.9072
Época 54/120 | train_loss=0.2360 | val_loss=0.2678 | val_acc=0.9157
Época 55/120 | train_loss=0.2300 | val_loss=0.1440 | val_acc=0.9491
Época 56/120 | train_loss=0.2307 | val_loss=0.1898 | val_acc=0.9416
Época 57/120 | train_loss=0.2198 | val_loss=0.2080 | val_acc=0.9237
Época 58/120 | train_loss=0.2169 | val_loss=0.2267 | val_acc=0.9267
Época 59/120 | train_loss=0.2202 | val_loss=0.1565 | val_acc=0.9471
Época 60/120 | train_loss=0.2187 | val_loss=0.2062 | val_acc=0.9337
Época 61/120 | train_loss=0.2027 | val_loss=0.2245 | val_acc=0.9262
Época 62/120 | train_loss=0.2057 | val_loss=0.1560 | val_acc=0.9466
Época 63/120 | train_loss=0.2017 | val_loss=0.1678 | val_acc=0.9372
Época 64/120 | train_loss=0.1964 | val_loss=0.1565 | val_acc=0.9436
Época 65/120 | train_loss=0.2005 | val_loss=0.1550 | val_acc=0.9441
Época 66/120 | train_loss=0.1939 | val_loss=0.3231 | val_acc=0.8958
Época 67/120 | train_loss=0.1931 | val_loss=0.1418 | val_acc=0.9511
Época 68/120 | train_loss=0.1885 | val_loss=0.1582 | val_acc=0.9431
Época 69/120 | train_loss=0.1801 | val_loss=0.1058 | val_acc=0.9601
Época 70/120 | train_loss=0.1762 | val_loss=0.1673 | val_acc=0.9466
Época 71/120 | train_loss=0.1753 | val_loss=0.1387 | val_acc=0.9491
Época 72/120 | train_loss=0.1738 | val_loss=0.1299 | val_acc=0.9591
Época 73/120 | train_loss=0.1640 | val_loss=0.1564 | val_acc=0.9456
Época 74/120 | train_loss=0.1631 | val_loss=0.1409 | val_acc=0.9481
Época 75/120 | train_loss=0.1606 | val_loss=0.1196 | val_acc=0.9606
Época 76/120 | train_loss=0.1509 | val_loss=0.1359 | val_acc=0.9546
Época 77/120 | train_loss=0.1483 | val_loss=0.1279 | val_acc=0.9551
Época 78/120 | train_loss=0.1471 | val_loss=0.0972 | val_acc=0.9616
Época 79/120 | train_loss=0.1403 | val_loss=0.1257 | val_acc=0.9576
Época 80/120 | train_loss=0.1417 | val_loss=0.1108 | val_acc=0.9621
Época 81/120 | train_loss=0.1337 | val_loss=0.1132 | val_acc=0.9586
Época 82/120 | train_loss=0.1235 | val_loss=0.1121 | val_acc=0.9636
Época 83/120 | train_loss=0.1270 | val_loss=0.1217 | val_acc=0.9581
Época 84/120 | train_loss=0.1271 | val_loss=0.1002 | val_acc=0.9666
Época 85/120 | train_loss=0.1165 | val_loss=0.1664 | val_acc=0.9456
Época 86/120 | train_loss=0.1174 | val_loss=0.0957 | val_acc=0.9656
Época 87/120 | train_loss=0.1108 | val_loss=0.0907 | val_acc=0.9671
Época 88/120 | train_loss=0.1065 | val_loss=0.0956 | val_acc=0.9661
Época 89/120 | train_loss=0.0951 | val_loss=0.1192 | val_acc=0.9591
Época 90/120 | train_loss=0.0977 | val_loss=0.0962 | val_acc=0.9651
Época 91/120 | train_loss=0.0955 | val_loss=0.1017 | val_acc=0.9661
Época 92/120 | train_loss=0.0844 | val_loss=0.1057 | val_acc=0.9696
Época 93/120 | train_loss=0.0848 | val_loss=0.0994 | val_acc=0.9681
Época 94/120 | train_loss=0.0790 | val_loss=0.1037 | val_acc=0.9651
Época 95/120 | train_loss=0.0734 | val_loss=0.0913 | val_acc=0.9706
Época 96/120 | train_loss=0.0706 | val_loss=0.0903 | val_acc=0.9691
Época 97/120 | train_loss=0.0653 | val_loss=0.0772 | val_acc=0.9756
Época 98/120 | train_loss=0.0650 | val_loss=0.0822 | val_acc=0.9731
Época 99/120 | train_loss=0.0595 | val_loss=0.0913 | val_acc=0.9716
Época 100/120 | train_loss=0.0572 | val_loss=0.0980 | val_acc=0.9701
Época 101/120 | train_loss=0.0510 | val_loss=0.0915 | val_acc=0.9686
Época 102/120 | train_loss=0.0535 | val_loss=0.0782 | val_acc=0.9716
Época 103/120 | train_loss=0.0475 | val_loss=0.0820 | val_acc=0.9696
Época 104/120 | train_loss=0.0439 | val_loss=0.0885 | val_acc=0.9721
Época 105/120 | train_loss=0.0371 | val_loss=0.0879 | val_acc=0.9711
Época 106/120 | train_loss=0.0392 | val_loss=0.0753 | val_acc=0.9751
Época 107/120 | train_loss=0.0379 | val_loss=0.0747 | val_acc=0.9746
Época 108/120 | train_loss=0.0342 | val_loss=0.0755 | val_acc=0.9761
Época 109/120 | train_loss=0.0345 | val_loss=0.0750 | val_acc=0.9751
Época 110/120 | train_loss=0.0324 | val_loss=0.0788 | val_acc=0.9746
Época 111/120 | train_loss=0.0288 | val_loss=0.0700 | val_acc=0.9786
Época 112/120 | train_loss=0.0285 | val_loss=0.0733 | val_acc=0.9766
Época 113/120 | train_loss=0.0241 | val_loss=0.0714 | val_acc=0.9766
Época 114/120 | train_loss=0.0249 | val_loss=0.0765 | val_acc=0.9751
Época 115/120 | train_loss=0.0270 | val_loss=0.0735 | val_acc=0.9766
Época 116/120 | train_loss=0.0232 | val_loss=0.0733 | val_acc=0.9741
Época 117/120 | train_loss=0.0273 | val_loss=0.0713 | val_acc=0.9766
Época 118/120 | train_loss=0.0269 | val_loss=0.0718 | val_acc=0.9771
Época 119/120 | train_loss=0.0242 | val_loss=0.0742 | val_acc=0.9756
Época 120/120 | train_loss=0.0239 | val_loss=0.0687 | val_acc=0.9771
Métricas no conjunto de teste: {'accuracy': 0.97175, 'balanced_accuracy': np.float64(0.97175), 'precision': 0.9717499748945237, 'recall': 0.97175, 'f1_score': 0.9717476839446324}
Acurácia por classe: {'airplane': 0.973, 'automobile': 0.976, 'ship': 0.971, 'truck': 0.967}
[model-saver] Modelo salvo em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_hier_vehicle_20260911-000655/

=== animal: 27005 treino / 2995 val / 6000 teste ===

treinando 'hier_animal':   0%|          | 0/120 [00:00<?, ?it/s]

Época 1/120 | train_loss=1.7931 | val_loss=1.7993 | val_acc=0.1573
Época 2/120 | train_loss=1.7948 | val_loss=1.8004 | val_acc=0.1573
Época 3/120 | train_loss=1.7951 | val_loss=1.7934 | val_acc=0.1573
Época 4/120 | train_loss=1.7951 | val_loss=1.7918 | val_acc=0.1776
Época 5/120 | train_loss=1.7950 | val_loss=1.7938 | val_acc=0.1716
Época 6/120 | train_loss=1.7948 | val_loss=1.7947 | val_acc=0.1693
Época 7/120 | train_loss=1.7953 | val_loss=1.7958 | val_acc=0.1573
Época 8/120 | train_loss=1.7950 | val_loss=1.7522 | val_acc=0.2053
Época 9/120 | train_loss=1.7425 | val_loss=1.6880 | val_acc=0.2641
Época 10/120 | train_loss=1.6846 | val_loss=1.6300 | val_acc=0.3152
Época 11/120 | train_loss=1.4908 | val_loss=1.3708 | val_acc=0.4621
Época 12/120 | train_loss=1.3367 | val_loss=1.1621 | val_acc=0.5492
Época 13/120 | train_loss=1.2219 | val_loss=1.2328 | val_acc=0.5262
Época 14/120 | train_loss=1.1213 | val_loss=1.1110 | val_acc=0.5863
Época 15/120 | train_loss=1.0287 | val_loss=0.8500 | val_acc=0.6865
Época 16/120 | train_loss=0.9619 | val_loss=1.1025 | val_acc=0.6234
Época 17/120 | train_loss=0.9229 | val_loss=1.0086 | val_acc=0.6514
Época 18/120 | train_loss=0.8902 | val_loss=0.7605 | val_acc=0.7245
Época 19/120 | train_loss=0.8551 | val_loss=0.9220 | val_acc=0.6474
Época 20/120 | train_loss=0.8381 | val_loss=0.8474 | val_acc=0.7005
Época 21/120 | train_loss=0.8207 | val_loss=0.8380 | val_acc=0.6965
Época 22/120 | train_loss=0.7963 | val_loss=0.8379 | val_acc=0.6988
Época 23/120 | train_loss=0.7850 | val_loss=0.7422 | val_acc=0.7396
Época 24/120 | train_loss=0.7601 | val_loss=0.7955 | val_acc=0.7199
Época 25/120 | train_loss=0.7548 | val_loss=0.7793 | val_acc=0.7245
Época 26/120 | train_loss=0.7558 | val_loss=0.6521 | val_acc=0.7656
Época 27/120 | train_loss=0.7275 | val_loss=0.7117 | val_acc=0.7529
Época 28/120 | train_loss=0.7166 | val_loss=0.6523 | val_acc=0.7589
Época 29/120 | train_loss=0.7088 | val_loss=0.6804 | val_acc=0.7633
Época 30/120 | train_loss=0.7010 | val_loss=0.5744 | val_acc=0.7907
Época 31/120 | train_loss=0.6828 | val_loss=0.7107 | val_acc=0.7643
Época 32/120 | train_loss=0.6865 | val_loss=0.7640 | val_acc=0.7306
Época 33/120 | train_loss=0.6796 | val_loss=0.6479 | val_acc=0.7716
Época 34/120 | train_loss=0.6670 | val_loss=0.8918 | val_acc=0.7048
Época 35/120 | train_loss=0.6601 | val_loss=0.7226 | val_acc=0.7619
Época 36/120 | train_loss=0.6505 | val_loss=0.7395 | val_acc=0.7516
Época 37/120 | train_loss=0.6345 | val_loss=0.6064 | val_acc=0.7920
Época 38/120 | train_loss=0.6331 | val_loss=0.8276 | val_acc=0.7265
Época 39/120 | train_loss=0.6370 | val_loss=0.5730 | val_acc=0.8080
Época 40/120 | train_loss=0.6179 | val_loss=0.5024 | val_acc=0.8207
Época 41/120 | train_loss=0.6128 | val_loss=0.5366 | val_acc=0.8150
Época 42/120 | train_loss=0.6028 | val_loss=0.5741 | val_acc=0.7993
Época 43/120 | train_loss=0.5986 | val_loss=0.5736 | val_acc=0.7957
Época 44/120 | train_loss=0.5968 | val_loss=0.4527 | val_acc=0.8407
Época 45/120 | train_loss=0.5895 | val_loss=0.7193 | val_acc=0.7629
Época 46/120 | train_loss=0.5817 | val_loss=0.4727 | val_acc=0.8327
Época 47/120 | train_loss=0.5765 | val_loss=0.4988 | val_acc=0.8214
Época 48/120 | train_loss=0.5699 | val_loss=0.4777 | val_acc=0.8327
Época 49/120 | train_loss=0.5608 | val_loss=0.5083 | val_acc=0.8197
Época 50/120 | train_loss=0.5666 | val_loss=0.4798 | val_acc=0.8314
Época 51/120 | train_loss=0.5476 | val_loss=0.5043 | val_acc=0.8244
Época 52/120 | train_loss=0.5523 | val_loss=0.5843 | val_acc=0.7913
Época 53/120 | train_loss=0.5354 | val_loss=0.4884 | val_acc=0.8321
Época 54/120 | train_loss=0.5306 | val_loss=0.4881 | val_acc=0.8234
Época 55/120 | train_loss=0.5282 | val_loss=0.4548 | val_acc=0.8341
Época 56/120 | train_loss=0.5268 | val_loss=0.4772 | val_acc=0.8351
Época 57/120 | train_loss=0.5094 | val_loss=0.4315 | val_acc=0.8477
Época 58/120 | train_loss=0.5075 | val_loss=0.4971 | val_acc=0.8280
Época 59/120 | train_loss=0.4996 | val_loss=0.5034 | val_acc=0.8200
Época 60/120 | train_loss=0.4961 | val_loss=0.4492 | val_acc=0.8447
Época 61/120 | train_loss=0.4912 | val_loss=0.4537 | val_acc=0.8494
Época 62/120 | train_loss=0.4809 | val_loss=0.4074 | val_acc=0.8591
Época 63/120 | train_loss=0.4707 | val_loss=0.5142 | val_acc=0.8200
Época 64/120 | train_loss=0.4702 | val_loss=0.4588 | val_acc=0.8374
Época 65/120 | train_loss=0.4614 | val_loss=0.4569 | val_acc=0.8421
Época 66/120 | train_loss=0.4571 | val_loss=0.4485 | val_acc=0.8491
Época 67/120 | train_loss=0.4431 | val_loss=0.3583 | val_acc=0.8751
Época 68/120 | train_loss=0.4349 | val_loss=0.4028 | val_acc=0.8534
Época 69/120 | train_loss=0.4286 | val_loss=0.3816 | val_acc=0.8651
Época 70/120 | train_loss=0.4235 | val_loss=0.6273 | val_acc=0.8080
Época 71/120 | train_loss=0.4183 | val_loss=0.3930 | val_acc=0.8688
Época 72/120 | train_loss=0.4124 | val_loss=0.3951 | val_acc=0.8628
Época 73/120 | train_loss=0.3963 | val_loss=0.3912 | val_acc=0.8598
Época 74/120 | train_loss=0.3952 | val_loss=0.3955 | val_acc=0.8614
Época 75/120 | train_loss=0.3883 | val_loss=0.4888 | val_acc=0.8294
Época 76/120 | train_loss=0.3766 | val_loss=0.3688 | val_acc=0.8735
Época 77/120 | train_loss=0.3748 | val_loss=0.3793 | val_acc=0.8654
Época 78/120 | train_loss=0.3644 | val_loss=0.3250 | val_acc=0.8815
Época 79/120 | train_loss=0.3510 | val_loss=0.3502 | val_acc=0.8815
Época 80/120 | train_loss=0.3447 | val_loss=0.3621 | val_acc=0.8755
Época 81/120 | train_loss=0.3397 | val_loss=0.3576 | val_acc=0.8748
Época 82/120 | train_loss=0.3299 | val_loss=0.3383 | val_acc=0.8758
Época 83/120 | train_loss=0.3262 | val_loss=0.3850 | val_acc=0.8701
Época 84/120 | train_loss=0.3148 | val_loss=0.3503 | val_acc=0.8741
Época 85/120 | train_loss=0.3000 | val_loss=0.2998 | val_acc=0.9008
Época 86/120 | train_loss=0.2947 | val_loss=0.3283 | val_acc=0.8851
Época 87/120 | train_loss=0.2793 | val_loss=0.3325 | val_acc=0.8878
Época 88/120 | train_loss=0.2829 | val_loss=0.2930 | val_acc=0.8972
Época 89/120 | train_loss=0.2673 | val_loss=0.3304 | val_acc=0.8888
Época 90/120 | train_loss=0.2530 | val_loss=0.2932 | val_acc=0.8948
Época 91/120 | train_loss=0.2490 | val_loss=0.2698 | val_acc=0.9088
Época 92/120 | train_loss=0.2372 | val_loss=0.2747 | val_acc=0.9109
Época 93/120 | train_loss=0.2273 | val_loss=0.2829 | val_acc=0.9005
Época 94/120 | train_loss=0.2244 | val_loss=0.2873 | val_acc=0.9032
Época 95/120 | train_loss=0.2193 | val_loss=0.2808 | val_acc=0.9045
Época 96/120 | train_loss=0.2047 | val_loss=0.2681 | val_acc=0.9062
Época 97/120 | train_loss=0.1909 | val_loss=0.2552 | val_acc=0.9145
Época 98/120 | train_loss=0.1827 | val_loss=0.2564 | val_acc=0.9165
Época 99/120 | train_loss=0.1759 | val_loss=0.2684 | val_acc=0.9159
Época 100/120 | train_loss=0.1677 | val_loss=0.2615 | val_acc=0.9145
Época 101/120 | train_loss=0.1539 | val_loss=0.2476 | val_acc=0.9182
Época 102/120 | train_loss=0.1470 | val_loss=0.2551 | val_acc=0.9155
Época 103/120 | train_loss=0.1429 | val_loss=0.2470 | val_acc=0.9192
Época 104/120 | train_loss=0.1250 | val_loss=0.2499 | val_acc=0.9195
Época 105/120 | train_loss=0.1220 | val_loss=0.2504 | val_acc=0.9262
Época 106/120 | train_loss=0.1178 | val_loss=0.2474 | val_acc=0.9219
Época 107/120 | train_loss=0.1081 | val_loss=0.2395 | val_acc=0.9215
Época 108/120 | train_loss=0.0961 | val_loss=0.2540 | val_acc=0.9209
Época 109/120 | train_loss=0.0938 | val_loss=0.2483 | val_acc=0.9229
Época 110/120 | train_loss=0.0899 | val_loss=0.2374 | val_acc=0.9269
Época 111/120 | train_loss=0.0873 | val_loss=0.2450 | val_acc=0.9232
Época 112/120 | train_loss=0.0797 | val_loss=0.2444 | val_acc=0.9285
Época 113/120 | train_loss=0.0739 | val_loss=0.2387 | val_acc=0.9292
Época 114/120 | train_loss=0.0740 | val_loss=0.2390 | val_acc=0.9312
Época 115/120 | train_loss=0.0715 | val_loss=0.2353 | val_acc=0.9316
Época 116/120 | train_loss=0.0713 | val_loss=0.2334 | val_acc=0.9319
Época 117/120 | train_loss=0.0716 | val_loss=0.2347 | val_acc=0.9299
Época 118/120 | train_loss=0.0675 | val_loss=0.2314 | val_acc=0.9322
Época 119/120 | train_loss=0.0686 | val_loss=0.2308 | val_acc=0.9316
Época 120/120 | train_loss=0.0660 | val_loss=0.2341 | val_acc=0.9309
Métricas no conjunto de teste: {'accuracy': 0.9298333333333333, 'balanced_accuracy': np.float64(0.9298333333333333), 'precision': 0.9297427282574965, 'recall': 0.9298333333333333, 'f1_score': 0.9297584514437466}
Acurácia por classe: {'bird': 0.937, 'cat': 0.866, 'deer': 0.961, 'dog': 0.896, 'frog': 0.956, 'horse': 0.963}
[model-saver] Modelo salvo em /kaggle/working/redes-neurais/miniprojeto/fase2-cnn/results/cnn_hier_animal_20260911-003712/

         accuracy  balanced_accuracy  precision    recall  f1_score
gate     0.987500           0.987083   0.987503  0.987500  0.987501
vehicle  0.971750           0.971750   0.971750  0.971750  0.971748
animal   0.929833           0.929833   0.929743  0.929833  0.929758

In [25]:
#@title Compoe as tres redes e compara com o modelo achatado
# fit_or_load pode ter reaproveitado runs do disco (model=None), entao os pesos
# sao recarregados a partir de results/ - assim a celula funciona tanto logo
# apos treinar quanto numa sessao nova.
_NUM_CLASSES = {"gate": 2, "vehicle": 4, "animal": 6}
hier_models = {
    task: load_run_model(find_run_dir(f"hier_{task}", RESULTS_DIR), device, num_classes=n)[0]
    for task, n in _NUM_CLASSES.items()
}

hier_combined = hierarchical_predict(
    hier_models["gate"], hier_models["vehicle"], hier_models["animal"],
    flat_test_loader(data_dir=DATA_DIR, batch_size=256, num_workers=NUM_WORKERS),
    device,
)

flat_best = max(
    (r["test_scores"]["accuracy"] for r in experiment_results.values()),
    default=float("nan"),
)

print(f"Porteiro (veiculo vs animal): {hier_combined['gate_accuracy']:.4f}")
print(f"Hierarquico composto (10 classes): {hier_combined['test_scores']['accuracy']:.4f}")
print(f"Melhor modelo achatado ate agora:  {flat_best:.4f}")
print(f"Com porteiro perfeito (oraculo):   {oracle_gate_accuracy(hier_combined):.4f}")

pd.DataFrame({
    "hierarquico": hier_combined["per_class_accuracy"],
    "melhor_achatado": experiment_results[
        max(experiment_results, key=lambda k: experiment_results[k]["test_scores"]["accuracy"])
    ]["per_class_accuracy"],
})

Porteiro (veiculo vs animal): 0.9875
Hierarquico composto (10 classes): 0.9360
Melhor modelo achatado ate agora:  0.9490
Com porteiro perfeito (oraculo):   0.9466

            hierarquico  melhor_achatado
airplane          0.941            0.957
automobile        0.972            0.977
bird              0.920            0.942
cat               0.850            0.881
deer              0.953            0.953
dog               0.893            0.910
frog              0.950            0.970
horse             0.955            0.967
ship              0.963            0.968
truck             0.963            0.965

## 16. Próximas rodadas

O que fazer depois depende de qual das três frentes acima moveu a agulha:

- **Se MixUp/CutMix (leva 8) ganhou**, o teto era mesmo de regularização:
  vale esticar para 300 épocas e testar `mixup_alpha=0.4`.
- **Se o ensemble ganhou bem mais que qualquer modelo isolado**, os erros são
  descorrelacionados e a diversidade compensa: treinar 3 modelos com seeds
  diferentes (não regularizadores diferentes) e ensemblar costuma render mais.
- **Se o hierárquico ganhou**, o caminho é aprofundar a decomposição
  (por exemplo, um terceiro nível só para `cat` vs `dog`).
- **Se nada ganhou**, o platô de ~0.94 é da família VGG simples. Passar disso
  pede conexões residuais (ResNet) ou treino muito mais longo com
  augmentation pesada — mudança de arquitetura, não de hiperparâmetro.

Alavancas de arquitetura ainda não exploradas: `conv_layers_per_block=3`,
bloco final `1x1` para misturar canais, ou `pool_size` só nos primeiros
estágios. Se as células ficarem grandes/lentas demais, mova para um
`scripts/run_experiments.py` (ver `../fase1-mlp/scripts/run_experiments.py`).

In [26]:
#@title Comparar todas as execuções salvas
df = load_all_metadata(RESULTS_DIR)
if not df.empty:
    cols = [c for c in ["run_name", "metrics.test_accuracy", "metrics.test_f1_score", "metrics.epochs_trained"] if c in df.columns]
    display(df[cols].sort_values("metrics.test_accuracy", ascending=False) if cols else df)
else:
    print("Nenhuma execucao salva ainda em", RESULTS_DIR)

,run_name,metrics.test_accuracy,metrics.test_f1_score,metrics.epochs_trained
32,hier_gate,0.987500,0.987501,120
33,hier_vehicle,0.971750,0.971748,120
29,ensemble_vgg4_all,0.955400,0.955341,0
30,ensemble_vgg4_top3,0.951900,0.951821,0
43,vgg4_mixcut_aug_ls,0.949000,0.948969,200
44,vgg4_mixcut_both,0.946900,0.946857,200
45,vgg4_mixup,0.944300,0.944293,200
40,vgg4_cutmix,0.942900,0.942930,200
46,vgg4_randaugment,0.941700,0.941689,120
48,vgg4_trivial_aug,0.941100,0.941136,120
47,vgg4_reg_combo,0.940700,0.940574,120
42,vgg4_label_smooth,0.938900,0.938875,120
55,vgg_4stage_gap_sgd,0.937000,0.936859,120
41,vgg4_dropout,0.937000,0.936809,120
49,vgg4_wd_higher,0.937000,0.937010,120
53,vgg_2conv_sgd,0.933200,0.933170,120
31,hier_animal,0.929833,0.929758,120
50,vgg_2conv_dropout,0.928400,0.928181,120
54,vgg_2conv_sgd_strong_aug,0.922200,0.922028,120
51,vgg_2conv_gap,0.901700,0.901462,99
52,vgg_2conv_per_block,0.900700,0.900811,87
23,combo_wd_wider_sgd_long,0.889100,0.889094,120
21,combo_wd_wider,0.886400,0.886175,100
18,combo_wd_long,0.879200,0.878802,100
22,combo_wd_wider_fc,0.877600,0.877360,80
17,combo_wd_gelu,0.875900,0.875705,80
19,combo_wd_sgd,0.875600,0.875211,100
24,combo_weight_decay_light,0.872200,0.872163,60
20,combo_wd_stronger,0.865900,0.865748,80
25,combo_wider_channels,0.861900,0.861191,36
3,augment_batchnorm_deeper_cosine,0.854800,0.854783,60
10,combo_batch64,0.853400,0.853082,55
26,combo_wider_fc,0.852700,0.852820,58
11,combo_cosine_long,0.852200,0.851625,72
14,combo_lr_high_cosine,0.851600,0.851244,68
16,combo_strong_augment,0.848900,0.848695,52
13,combo_kernel5,0.846700,0.845617,43
9,combo_4conv,0.846000,0.846866,34
2,augment_batchnorm_deeper,0.835700,0.835417,41
12,combo_dropout_tiny,0.835100,0.834027,60
15,combo_real_norm,0.834700,0.833983,41
4,augment_deeper,0.807000,0.805164,41
1,augment_batchnorm,0.798700,0.798478,46
6,augment_more_epochs,0.787100,0.786495,54
0,augment,0.763500,0.764562,30
5,augment_dropout_light,0.745000,0.740547,50
27,deeper_3conv,0.739400,0.738148,10
8,batch_norm,0.733600,0.732073,12
7,baseline,0.714800,0.712281,9
36,lr_low,0.714100,0.712868,11
28,dropout_03,0.713000,0.709568,30
37,padding_0,0.711900,0.711563,11
38,pool_4,0.711700,0.714032,15
34,kernel_5,0.703500,0.700650,9
39,stride_2_no_pool,0.643000,0.644236,8
35,lr_high,0.617500,0.620140,19

## 17. Baixar `results/` para trazer de volta ao repositório local

**Só necessário no Colab/Kaggle** (local já grava direto em `../results/`).
Os resultados salvos na VM efêmera somem quando a sessão reinicia — rode
esta célula ao final de cada sessão de experimentos para não perder o
trabalho. No Colab ela gera um `.zip` e baixa direto para a pasta de
Downloads do seu computador; no Kaggle ela só gera o `.zip` em
`/kaggle/working/` — baixe pelo painel lateral **Output** do notebook
(ícone de download ao lado do arquivo). Depois é só extrair por cima da
pasta `results/` local (ou pedir para o Claude fazer isso) e dar
commit/push.

In [27]:
#@title Baixar results/ (Colab/Kaggle)
import shutil

if IN_COLAB:
    from google.colab import files

    zip_path = shutil.make_archive("/content/results_cnn", "zip", str(RESULTS_DIR))
    print("Gerado:", zip_path)
    files.download(zip_path)
elif IN_KAGGLE:
    zip_path = shutil.make_archive("/kaggle/working/results_cnn", "zip", str(RESULTS_DIR))
    print("Gerado:", zip_path, "- baixe pelo painel lateral 'Output' do Kaggle (icone de download ao lado do arquivo).")
else:
    print("Local: results/ ja esta em", RESULTS_DIR, "- nao precisa baixar nada.")

Gerado: /kaggle/working/results_cnn.zip - baixe pelo painel lateral 'Output' do Kaggle (icone de download ao lado do arquivo).