# Mini-projeto 1 - Fase 2: CNN para classificação do CIFAR-10

Continuidade da Fase 1 (MLP, ver `../fase1-mlp/`). A lógica reutilizável (modelo, dados, treino, métricas, checkpointing) vive no pacote `cnn_cifar10` em `../src/`, seguindo exatamente o mesmo padrão da Fase 1 — o notebook fica focado em **definir experimentos e reportar resultados**, não em implementação.

**Integrantes do grupo:** _preencher aqui (nome de todos)_

O que este notebook cobre (conforme o enunciado do mini-projeto):
- Treino de uma CNN no CIFAR-10 com hiperparâmetros configuráveis (nº/tamanho de filtros, kernel size, stride, padding, pooling, dropout, taxa de aprendizagem, além dos já cobertos na Fase 1: ativação, otimizador, função de erro).
- Métricas por classe (acurácia) e globais (acurácia, precision, recall, f1).
- Comparação direta com o melhor resultado do MLP (Fase 1: ensemble `final` = 0.6135 de acurácia) — ver `../../fase1-mlp/README.md`.
- Cada execução de treino é salva automaticamente em `../results/` (pesos + config + métricas + histórico) — ver `../src/cnn_cifar10/checkpointing.py`.

**Recomendação forte: rode este notebook no Google Colab com GPU** (Ambiente de execução > Alterar tipo de ambiente de execução > GPU). CNN é bem mais lenta que MLP em CPU, e o ganho de GPU aqui é de 10-50x+.

## 0. Setup do ambiente

- **Local**: rode a partir de um ambiente onde o pacote já foi instalado (`pip install -e .` na pasta `fase2-cnn/`).
- **Google Colab**: a célula abaixo clona o repositório e instala o pacote automaticamente. O repositório é **privado**, então precisa de um GitHub Personal Access Token (PAT) — ver instruções abaixo, só precisa configurar uma vez.

### Gerar o token (uma vez só)

1. No GitHub: `Settings > Developer settings > Personal access tokens > Fine-grained tokens > Generate new token`.
2. Repository access: `Only select repositories` > `redes-neurais`.
3. Permissions: `Contents` = `Read-only` (só precisa ler/clonar, não escrever).
4. Defina uma expiração (ex.: 90 dias) e gere o token — copie o valor (`github_pat_...`), ele só aparece uma vez.

### Guardar no Colab (uma vez por navegador/conta)

1. No Colab, clique no ícone de chave (🔑 **Secrets**) na barra lateral esquerda.
2. `Add new secret` → nome `GITHUB_TOKEN`, valor = o token copiado acima.
3. Ative o toggle "Notebook access" para este notebook.

A célula abaixo lê o secret automaticamente; se não encontrar, pede o token via prompt (não fica salvo em lugar nenhum do notebook).

In [10]:
#@title Setup (Colab ou local)
import sys
from pathlib import Path

IN_COLAB = "google.colab" in sys.modules

if IN_COLAB:
    import shutil

    BRANCH = "feat/cnn"  #@param {type:"string"}
    # Ajuste para "main" (ou o branch que estiver usando) quando o trabalho da
    # Fase 2 for mesclado - não precisa editar mais nada além desta linha.
    REPO_PATH = "github.com/jpbezerra/redes-neurais.git"
    REPO_DIR = Path("/content/redes-neurais")

    # Se uma tentativa anterior de clone falhou no meio (ex.: token errado),
    # a pasta pode existir mas sem ser um repositorio git valido - nesse caso
    # apagamos e clonamos de novo em vez de só tentar "git pull" nela.
    if REPO_DIR.exists() and not (REPO_DIR / ".git").exists():
        shutil.rmtree(REPO_DIR)

    if not REPO_DIR.exists():
        token = None
        try:
            from google.colab import userdata
            token = userdata.get("GITHUB_TOKEN")
        except Exception:
            token = None
        if not token:
            import getpass
            token = getpass.getpass("Repositorio privado - cole seu GitHub Personal Access Token: ")
        clone_url = f"https://{token}@{REPO_PATH}"
        # o token fica salvo em .git/config só dentro desta VM efêmera do Colab
        # (destruída ao fim da sessão) - necessário para o "git pull" funcionar
        # de novo mais tarde na mesma sessão, sem pedir o token de novo.
        !git clone -q -b {BRANCH} {clone_url} {REPO_DIR}
    else:
        !git -C {REPO_DIR} pull -q origin {BRANCH}

    PROJECT_ROOT = REPO_DIR / "miniprojeto" / "fase2-cnn"
    assert (PROJECT_ROOT / "pyproject.toml").exists(), (
        f"Clone parece ter falhado (pyproject.toml nao encontrado em {PROJECT_ROOT}). "
        f"Confira: (1) BRANCH='{BRANCH}' e o branch certo, (2) o token em Secrets "
        "(GITHUB_TOKEN) esta valido - depois 'Ambiente de execucao > Reiniciar sessao' "
        "e rode esta celula de novo."
    )
    %pip install -q -e {PROJECT_ROOT}
else:
    PROJECT_ROOT = Path.cwd().parent  # notebooks/ -> fase2-cnn/

sys.path.insert(0, str(PROJECT_ROOT / "src"))

DATA_DIR = PROJECT_ROOT / "data"
RESULTS_DIR = PROJECT_ROOT / "results"
print("PROJECT_ROOT:", PROJECT_ROOT)

  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
  Building editable for cnn-cifar10 (pyproject.toml) ... done
PROJECT_ROOT: /content/redes-neurais/miniprojeto/fase2-cnn

In [11]:
#@title Imports
import torch
import matplotlib.pyplot as plt
import pandas as pd

from cnn_cifar10.config import ExperimentConfig
from cnn_cifar10.data import get_dataloaders, CLASSES
from cnn_cifar10.train import fit, fit_or_load
from cnn_cifar10.checkpointing import load_all_metadata
from cnn_cifar10.utils import set_seed, get_device

In [12]:
#@title Device
device = get_device()
print("Usando dispositivo:", device)
if device.type == "cpu":
    print("Aviso: sem GPU disponível. CNN em CPU é bem mais lenta — considere rodar no Colab.")

# No Colab/Linux, num_workers > 0 acelera o carregamento com augmentation
# (no Windows local, exige if __name__ == '__main__': em scripts, então mantemos 0 lá).
NUM_WORKERS = 2 if IN_COLAB else 0

Usando dispositivo: cuda

## 1. Experimento baseline

Arquitetura equivalente à do notebook de referência do professor (`temp/CIFAR10_with_CNNs.ipynb`, adaptação do LeNet-5): 2 blocos convolucionais (32 e 64 filtros, kernel 3x3, padding 1, stride 1) + max pooling 2x2 após cada bloco, seguidos de cabeça densa `120 -> 84 -> 10`. ReLU, Adam, entropia cruzada, sem regularização — ponto de partida para a busca guiada, do mesmo jeito que a Fase 1 partiu do baseline MLP `[64,128,64]`.

In [13]:
baseline_config = ExperimentConfig(
    run_name="baseline",
    conv_channels=(32, 64),
    kernel_size=3,
    stride=1,
    padding=1,
    pool_size=2,
    fc_layers=(120, 84),
    activation="relu",
    optimizer="adam",
    loss="cross_entropy",
    learning_rate=1e-3,
    batch_size=32,
    num_epochs=40,
    patience=5,
    notes="Baseline equivalente ao notebook de referencia (2 conv + 2 pool + 3 fc), ponto de partida da busca guiada da Fase 2.",
    tags=["baseline"],
)

set_seed(baseline_config.seed)
train_loader, val_loader, test_loader = get_dataloaders(
    data_dir=DATA_DIR,
    batch_size=baseline_config.batch_size,
    val_fraction=baseline_config.val_fraction,
    seed=baseline_config.seed,
    num_workers=NUM_WORKERS,
    augment=baseline_config.augment,
    normalization=baseline_config.normalization,
)

result_baseline = fit_or_load(
    baseline_config, train_loader, val_loader, test_loader, device,
    class_names=list(CLASSES), results_dir=RESULTS_DIR,
)
result_baseline["test_scores"]

100%|██████████| 170M/170M [24:04<00:00, 118kB/s]

treinando 'baseline':   0%|          | 0/40 [00:00<?, ?it/s]

Época 1/40 | train_loss=1.3641 | val_loss=1.0566 | val_acc=0.6272
Época 2/40 | train_loss=0.9682 | val_loss=0.9147 | val_acc=0.6770
Época 3/40 | train_loss=0.7919 | val_loss=0.8745 | val_acc=0.6900
Época 4/40 | train_loss=0.6640 | val_loss=0.8211 | val_acc=0.7260
Época 5/40 | train_loss=0.5528 | val_loss=0.8311 | val_acc=0.7314
Época 6/40 | train_loss=0.4561 | val_loss=0.9022 | val_acc=0.7222
Época 7/40 | train_loss=0.3616 | val_loss=0.9661 | val_acc=0.7104
Época 8/40 | train_loss=0.2887 | val_loss=1.0826 | val_acc=0.7142
Época 9/40 | train_loss=0.2280 | val_loss=1.2168 | val_acc=0.7078
Early stopping acionado.
Métricas no conjunto de teste: {'accuracy': 0.7148, 'balanced_accuracy': np.float64(0.7148), 'precision': 0.7129270673384086, 'recall': 0.7148, 'f1_score': 0.7122810504679414}
Acurácia por classe: {'airplane': 0.758, 'automobile': 0.863, 'bird': 0.588, 'cat': 0.495, 'deer': 0.652, 'dog': 0.608, 'frog': 0.85, 'horse': 0.758, 'ship': 0.832, 'truck': 0.744}
[model-saver] Modelo salvo em /content/redes-neurais/miniprojeto/fase2-cnn/results/cnn_baseline_20260907-211552/

{'accuracy': 0.7148,
 'balanced_accuracy': np.float64(0.7148),
 'precision': 0.7129270673384086,
 'recall': 0.7148,
 'f1_score': 0.7122810504679414}

## 2. Leva 1 — variações isoladas (uma alavanca por vez)

Mesmo espírito da leva 1 do MLP: cada configuração muda **um** hiperparâmetro
em relação ao baseline, para medir o efeito isolado antes de combinar
vencedores em rodadas sucessivas (busca gulosa, como nas levas 2-8 do MLP).
Cobre todos os parâmetros pedidos no enunciado da Fase 2: tamanho da rede,
kernel size, stride, padding, dropout, pooling e taxa de aprendizagem — mais
batch norm e augmentation como bônus (mesma cobertura extra feita no MLP).

`num_epochs=30`/`patience=5` (menor que o baseline) para essa leva exploratória
rodar mais rápido — se algum candidato for promissor, pode retreinar depois
com mais épocas.

In [14]:
candidate_configs = [
    ExperimentConfig(
        run_name="kernel_5",
        conv_channels=(32, 64), kernel_size=5, stride=1, padding=2, pool_size=2,
        fc_layers=(120, 84), num_epochs=30, patience=5,
        notes="Kernel 5x5 em vez de 3x3 (padding=2 mantem o tamanho espacial 'same').",
    ),
    ExperimentConfig(
        run_name="stride_2_no_pool",
        conv_channels=(32, 64), kernel_size=3, stride=2, padding=1, pool_size=1,
        fc_layers=(120, 84), num_epochs=30, patience=5,
        notes="Substitui o pooling por stride=2 na propria convolucao (pool_size=1 = sem pooling extra).",
    ),
    ExperimentConfig(
        run_name="padding_0",
        conv_channels=(32, 64), kernel_size=3, stride=1, padding=0, pool_size=2,
        fc_layers=(120, 84), num_epochs=30, patience=5,
        notes="Convolucao 'valid' (sem padding) em vez de 'same' (padding=1) do baseline.",
    ),
    ExperimentConfig(
        run_name="pool_4",
        conv_channels=(32, 64), kernel_size=3, stride=1, padding=1, pool_size=4,
        fc_layers=(120, 84), num_epochs=30, patience=5,
        notes="Janela de pooling maior (4x4 em vez de 2x2) apos cada bloco convolucional.",
    ),
    ExperimentConfig(
        run_name="deeper_3conv",
        conv_channels=(32, 64, 128), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), num_epochs=30, patience=5,
        notes="Rede maior: 3 blocos convolucionais (32/64/128 filtros) em vez de 2.",
    ),
    ExperimentConfig(
        run_name="dropout_03",
        conv_channels=(32, 64), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), dropout=0.3, num_epochs=30, patience=5,
        notes="Dropout 0.3 (Dropout2d nos blocos conv + Dropout na cabeca densa) sobre o baseline.",
    ),
    ExperimentConfig(
        run_name="batch_norm",
        conv_channels=(32, 64), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), batch_norm=True, num_epochs=30, patience=5,
        notes="Adiciona BatchNorm2d apos cada convolucao, sobre o baseline.",
    ),
    ExperimentConfig(
        run_name="lr_low",
        conv_channels=(32, 64), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), learning_rate=5e-4, num_epochs=30, patience=5,
        notes="Learning rate 2x menor que o baseline (1e-3 -> 5e-4).",
    ),
    ExperimentConfig(
        run_name="lr_high",
        conv_channels=(32, 64), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), learning_rate=5e-3, num_epochs=30, patience=5,
        notes="Learning rate 5x maior que o baseline (1e-3 -> 5e-3).",
    ),
    ExperimentConfig(
        run_name="augment",
        conv_channels=(32, 64), kernel_size=3, stride=1, padding=1, pool_size=2,
        fc_layers=(120, 84), augment=True, num_epochs=30, patience=5,
        notes="Data augmentation (crop+flip) no treino, mesma transform da Fase 1.",
    ),
    # Adicione outras variacoes conforme os experimentos forem sendo decididos.
]

In [15]:
experiment_results = {baseline_config.run_name: result_baseline}
for config in candidate_configs:
    if config.run_name in experiment_results:
        continue
    set_seed(config.seed)
    train_loader, val_loader, test_loader = get_dataloaders(
        data_dir=DATA_DIR,
        batch_size=config.batch_size,
        val_fraction=config.val_fraction,
        seed=config.seed,
        num_workers=NUM_WORKERS,
        augment=config.augment,
        normalization=config.normalization,
    )
    experiment_results[config.run_name] = fit_or_load(
        config, train_loader, val_loader, test_loader, device,
        class_names=list(CLASSES), results_dir=RESULTS_DIR,
    )

treinando 'kernel_5':   0%|          | 0/30 [00:00<?, ?it/s]

Época 1/30 | train_loss=1.3761 | val_loss=1.0773 | val_acc=0.6210
Época 2/30 | train_loss=0.9798 | val_loss=0.9474 | val_acc=0.6682
Época 3/30 | train_loss=0.8017 | val_loss=0.8587 | val_acc=0.6958
Época 4/30 | train_loss=0.6711 | val_loss=0.8480 | val_acc=0.7094
Época 5/30 | train_loss=0.5650 | val_loss=0.8566 | val_acc=0.7088
Época 6/30 | train_loss=0.4696 | val_loss=0.9816 | val_acc=0.7060
Época 7/30 | train_loss=0.3946 | val_loss=0.9509 | val_acc=0.7046
Época 8/30 | train_loss=0.3201 | val_loss=1.0678 | val_acc=0.7014
Época 9/30 | train_loss=0.2715 | val_loss=1.1455 | val_acc=0.6986
Early stopping acionado.
Métricas no conjunto de teste: {'accuracy': 0.7035, 'balanced_accuracy': np.float64(0.7034999999999999), 'precision': 0.7066374910321646, 'recall': 0.7035, 'f1_score': 0.7006502013981192}
Acurácia por classe: {'airplane': 0.81, 'automobile': 0.822, 'bird': 0.605, 'cat': 0.443, 'deer': 0.741, 'dog': 0.532, 'frog': 0.776, 'horse': 0.8, 'ship': 0.781, 'truck': 0.725}
[model-saver] Modelo salvo em /content/redes-neurais/miniprojeto/fase2-cnn/results/cnn_kernel_5_20260907-211827/

treinando 'stride_2_no_pool':   0%|          | 0/30 [00:00<?, ?it/s]

Época 1/30 | train_loss=1.4657 | val_loss=1.2343 | val_acc=0.5656
Época 2/30 | train_loss=1.1122 | val_loss=1.0714 | val_acc=0.6166
Época 3/30 | train_loss=0.9286 | val_loss=0.9947 | val_acc=0.6438
Época 4/30 | train_loss=0.7769 | val_loss=1.0364 | val_acc=0.6462
Época 5/30 | train_loss=0.6485 | val_loss=1.0175 | val_acc=0.6592
Época 6/30 | train_loss=0.5277 | val_loss=1.1268 | val_acc=0.6528
Época 7/30 | train_loss=0.4203 | val_loss=1.2312 | val_acc=0.6442
Época 8/30 | train_loss=0.3358 | val_loss=1.3373 | val_acc=0.6516
Early stopping acionado.
Métricas no conjunto de teste: {'accuracy': 0.643, 'balanced_accuracy': np.float64(0.643), 'precision': 0.656135258511737, 'recall': 0.643, 'f1_score': 0.6442358355161343}
Acurácia por classe: {'airplane': 0.715, 'automobile': 0.735, 'bird': 0.443, 'cat': 0.628, 'deer': 0.591, 'dog': 0.429, 'frog': 0.697, 'horse': 0.708, 'ship': 0.752, 'truck': 0.732}
[model-saver] Modelo salvo em /content/redes-neurais/miniprojeto/fase2-cnn/results/cnn_stride_2_no_pool_20260907-212041/

treinando 'padding_0':   0%|          | 0/30 [00:00<?, ?it/s]

Época 1/30 | train_loss=1.4594 | val_loss=1.2677 | val_acc=0.5392
Época 2/30 | train_loss=1.0871 | val_loss=1.0074 | val_acc=0.6392
Época 3/30 | train_loss=0.9220 | val_loss=0.9258 | val_acc=0.6712
Época 4/30 | train_loss=0.8078 | val_loss=0.8668 | val_acc=0.6962
Época 5/30 | train_loss=0.7182 | val_loss=0.8643 | val_acc=0.6976
Época 6/30 | train_loss=0.6436 | val_loss=0.8573 | val_acc=0.7056
Época 7/30 | train_loss=0.5731 | val_loss=0.8575 | val_acc=0.7084
Época 8/30 | train_loss=0.5154 | val_loss=0.9153 | val_acc=0.7060
Época 9/30 | train_loss=0.4605 | val_loss=0.9456 | val_acc=0.6970
Época 10/30 | train_loss=0.4140 | val_loss=0.9779 | val_acc=0.7068
Época 11/30 | train_loss=0.3684 | val_loss=1.1062 | val_acc=0.6906
Early stopping acionado.
Métricas no conjunto de teste: {'accuracy': 0.7119, 'balanced_accuracy': np.float64(0.7119), 'precision': 0.7161356838734905, 'recall': 0.7119, 'f1_score': 0.7115627068926509}
Acurácia por classe: {'airplane': 0.672, 'automobile': 0.846, 'bird': 0.542, 'cat': 0.554, 'deer': 0.702, 'dog': 0.616, 'frog': 0.813, 'horse': 0.717, 'ship': 0.872, 'truck': 0.785}
[model-saver] Modelo salvo em /content/redes-neurais/miniprojeto/fase2-cnn/results/cnn_padding_0_20260907-212345/

treinando 'pool_4':   0%|          | 0/30 [00:00<?, ?it/s]

Época 1/30 | train_loss=1.5506 | val_loss=1.3222 | val_acc=0.5186
Época 2/30 | train_loss=1.1781 | val_loss=1.1063 | val_acc=0.6008
Época 3/30 | train_loss=1.0275 | val_loss=1.0266 | val_acc=0.6318
Época 4/30 | train_loss=0.9317 | val_loss=0.9727 | val_acc=0.6560
Época 5/30 | train_loss=0.8582 | val_loss=0.9159 | val_acc=0.6826
Época 6/30 | train_loss=0.8059 | val_loss=0.9259 | val_acc=0.6746
Época 7/30 | train_loss=0.7627 | val_loss=0.9125 | val_acc=0.6786
Época 8/30 | train_loss=0.7261 | val_loss=0.8881 | val_acc=0.6890
Época 9/30 | train_loss=0.6909 | val_loss=0.8894 | val_acc=0.6978
Época 10/30 | train_loss=0.6608 | val_loss=0.8500 | val_acc=0.7106
Época 11/30 | train_loss=0.6362 | val_loss=0.8553 | val_acc=0.7052
Época 12/30 | train_loss=0.6102 | val_loss=0.8638 | val_acc=0.7094
Época 13/30 | train_loss=0.5886 | val_loss=0.8865 | val_acc=0.7136
Época 14/30 | train_loss=0.5672 | val_loss=0.8604 | val_acc=0.7088
Época 15/30 | train_loss=0.5467 | val_loss=0.9083 | val_acc=0.7126
Early stopping acionado.
Métricas no conjunto de teste: {'accuracy': 0.7117, 'balanced_accuracy': np.float64(0.7117000000000001), 'precision': 0.7221517511422278, 'recall': 0.7117, 'f1_score': 0.7140319294742645}
Acurácia por classe: {'airplane': 0.799, 'automobile': 0.801, 'bird': 0.597, 'cat': 0.597, 'deer': 0.728, 'dog': 0.628, 'frog': 0.794, 'horse': 0.623, 'ship': 0.783, 'truck': 0.767}
[model-saver] Modelo salvo em /content/redes-neurais/miniprojeto/fase2-cnn/results/cnn_pool_4_20260907-212750/

treinando 'deeper_3conv':   0%|          | 0/30 [00:00<?, ?it/s]

Época 1/30 | train_loss=1.4621 | val_loss=1.1451 | val_acc=0.5814
Época 2/30 | train_loss=1.0155 | val_loss=0.9334 | val_acc=0.6628
Época 3/30 | train_loss=0.8111 | val_loss=0.8295 | val_acc=0.7154
Época 4/30 | train_loss=0.6841 | val_loss=0.7696 | val_acc=0.7310
Época 5/30 | train_loss=0.5905 | val_loss=0.7437 | val_acc=0.7458
Época 6/30 | train_loss=0.5081 | val_loss=0.7553 | val_acc=0.7562
Época 7/30 | train_loss=0.4426 | val_loss=0.8259 | val_acc=0.7400
Época 8/30 | train_loss=0.3861 | val_loss=0.8178 | val_acc=0.7404
Época 9/30 | train_loss=0.3335 | val_loss=0.8713 | val_acc=0.7516
Época 10/30 | train_loss=0.2890 | val_loss=0.8740 | val_acc=0.7460
Early stopping acionado.
Métricas no conjunto de teste: {'accuracy': 0.7394, 'balanced_accuracy': np.float64(0.7394), 'precision': 0.7415052746612526, 'recall': 0.7394, 'f1_score': 0.7381475742139827}
Acurácia por classe: {'airplane': 0.804, 'automobile': 0.866, 'bird': 0.708, 'cat': 0.546, 'deer': 0.645, 'dog': 0.553, 'frog': 0.829, 'horse': 0.772, 'ship': 0.871, 'truck': 0.8}
[model-saver] Modelo salvo em /content/redes-neurais/miniprojeto/fase2-cnn/results/cnn_deeper_3conv_20260907-213046/

treinando 'dropout_03':   0%|          | 0/30 [00:00<?, ?it/s]

Época 1/30 | train_loss=1.7307 | val_loss=1.3188 | val_acc=0.5314
Época 2/30 | train_loss=1.4305 | val_loss=1.1912 | val_acc=0.5812
Época 3/30 | train_loss=1.3115 | val_loss=1.1098 | val_acc=0.6212
Época 4/30 | train_loss=1.2425 | val_loss=1.0399 | val_acc=0.6402
Época 5/30 | train_loss=1.1847 | val_loss=0.9919 | val_acc=0.6548
Época 6/30 | train_loss=1.1463 | val_loss=0.9776 | val_acc=0.6602
Época 7/30 | train_loss=1.1125 | val_loss=0.9455 | val_acc=0.6654
Época 8/30 | train_loss=1.0774 | val_loss=0.9559 | val_acc=0.6596
Época 9/30 | train_loss=1.0585 | val_loss=0.9164 | val_acc=0.6818
Época 10/30 | train_loss=1.0373 | val_loss=0.9142 | val_acc=0.6746
Época 11/30 | train_loss=1.0107 | val_loss=0.9092 | val_acc=0.6808
Época 12/30 | train_loss=1.0010 | val_loss=0.8794 | val_acc=0.6862
Época 13/30 | train_loss=0.9871 | val_loss=0.8775 | val_acc=0.6938
Época 14/30 | train_loss=0.9750 | val_loss=0.8806 | val_acc=0.6942
Época 15/30 | train_loss=0.9531 | val_loss=0.8725 | val_acc=0.6998
Época 16/30 | train_loss=0.9441 | val_loss=0.8494 | val_acc=0.7112
Época 17/30 | train_loss=0.9335 | val_loss=0.8659 | val_acc=0.6972
Época 18/30 | train_loss=0.9164 | val_loss=0.8678 | val_acc=0.6960
Época 19/30 | train_loss=0.9113 | val_loss=0.8638 | val_acc=0.7002
Época 20/30 | train_loss=0.8995 | val_loss=0.8406 | val_acc=0.7112
Época 21/30 | train_loss=0.8897 | val_loss=0.8499 | val_acc=0.7056
Época 22/30 | train_loss=0.8867 | val_loss=0.8407 | val_acc=0.7090
Época 23/30 | train_loss=0.8712 | val_loss=0.8326 | val_acc=0.7098
Época 24/30 | train_loss=0.8648 | val_loss=0.8323 | val_acc=0.7122
Época 25/30 | train_loss=0.8579 | val_loss=0.8280 | val_acc=0.7120
Época 26/30 | train_loss=0.8508 | val_loss=0.8283 | val_acc=0.7100
Época 27/30 | train_loss=0.8435 | val_loss=0.8197 | val_acc=0.7164
Época 28/30 | train_loss=0.8347 | val_loss=0.8305 | val_acc=0.7092
Época 29/30 | train_loss=0.8272 | val_loss=0.8241 | val_acc=0.7156
Época 30/30 | train_loss=0.8223 | val_loss=0.8400 | val_acc=0.7052
Métricas no conjunto de teste: {'accuracy': 0.713, 'balanced_accuracy': np.float64(0.713), 'precision': 0.7092452807150121, 'recall': 0.713, 'f1_score': 0.7095681652488525}
Acurácia por classe: {'airplane': 0.795, 'automobile': 0.833, 'bird': 0.546, 'cat': 0.461, 'deer': 0.69, 'dog': 0.609, 'frog': 0.837, 'horse': 0.775, 'ship': 0.794, 'truck': 0.79}
[model-saver] Modelo salvo em /content/redes-neurais/miniprojeto/fase2-cnn/results/cnn_dropout_03_20260907-213918/

treinando 'batch_norm':   0%|          | 0/30 [00:00<?, ?it/s]

Época 1/30 | train_loss=1.2551 | val_loss=0.9936 | val_acc=0.6474
Época 2/30 | train_loss=0.9299 | val_loss=0.9356 | val_acc=0.6710
Época 3/30 | train_loss=0.8011 | val_loss=0.8201 | val_acc=0.7208
Época 4/30 | train_loss=0.7023 | val_loss=0.8060 | val_acc=0.7276
Época 5/30 | train_loss=0.6287 | val_loss=0.8193 | val_acc=0.7212
Época 6/30 | train_loss=0.5607 | val_loss=0.7929 | val_acc=0.7286
Época 7/30 | train_loss=0.4937 | val_loss=0.7854 | val_acc=0.7392
Época 8/30 | train_loss=0.4326 | val_loss=0.8393 | val_acc=0.7288
Época 9/30 | train_loss=0.3769 | val_loss=0.8496 | val_acc=0.7354
Época 10/30 | train_loss=0.3291 | val_loss=0.8819 | val_acc=0.7388
Época 11/30 | train_loss=0.2916 | val_loss=0.9329 | val_acc=0.7356
Época 12/30 | train_loss=0.2469 | val_loss=0.9962 | val_acc=0.7230
Early stopping acionado.
Métricas no conjunto de teste: {'accuracy': 0.7336, 'balanced_accuracy': np.float64(0.7336), 'precision': 0.734222827446799, 'recall': 0.7336, 'f1_score': 0.7320725600937166}
Acurácia por classe: {'airplane': 0.785, 'automobile': 0.8, 'bird': 0.584, 'cat': 0.553, 'deer': 0.732, 'dog': 0.6, 'frog': 0.835, 'horse': 0.815, 'ship': 0.804, 'truck': 0.828}
[model-saver] Modelo salvo em /content/redes-neurais/miniprojeto/fase2-cnn/results/cnn_batch_norm_20260907-214245/

treinando 'lr_low':   0%|          | 0/30 [00:00<?, ?it/s]

Época 1/30 | train_loss=1.4649 | val_loss=1.1954 | val_acc=0.5778
Época 2/30 | train_loss=1.0913 | val_loss=1.0076 | val_acc=0.6392
Época 3/30 | train_loss=0.9197 | val_loss=0.9165 | val_acc=0.6708
Época 4/30 | train_loss=0.8044 | val_loss=0.8526 | val_acc=0.6976
Época 5/30 | train_loss=0.7107 | val_loss=0.8157 | val_acc=0.7176
Época 6/30 | train_loss=0.6250 | val_loss=0.8138 | val_acc=0.7188
Época 7/30 | train_loss=0.5416 | val_loss=0.8260 | val_acc=0.7208
Época 8/30 | train_loss=0.4637 | val_loss=0.8673 | val_acc=0.7212
Época 9/30 | train_loss=0.3953 | val_loss=0.9080 | val_acc=0.7208
Época 10/30 | train_loss=0.3280 | val_loss=0.9375 | val_acc=0.7238
Época 11/30 | train_loss=0.2729 | val_loss=1.0465 | val_acc=0.7192
Early stopping acionado.
Métricas no conjunto de teste: {'accuracy': 0.7141, 'balanced_accuracy': np.float64(0.7141000000000001), 'precision': 0.718703520840902, 'recall': 0.7141, 'f1_score': 0.7128678189521056}
Acurácia por classe: {'airplane': 0.666, 'automobile': 0.846, 'bird': 0.591, 'cat': 0.531, 'deer': 0.769, 'dog': 0.561, 'frog': 0.852, 'horse': 0.699, 'ship': 0.844, 'truck': 0.782}
[model-saver] Modelo salvo em /content/redes-neurais/miniprojeto/fase2-cnn/results/cnn_lr_low_20260907-214548/

treinando 'lr_high':   0%|          | 0/30 [00:00<?, ?it/s]

Época 1/30 | train_loss=1.5655 | val_loss=1.3643 | val_acc=0.5038
Época 2/30 | train_loss=1.3157 | val_loss=1.2692 | val_acc=0.5474
Época 3/30 | train_loss=1.2212 | val_loss=1.2018 | val_acc=0.5658
Época 4/30 | train_loss=1.1634 | val_loss=1.1915 | val_acc=0.5878
Época 5/30 | train_loss=1.1217 | val_loss=1.1348 | val_acc=0.6062
Época 6/30 | train_loss=1.0888 | val_loss=1.1609 | val_acc=0.5958
Época 7/30 | train_loss=1.0628 | val_loss=1.1404 | val_acc=0.5940
Época 8/30 | train_loss=1.0290 | val_loss=1.1341 | val_acc=0.6070
Época 9/30 | train_loss=1.0146 | val_loss=1.1946 | val_acc=0.5852
Época 10/30 | train_loss=0.9843 | val_loss=1.1448 | val_acc=0.6128
Época 11/30 | train_loss=0.9688 | val_loss=1.1463 | val_acc=0.6054
Época 12/30 | train_loss=0.9513 | val_loss=1.1189 | val_acc=0.6252
Época 13/30 | train_loss=0.9363 | val_loss=1.1201 | val_acc=0.6178
Época 14/30 | train_loss=0.9119 | val_loss=1.0990 | val_acc=0.6158
Época 15/30 | train_loss=0.8945 | val_loss=1.1276 | val_acc=0.6148
Época 16/30 | train_loss=0.8763 | val_loss=1.1415 | val_acc=0.6256
Época 17/30 | train_loss=0.8689 | val_loss=1.1367 | val_acc=0.6304
Época 18/30 | train_loss=0.8444 | val_loss=1.1926 | val_acc=0.6190
Época 19/30 | train_loss=0.8429 | val_loss=1.1804 | val_acc=0.6274
Early stopping acionado.
Métricas no conjunto de teste: {'accuracy': 0.6175, 'balanced_accuracy': np.float64(0.6174999999999999), 'precision': 0.6290372700909241, 'recall': 0.6175, 'f1_score': 0.620139987320746}
Acurácia por classe: {'airplane': 0.651, 'automobile': 0.774, 'bird': 0.439, 'cat': 0.493, 'deer': 0.532, 'dog': 0.566, 'frog': 0.699, 'horse': 0.695, 'ship': 0.693, 'truck': 0.633}
[model-saver] Modelo salvo em /content/redes-neurais/miniprojeto/fase2-cnn/results/cnn_lr_high_20260907-215058/

treinando 'augment':   0%|          | 0/30 [00:00<?, ?it/s]

Época 1/30 | train_loss=1.5902 | val_loss=1.2750 | val_acc=0.5310
Época 2/30 | train_loss=1.2676 | val_loss=1.0652 | val_acc=0.6174
Época 3/30 | train_loss=1.1192 | val_loss=1.0431 | val_acc=0.6392
Época 4/30 | train_loss=1.0253 | val_loss=0.8935 | val_acc=0.6856
Época 5/30 | train_loss=0.9672 | val_loss=0.8684 | val_acc=0.6948
Época 6/30 | train_loss=0.9234 | val_loss=0.8589 | val_acc=0.6986
Época 7/30 | train_loss=0.8845 | val_loss=0.8175 | val_acc=0.7142
Época 8/30 | train_loss=0.8575 | val_loss=0.8280 | val_acc=0.7112
Época 9/30 | train_loss=0.8329 | val_loss=0.8012 | val_acc=0.7244
Época 10/30 | train_loss=0.8097 | val_loss=0.7837 | val_acc=0.7258
Época 11/30 | train_loss=0.7967 | val_loss=0.7580 | val_acc=0.7328
Época 12/30 | train_loss=0.7832 | val_loss=0.7473 | val_acc=0.7448
Época 13/30 | train_loss=0.7689 | val_loss=0.7643 | val_acc=0.7368
Época 14/30 | train_loss=0.7517 | val_loss=0.7416 | val_acc=0.7484
Época 15/30 | train_loss=0.7459 | val_loss=0.7174 | val_acc=0.7546
Época 16/30 | train_loss=0.7359 | val_loss=0.6944 | val_acc=0.7614
Época 17/30 | train_loss=0.7225 | val_loss=0.7429 | val_acc=0.7504
Época 18/30 | train_loss=0.7073 | val_loss=0.7063 | val_acc=0.7600
Época 19/30 | train_loss=0.7079 | val_loss=0.7067 | val_acc=0.7558
Época 20/30 | train_loss=0.6968 | val_loss=0.6863 | val_acc=0.7580
Época 21/30 | train_loss=0.6884 | val_loss=0.6853 | val_acc=0.7664
Época 22/30 | train_loss=0.6870 | val_loss=0.6894 | val_acc=0.7642
Época 23/30 | train_loss=0.6754 | val_loss=0.6792 | val_acc=0.7596
Época 24/30 | train_loss=0.6676 | val_loss=0.6963 | val_acc=0.7564
Época 25/30 | train_loss=0.6684 | val_loss=0.6763 | val_acc=0.7670
Época 26/30 | train_loss=0.6614 | val_loss=0.6972 | val_acc=0.7638
Época 27/30 | train_loss=0.6564 | val_loss=0.6548 | val_acc=0.7728
Época 28/30 | train_loss=0.6458 | val_loss=0.6832 | val_acc=0.7694
Época 29/30 | train_loss=0.6464 | val_loss=0.6987 | val_acc=0.7600
Época 30/30 | train_loss=0.6382 | val_loss=0.6681 | val_acc=0.7728
Métricas no conjunto de teste: {'accuracy': 0.7635, 'balanced_accuracy': np.float64(0.7635), 'precision': 0.7716712028049783, 'recall': 0.7635, 'f1_score': 0.7645615214176086}
Acurácia por classe: {'airplane': 0.798, 'automobile': 0.912, 'bird': 0.596, 'cat': 0.664, 'deer': 0.659, 'dog': 0.691, 'frog': 0.821, 'horse': 0.771, 'ship': 0.893, 'truck': 0.83}
[model-saver] Modelo salvo em /content/redes-neurais/miniprojeto/fase2-cnn/results/cnn_augment_20260907-220140/

In [16]:
#@title Tabela comparativa dos experimentos
comparison = pd.DataFrame(
    {name: r["test_scores"] for name, r in experiment_results.items()}
).T.sort_values("accuracy", ascending=False)
comparison

                  accuracy  balanced_accuracy  precision  recall  f1_score
augment             0.7635             0.7635   0.771671  0.7635  0.764562
deeper_3conv        0.7394             0.7394   0.741505  0.7394  0.738148
batch_norm          0.7336             0.7336   0.734223  0.7336  0.732073
baseline            0.7148             0.7148   0.712927  0.7148  0.712281
lr_low              0.7141             0.7141   0.718704  0.7141  0.712868
dropout_03          0.7130             0.7130   0.709245  0.7130  0.709568
padding_0           0.7119             0.7119   0.716136  0.7119  0.711563
pool_4              0.7117             0.7117   0.722152  0.7117  0.714032
kernel_5            0.7035             0.7035   0.706637  0.7035  0.700650
stride_2_no_pool    0.6430             0.6430   0.656135  0.6430  0.644236
lr_high             0.6175             0.6175   0.629037  0.6175  0.620140

## 3. Próximas rodadas

Depois de ver os resultados da leva 1 acima, combine os hiperparâmetros
vencedores em rodadas sucessivas (busca gulosa), como nas levas 2-8 do MLP —
cada rodada informada pelo resultado da anterior. Se as rodadas ficarem
grandes/lentas demais para caber numa célula, considere mover para um
`scripts/run_experiments.py` (ver `../fase1-mlp/scripts/run_experiments.py`
como referência de estrutura).

In [17]:
#@title Comparar todas as execuções salvas
df = load_all_metadata(RESULTS_DIR)
if not df.empty:
    cols = [c for c in ["run_name", "metrics.test_accuracy", "metrics.test_f1_score", "metrics.epochs_trained"] if c in df.columns]
    display(df[cols].sort_values("metrics.test_accuracy", ascending=False) if cols else df)
else:
    print("Nenhuma execucao salva ainda em", RESULTS_DIR)

,run_name,metrics.test_accuracy,metrics.test_f1_score,metrics.epochs_trained
0,augment,0.7635,0.764562,30
3,deeper_3conv,0.7394,0.738148,10
2,batch_norm,0.7336,0.732073,12
1,baseline,0.7148,0.712281,9
7,lr_low,0.7141,0.712868,11
4,dropout_03,0.7130,0.709568,30
8,padding_0,0.7119,0.711563,11
9,pool_4,0.7117,0.714032,15
5,kernel_5,0.7035,0.700650,9
10,stride_2_no_pool,0.6430,0.644236,8
6,lr_high,0.6175,0.620140,19

## 4. Baixar `results/` para trazer de volta ao repositório local

**Só necessário no Colab** (local já grava direto em `../results/`). Os
resultados salvos em `/content/redes-neurais/.../results/` somem quando a
sessão do Colab reinicia — rode esta célula ao final de cada sessão de
experimentos para não perder o trabalho. Ela gera um `.zip` e baixa para a
pasta de Downloads do seu computador; depois é só extrair por cima da pasta
`results/` local (ou pedir para o Claude fazer isso) e dar commit/push.

In [18]:
#@title Baixar results/ (Colab)
if IN_COLAB:
    import shutil
    from google.colab import files

    zip_path = shutil.make_archive("/content/results_cnn", "zip", str(RESULTS_DIR))
    print("Gerado:", zip_path)
    files.download(zip_path)
else:
    print("Local: results/ ja esta em", RESULTS_DIR, "- nao precisa baixar nada.")

Gerado: /content/results_cnn.zip